### ISSUE TITLE
Improve update banner

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1005]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![Screenshot 2022-09-15 at 10 30 04](https://user-images.githubusercontent.com/2109932/190355405-f212b39b-df48-4894-8096-573691ee518c.png)

* it's stuck to the bottom of the list
* there's a horizontal scrollbar on the overview. (Not sure if related to the banner)
* it shows up on https://master--toolpad.mui.com/

### Expected behavior 🤔

* it's positioned fixed, perhaps it even makes sense to use a `Snackbar`?
* no horizontal scrollbar
* it shouldn't show up on https://master--toolpad.mui.com/
    * should it appear every time a new version comes out? or once dismissed, it's dismissed forever until you upgrade?

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by bharatkashyap** [comment]
> ### Expected behavior 🤔
> * it's positioned fixed, perhaps it even makes sense to use a `Snackbar`?
> * no horizontal scrollbar

In hindsight, this makes sense because the content isn't too much anyway. 

This should also do away with the scrollbar issue (although I did investigate the horizontal scrollbar issue before but unsuccessfully. It might not be related to the banner.)

**Comment by bytasv** [comment]
I'd also consider positioning it at the top (not sure if this was discussed?) as that way it's easier to capture attention

**Comment by Janpot** [comment]
I don't feel like this message is important enough to try to capture all attention. All that will happen is users clicking it away faster to get it out of the way, reducing the chance of them upgrading. You rather want them to keep it around as a reminder for themselves. I would consider
* to only showing it on the overview page.
* to also show an "update available" label next to the version in the help menu
   ![Screenshot 2022-09-15 at 11 47 53](https://user-images.githubusercontent.com/2109932/190373638-7f5ea829-5d90-4167-864d-4ca8f574ad89.png)
   After they've dismissed, I'd also put a short "update available" link somewhere on the overview page that opens update instructions.

**Comment by bharatkashyap** [comment]
The horizontal scrollbar seems to be unrelated to the banner, see https://github.com/mui/mui-toolpad/pull/1006#issue-1374257777

**Comment by oliviertassinari** [comment]
💯 to remove this banner. it feels at least x3 too distracting compared to the value it brings. Could we do a benchmark of how other self-hosted projects handle updates notification and see what feels great?
