### ISSUE TITLE
Add captcha to online demo

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#1010]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

From https://github.com/mui/mui-toolpad/issues/592
We may want to have a captcha in the demo, to be solved before users can create a new application.

### Examples 🌈

Possible solutions:
- https://www.google.com/recaptcha/about/ ?

(I'm not very familiar with captcha solutions)

### Motivation 🔦

Reduce bot traffic in demo, or application spam.

**Comment by bharatkashyap** [comment]
I've used https://www.hcaptcha.com/ before, did the job well
