### ISSUE TITLE
Improve the self-host flow from landing page

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1029]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Problem: The count of users who have shown interest in signing up is similar to the number of users who have clicked 'Self-host'. But the docker pull count is relatively low because the journey is not clear. Suggestions:

1. Currently, user lands [here](https://mui.com/toolpad/getting-started/overview/) instead we should have a dedicated page for Docker instructions. The title should be Installation.
2. Even the current title for Docker instructions is "Prerequisites" rather it should be Installation.

**Comment by oliviertassinari** [comment]
> But the docker pull count is relatively low because the journey is not clear. 

The "because" feels like a big leap in the reasoning. I think that no download could also be explained by: "I'm not convinced, I won't try to use it".

**Comment by bytasv** [comment]
I think it won't hurt to have those steps in their own section, but I have to agree, I think this might not be the main reason as it's after all just a few steps to follow however as users maybe the expectations are different what you will get after visiting "self hosted" version, after all it's one of the biggest CTAs on the page so it's also possible that people end up there just out of curiosity

**Comment by prakhargupta1** [comment]
> The "because" feels like a leap in reasoning. I think that a user dropping out (no downloads) could also be explained by: "I'm not convinced enough for the effort that is asked of me".

I agree, it can't be the only reason but certainly one of the reasons worth improving.

**Comment by Janpot** [comment]
@prakhargupta1 Just curious, did you see a noticable difference in docker pulls in the last two weeks?

**Comment by prakhargupta1** [comment]
There has been an organic increment in the [daily count,](https://docs.google.com/spreadsheets/d/1V-TWJvgX0BFn4Z6xAriocEDWLM15RfDbH1pklbjCk18/edit?usp=sharing) but I don't think we can attribute it to this change.
