### ISSUE TITLE
Editor crashes when creating fetch connection query

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#1032]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Editor crashes when creating a fetch connection query.

https://user-images.githubusercontent.com/10789765/191089930-d26cc8fb-37f4-44e5-a91e-ee62a85c628a.mov

### Expected behavior 🤔

Editor should not crash when creating a fetch connection query.

### Steps to reproduce 🕹

Steps:

1. Create new app
2. Create Fetch connection
3. Start creating query from connection
4. Application crashes

**Comment by prakhargupta1** [comment]
Duplicate to #1001

**Comment by Janpot** [comment]
@apedroferreira Can you confirm this is a duplicate to https://github.com/mui/mui-toolpad/issues/1001? As far as I understand, in https://github.com/mui/mui-toolpad/issues/1001 the editor doesn't crash, it's just showing an error in the node.js console.

**Comment by apedroferreira** [comment]
> @apedroferreira Can you confirm this is a duplicate to #1001? As far as I understand, in #1001 the editor doesn't crash, it's just showing an error in the node.js console.

yep, seems to be caused by the same bug - same error message
