### ISSUE TITLE
actionbar.css monaco editor fail 

### ISSUE THREAD

**Issue by kzmKZuzmo** [mui/mui-toolpad#1034]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/16986250/191208937-4d95404f-97c6-4c06-b371-00a29b515576.png)
 
```
error - ../../node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css
@mui/toolpad-app: [dev:*next] Global CSS cannot be imported from within node_modules.
@mui/toolpad-app: [dev:*next] Read more: https://nextjs.org/docs/messages/css-npm
@mui/toolpad-app: [dev:*next] Location: ..\..\node_modules\monaco-editor\esm\vs\base\browser\ui\actionbar\actionViewItems.js
```

```
@mui/toolpad-app: [dev:*prisma] ma.prisma
@mui/toolpad-app: [dev:*prisma]
@mui/toolpad-app: [dev:*prisma] ✔ Generated Prisma Client (4.3.1 | library) to .\prisma\generated\client in 191m
@mui/toolpad-app: [dev:*prisma] s
@mui/toolpad-app: [dev:*prisma]
@mui/toolpad-app: [dev:*function-runtime] [watch] build finished, watching for changes...
@mui/toolpad-app: [dev:*react-devtools] [watch] build finished, watching for changes...
@mui/toolpad-app: [dev:*next] event - compiled client and server successfully in 1557 ms (1545 modules)
@mui/toolpad-app: [dev:*next] wait  - compiling...
@mui/toolpad-app: [dev:*next] event - compiled client and server successfully in 226 ms (1545 modules)
@mui/toolpad-app: [dev:*typings] yarn run dev:typings exited with code 0
@mui/toolpad-app: [dev:*next] wait  - compiling /middleware...
@mui/toolpad-app: [dev:*next] event - compiled successfully in 52 ms (43 modules)
@mui/toolpad-app: [dev:*next] wait  - compiling /_toolpad/[[...index]] (client and server)...
@mui/toolpad-app: [dev:*next] (node:20220) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
@mui/toolpad-app: [dev:*next] (Use `node --trace-deprecation ...` to show where the warning was created)
@mui/toolpad-app: [dev:*react-devtools] [watch] build started (change: "../../../../../package.json")
@mui/toolpad-app: [dev:*function-runtime] [watch] build started (change: "../../../../../package.json")
@mui/toolpad-app: [dev:*react-devtools] [watch] build finished
@mui/toolpad-app: [dev:*function-runtime] [watch] build finished
@mui/toolpad-app: [dev:*next] error - ../../node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css
@mui/toolpad-app: [dev:*next] Global CSS cannot be imported from within node_modules.
@mui/toolpad-app: [dev:*next] Read more: https://nextjs.org/docs/messages/css-npm
@mui/toolpad-app: [dev:*next] Location: ..\..\node_modules\monaco-editor\esm\vs\base\browser\ui\actionbar\actionViewItems.js
@mui/toolpad-app: [dev:*next] Could not find files for /_toolpad/[[...index]] in .next/build-manifest.json
@mui/toolpad-app: [dev:*next] Could not find files for /_toolpad/[[...index]] in .next/build-manifest.json
```

### Steps to reproduce 🕹

Steps:

1.download your project
2.add .env
3. Run
 "dev": "dotenv cross-env FORCE_COLOR=1 lerna -- run dev --stream --parallel --scope @mui/toolpad-core --scope @mui/toolpad-components --scope @mui/toolpad-app",
4. open localhost:3000
5. create project
6. edit project
7.  faild

### Context 🔦

I get this error after first run  your project

### Your environment 🌎

  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42)
  npmPackages:
    @emotion/react:  11.10.4
    @emotion/styled:  11.10.4
    @mui/base:  5.0.0-alpha.96
    @mui/core-downloads-tracker:  5.10.4
    @mui/icons-material:  5.10.3
    @mui/lab:  5.0.0-alpha.98
    @mui/material:  5.10.4
    @mui/monorepo: https://github.com/mui/material-ui.git => 5.10.5
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.4
    @mui/system:  5.10.4
    @mui/toolpad-app:  0.0.18
    @mui/toolpad-components:  0.0.18
    @mui/toolpad-core:  0.0.18
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.1
    @mui/x-data-grid-generator:  5.17.1
    @mui/x-data-grid-premium:  5.17.1
    @mui/x-data-grid-pro:  5.17.1
    @mui/x-date-pickers:  5.0.0
    @mui/x-date-pickers-pro:  5.0.0
    @mui/x-license-pro:  5.17.0
    @types/react:  18.0.19
    react:  18.2.0
    react-dom:  18.2.0
    typescript: ^4.8.2 => 4.8.2

**Comment by bytasv** [comment]
Hey @kzmKZuzmo, I've just tried reproducing this but couldn't get the error. Could you please specify each step you took to end up in this situation?

What I've done on my side was:
1. Git clone repo
2. Ran `yarn install`
3. Ran `yarn dev`
4. Opened toolpad app on the url reported in terminal
5. Got no errors that you mentioned

Were there any other steps you took inside app? any specific page that you visited?

**Comment by kzmKZuzmo** [comment]
yes, I can open the app on browser its work 
![image](https://user-images.githubusercontent.com/16986250/191242934-01becefe-7ce5-452d-b5de-5ed808ba755b.png)
but when I trying the edit the project I got this error... (secondTest|test > edit > error screen)

**Comment by prakhargupta1** [comment]
Hey @kzmKZuzmo We would need more info about your environment, example [issue](https://github.com/mui/material-ui/issues/34194) for reference to the information that would be helpful.

**Comment by kzmKZuzmo** [comment]
check it (its updated)

**Comment by oliviertassinari** [comment]
@kzmKZuzmo Could you try with this change #1042?

**Comment by mnajdova** [comment]
> @kzmKZuzmo Could you try with this change https://github.com/mui/mui-toolpad/pull/1042?

This works 👍
