### ISSUE TITLE
NodeRuntimeWrapper is not required when deploying app?

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1035]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

NodeRuntimeWrapper wrap children with ErrorBoundary and NodeRuntimeContext.
It maybe bring a little performance loss for one node. But it is common that there are over 30 nodes in one page of real app.

```
function RenderedNodeContent({ node, childNodeGroups, Component }: RenderedNodeContentProps) {
  ...

  return (
    <NodeRuntimeWrapper nodeId={nodeId} componentConfig={Component[TOOLPAD_COMPONENT]}>
      {isLayoutNode ? (
        <Component {...props} />
      ) : (
        <Box
          sx={{
            display: 'flex',
            alignItems: boundLayoutProps.verticalAlign,
            justifyContent: boundLayoutProps.horizontalAlign,
          }}
        >
          <Component {...props} />
        </Box>
      )}
    </NodeRuntimeWrapper>
  );
}
```

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by apedroferreira** [comment]
Thanks for reporting this issue @WangLarry.
Not sure how plausible it would be to not to wrap each component with this - we'd also have to measure how much this is affecting performance to see if it's worth tackling.

**Comment by WangLarry** [comment]
NodeRuntimeContext inside of it  is unnecessary.

**Comment by Janpot** [comment]
> NodeRuntimeContext inside of it is unnecessary.

At the moment, it's indeed only used by the editor. But unless there's a significant measurable performance hit, I think we can live with it, the context value should be stable for the lifetime of the component, so I don't expect there to be any problem. I believe there are more important performance issues to focus on in the application runtime.
