### ISSUE TITLE
Allow adding a new row to the data grid

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1038]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The new row should be editable and should write back to the data source. For the scope of this ticket we'll focus on Fetch data source.

Relates to #994

**Comment by bharatkashyap** [comment]
Closing as on: https://github.com/mui/mui-toolpad/issues/1039#issuecomment-1531005595
