### ISSUE TITLE
Support editing page title

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1051]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, when creating new page, the name and title of it are same value. Lately, can edit name of page, but can not update or edit title.

**Comment by apedroferreira** [comment]
@WangLarry Not sure I understand this issue, could you please try to explain step-by-step or provide some visual examples?

From what I see right now it's possible to change the name in the app in the home page:

<img width="1792" alt="Screen Shot 2022-09-27 at 17 34 15" src="https://user-images.githubusercontent.com/10789765/192584551-d8b6a981-cca3-4394-95ab-51a13c072c3a.png">

and the name of a page can be set upon creating the page or edited in the right-side panel:

<img width="570" alt="Screen Shot 2022-09-27 at 17 34 38" src="https://user-images.githubusercontent.com/10789765/192584650-a8c7d3fb-5dcd-4d02-bfb1-3b4e363f3e1a.png">
<img width="601" alt="Screen Shot 2022-09-27 at 17 34 29" src="https://user-images.githubusercontent.com/10789765/192584635-652f76b0-688c-4dc4-8b5f-937386261d8e.png">

**Comment by WangLarry** [comment]
This title is html title, will show in tab of browser.

**Comment by apedroferreira** [comment]
> This title is html title, will show in tab of browser.

Ah, I see what you mean by page title. Thank you!

**Comment by prakhargupta1** [comment]
Relates to #754
