### ISSUE TITLE
Support custom component library

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1062]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently custom component in one app, can not reuse in another app. If supporting a custom component library, it will be convenient. Public library, team library, private library...

**Comment by prakhargupta1** [comment]
In the new Toolpad, this is supported in 2 ways:
1. An app is a bigger construct overall; multiple pages share the same component library. All custom components reside in the component library (drawer)
2. The code for all custom components can be easily shared among teams through GitHub.
