### ISSUE TITLE
Issue with fetch query preview

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1067]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have 2 queries in [this](https://master--toolpad.mui.com/_toolpad/app/cl56qkrj70035aqtojzlqkzr0/pages/cl56qkrjj0002aqto0wxe0kji) app.

1. fetch_target_url
2. test_query

1st one complies to the API by taking some parameter while 2nd is a static URL. Both are same URLs eventually, but somehow 1st one doesn't give me a preview but 2nd one does. Can we troubleshoot this?

Another point of concern: For 2nd query which works fine, the network panel shows an alert icon and when clicked, shows some error. Can we check this too?

### Expected behavior 🤔

Both should work the same way and show preview.

### Steps to reproduce 🕹

Steps:

1. Open the app
2. Run the 2 queries separately

**Comment by Janpot** [comment]
Yes, your transform should return a function body.i.e. it has

```tsx
(data) => {
  return (
    data.items
  )  ;
}
```

while it should have 

```tsx
return data.items;
```

We should show a better feedback when the transform function returns `undefined`. https://github.com/mui/mui-toolpad/issues/1083
