### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#1082]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/pages/cl4hla87800029xoihl7tf4qz, I can't make any changes

<img width="584" alt="Screenshot 2022-10-03 at 01 30 45" src="https://user-images.githubusercontent.com/3165635/193481143-5190730a-6644-45f3-839c-10305f9978e3.png">

The request says pending forever.

On the server side, I see this log:

<img width="656" alt="Screenshot 2022-10-03 at 01 33 44" src="https://user-images.githubusercontent.com/3165635/193481230-067b8786-8d43-4d33-becd-4bedb16cf00e.png">

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/pages/cl4hla87800029xoihl7tf4qz
2. Drap a Paper component in the canvas.
3. 💥 It never saves
   <img width="146" alt="Screenshot 2022-10-03 at 17 59 57" src="https://user-images.githubusercontent.com/3165635/193623462-95d68b22-b7c9-42fb-b401-24c2981f8aae.png">

### Context 🔦

I wanted to try https://github.com/mui/mui-toolpad/issues/419 out, to use the MUI X date picker.

**Comment by oliviertassinari** [comment]
@apedroferreira I have added steps to reproduce.

**Comment by WangLarry** [comment]
same as: https://github.com/mui/mui-toolpad/issues/1057?
