### ISSUE TITLE
Unable to fetch images in "Dog Images" template app

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#1086]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

It's not possible to fetch new dog images in the respective template app unless a sub breed is defined.
This seems to be because the " sub breed" input now defaults to "January" when it's empty, which is one of the default values for the Select component.

### Expected behavior 🤔

It should be possible to fetch new dog images in the respective template app even if sub-breed is empty, or has no options.

### Steps to reproduce 🕹

Steps:

1. Make new app from the "Fetch images" template (app that fetches dog images according to breeds).
2. Try to fetch an image.
3. No new image is fetched - the default image stays the same.

**Comment by WangLarry** [comment]
When component rended at first time, binding value has not evaluated yet. At this time, should use it's initial value in dom.

**Comment by WangLarry** [comment]
@Janpot 
https://github.com/mui/mui-toolpad/pull/1091#issuecomment-1267829977

**Comment by bharatkashyap** [comment]
Fixed by #1106
