### ISSUE TITLE
circleci test_static consumes OOM

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1101]
### Current behavior 😯

Regularly seeing `test_static` circleci jobs fail because of [OOM](https://support.circleci.com/hc/en-us/articles/115014359648-Exit-Code-137-Out-of-Memory) issues.

example: https://app.circleci.com/pipelines/github/mui/mui-toolpad/3578/workflows/b14c82c8-b004-45c1-b1ca-5a30412b6154/jobs/13481

```
@mui/toolpad-app: [build:*next] Killed
@mui/toolpad-app: [build:*next] error Command failed with exit code 137.
@mui/toolpad-app: [build:*next] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@mui/toolpad-app: [build:*next] yarn run build:next exited with code 137
```

[Insights](https://app.circleci.com/insights/github/mui/mui-toolpad/workflows/pipeline/jobs) confirmed an increase in max memory consumption since Sept 30

![Screenshot 2022-10-06 at 10 07 03](https://user-images.githubusercontent.com/2109932/194257787-a87506cb-00b3-44cf-ba7a-4882ad51bbde.png)

Might be caused by https://github.com/mui/mui-toolpad/pull/1043. I'm putting my money on the [source map changes](https://github.com/mui/mui-toolpad/blob/f0b69faa369f344c4225592eedc06f08ca5dffa6/packages/toolpad-app/next.config.mjs#L173) 🙂 

_We were already quite close to 100%, so if we can't bring memory consumption down, scaling the instance may be in order._

**Comment by bytasv** [comment]
Do we currently also generate sourcemaps when running out tests? Wondering if we could easily test the assumption about sourcemaps impact by opening PR where we disable sourcemaps generation and comparing with the one that has it enabled? 🤔

**Comment by apedroferreira** [comment]
Let's not upload sourcemaps with Sentry, doesn't make sense for us to do it since we're open source. Hopefully that will help.

**Comment by Janpot** [comment]
I believe it'll be sourcemap generation that will be heavy, not the uploading

**Comment by apedroferreira** [comment]
> I believe it'll be sourcemap generation that will be heavy, not the uploading

Yep I expressed myself a bit wrong, if it's Sentry that's generating them during the build and we can skip that it should be fine.

**Comment by bytasv** [comment]
Sentry should not be generating sourcemaps, it should only upload them, our build is suppose to generate sourcemaps, so that would mean disabling sourcemaps for our build

**Comment by Janpot** [comment]
> Sentry should not be generating sourcemaps, it should only upload them, our build is suppose to generate sourcemaps, so that would mean disabling sourcemaps for our build

The sentry plugin wraps the next.js config and alters it to so that our build generates sourcemaps in production and then it uploads them at the end of the build.

I think what we could do is:

* set `productionBrowserSourceMaps` in the next.js config to make sure sourcemaps are generated in our build (sentry plugin should do it under the hood as well but let's not rely on that).
* set `hiddenSourceMaps` to `false` in the Sentry plugin to make sure our sources contain a `sourceMappingURL` directive. We want this so that we can debug in production, and so that the Sentry backend can locate them as well
* set `dryRun` to `true` to avoid Sentry from uploading the sourcemaps to their backend after the build
