### ISSUE TITLE
Why theme is not being applied?

### ISSUE THREAD

**Issue by WangLarry** [mui/mui-toolpad#1120]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I try to extract general components into a new module. But the final result is that theme is not applied to these component.

1.  tsup config:
```typescript
export default defineConfig({
  clean: true,
  dts: {
    entry: {
      index: "src/index.tsx",
      TypescriptEditor: "src/TypescriptEditor.tsx",
      JsonEditor: "src/JsonEditor.tsx",
      MonacoEditor: "src/MonacoEditor.tsx",
    },
  },
  entry: [
    "src/index.tsx",
    "src/TypescriptEditor.tsx",
    "src/JsonEditor.tsx",
    "src/MonacoEditor.tsx",
  ],
  external: ["react"],
  format: ["esm"],
  minify: isProduction,
  sourcemap: true,
```

2. package.json: 
```json
"main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "type": "module",
  "files": [
    "dist/*"
  ],
  "exports": {
    ".": "./dist/index.js",
    "./dist/TypescriptEditor.js": "./dist/TypescriptEditor.js",
    "./dist/JsonEditor.js": "./dist/JsonEditor.js",
    "./dist/MonacoEditor.js": "./dist/MonacoEditor.js"
  },
```
3. components:
MapEntriesEditor.tsx,  TypescriptEditor.tsx, JsonEditor.tsx, MonacoEditor.tsx, .....

4. MapEntriesEditor does not use theme in toolpad. Function-datasource client use MapEntriesEditor, the. following picture show height is more taller, not use small size in theme.

<img width="1731" alt="截屏2022-10-09 22 09 37" src="https://user-images.githubusercontent.com/5869244/194761511-5678e65b-7fd4-4e41-9e7e-06051542ede7.png">

5. others functions of component work well, just face this problem now

**Comment by WangLarry** [comment]
This is more clear:
<img width="1731" alt="截屏2022-10-09 22 42 51" src="https://user-images.githubusercontent.com/5869244/194763164-37a59e1d-9c9c-4cb7-9fa5-493e0779f2dd.png">

```javascript
// Create a theme instance.
const theme = createTheme({
  components: {
    MuiTextField: {
      defaultProps: {
        size: "small",
        variant: "filled",   <<-------- added
      },
    },
....

 palette: {
     primary: {
      main: "#e91e63",  <<----  // pink, original: "#556cd6",
    },
```

**Comment by Janpot** [comment]
@WangLarry Before you pour a lot of effort into this, for now our general strategy will be to develop our Toolpad specific components inside the `src/components` folder and keep it there, this keeps the development cycle short. If we find that the MUI community expresses a need for having any of these components, we may think about promoting them to MUI (or MUI X).

(btw, your specific problem here looks like you're not externalizing @mui/material packages)

**Comment by WangLarry** [comment]
@Janpot 
I agree with you. What I do now is to get familiar with the code as soon as possible and learn from the modification. :)

**Comment by Janpot** [comment]
Closing this as there is no action required from the Toolpad team
