### ISSUE TITLE
Index Toolpad docs in the Algolia search

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Search bar is essential for our users to navigate well between MUI products.
Initially there is no need to show Toolpad docs in the search results. This is a task for future.

Stemmed from: https://github.com/mui/mui-toolpad/issues/1124

## Approach:

- Similar to how X docs isolate their search from core, we will provide a search for Toolpad-only
- Ask Jun for a getting started

**Comment by oliviertassinari** [comment]
I think that the important next step will be to monitor all the no results searches and fix them; one by one.

**Comment by Janpot** [comment]
Currently been investigating searches with no result. It is not possible to filter them by the "product" attribute, which makes it quite cumbersome to get toolpad specific data out of Algolia. Will have to investigate whether Algolia analytics unlocks this for us.

**Comment by Janpot** [comment]
Closing this as we can now filter Algolia search analytics by product.
