### ISSUE TITLE
Umbrella: feedback building GitHub supports tools

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#1163]
This is a list of pain points that I faced while building for https://www.notion.so/mui-org/Set-GitHub-scope-labels-12a84fdf50e44595afc55343dac00fca. I thought that it might be interesting for the rest of the team to get a perspective on this. I have seen a lot of things that we could improve, but it doesn't mean that we should. I mean for a lot of them we need to consider **when** or even if it's something to fix 😁.

The apps:

1. https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/ip23ggo
2. https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/e943n9y

The pain points:

1. #1157
2. I have exhausted my GitHub with 5,000 requests/hour in almost no time. I'm not sure how. One of my assumptions is because of this option:

<img width="196" alt="Screenshot 2022-10-16 at 01 13 09" src="https://user-images.githubusercontent.com/3165635/196010870-dab9c401-1084-43e6-bf60-2dc15138812d.png">

I have now disabled it to see if it's the origin of the problem.

3. #385 The GitHub API returns a total number of results that can be e.g. 124 but would only return pages of 30 rows. This can be quite confusing in the UI:

<img width="200" alt="Screenshot 2022-10-16 at 01 14 54" src="https://user-images.githubusercontent.com/3165635/196010900-df1e51c3-10ad-44dc-b73c-db95baf8da4b.png">

4. #827 I'm using the data grid with cells that are links. It would be great if I could click them:

<img width="373" alt="Screenshot 2022-10-16 at 01 15 26" src="https://user-images.githubusercontent.com/3165635/196010912-2cdeaddf-edf1-4adb-a978-c3ae27e65d76.png">

Similar to how it works with Metabase or Notion.

5. #1174 The point 4. made me wonder if it wouldn't be great to support custom column type, where you could create custom components and use them there. For example, to render https://mui-plus.vercel.app/components/Sparkline inside the cells.
6. I have added a quick description below the header. Having #756 would help.
7. The default size of the button feels quite big. I'm missing a size option.
8. #1172 I had two create almost two identical queries. I wish I could have the option to duplicate them.
9. #1175 When you drop a Typography component in a page, it has a default variant of body1 but the UI doesn't reflect it:

<img width="1111" alt="Screenshot 2022-10-16 at 01 21 45" src="https://user-images.githubusercontent.com/3165635/196011054-0d03be4b-3640-4618-92f9-5f52f395c7fb.png">

10. The UX to add and remove columns is frustrating. I can't reorder columns. I can't delete all the columns at once. If I spam click on the delete button, the dialog moves each time I delete a column, sometimes it opens the default view. I have tried Retool tool, but it's super painful with them.
11. #226 I had a couple of cases where I wanted to undo my change, but couldn't.

At the end of the day I could solve my ops problem with Toolpad, it matters more :). I have tried a bit to recreate this on Retool, but I'm not convinced their DX is better.

**Comment by Janpot** [comment]
1. 👍 
2. We should set a `staleTime` in `react-query` in the runtime. I think it's by default `0` and it makes the page constantly revalidate queries. Additionally, we could investigate whether we can integrate their [devtools](https://tanstack.com/query/v4/docs/devtools) in the toolpad editor. I believe we can get rid of the "refetch on window focus" option. https://github.com/mui/mui-toolpad/issues/1093
3. We're currently missing an abstraction to represent an abstract collection. See https://github.com/mui/mui-toolpad/issues/385. We could try to get a bit more mileage out of the queries before we dive into that.
4. I believe it's a matter of adding more column types. See https://github.com/mui/mui-toolpad/issues/827. Cataloging what's missing is probably step one.
5. We could create a "waiting for 👍" ticket
6. 👍 . would also be nice if we could just write inline markdown and have rows with app components in between (i.e. Toolpad/Notion mashup)
7. We could also make this part of your theme to encourage uniformity
8. 👍 
9. I believe that's a bug
10. Yes, this UI always was sort of temporary, I think there's an opportunity to figure out a good UX from the ground up. FYI, you can also reorder the columns on the grid itself, but I agree that the columns definition interface should support this
11. https://github.com/mui/mui-toolpad/issues/226

> I have tried a bit to recreate this on Retool, but I'm not convinced their DX is better.

But is Toolpad's better? or equally meh?

**Comment by oliviertassinari** [comment]
> But is Toolpad's better? or equally meh?

I'm used to how Toolpad works, so it was definitely better on Toolpad.

Compared to pro-code, since the app is really simple, the value I got is:

1. not having to care about a bunch of things: hosting, git, prettier, updating dependencies
2. learning new APIs/spending time on the docs of them: react-query, CSS, data grid

**Comment by Janpot** [comment]
> Sometimes having text to describe your state is nicer than something visual.

I believe this is one of the primary hurdles to make pro-code developers use low-code tools. I think it goes slighty further than that, for textual representation to be useful I need a frictionless integration with my other tools (code editors, source control, linters,...).

I wonder whether we rather should've started by creating a declarative configuration file format to build internal apps/admin panels, with a CLI that generates project files from this configuration, and build Toolpad as a GUI that manipulates the configuration files through drag&drop.

**Comment by oliviertassinari** [comment]
@Janpot Actually, I have opened a support ticket to Notion for this exact same challenge: https://about.gitlab.com/handbook/handbook-usage/#wiki-handbooks-dont-scale.

**Comment by oliviertassinari** [comment]
2. Oh wow, this one had an unintended consequence, all the Netlify deploys are broken now 😆 

> Error: {"message":"API rate limit exceeded for user ID 3165635.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

https://app.netlify.com/sites/material-ui/deploys/634c915abd072c00097c02ee. That ID, it's me https://avatars.githubusercontent.com/u/3165635. I'm creating a new token with another account for Netlify.

**Comment by Janpot** [comment]
I'm opening https://github.com/mui/mui-toolpad/pull/1167 to deal with this short term

**Comment by prakhargupta1** [comment]
> 3. We're currently missing an abstraction to represent an abstract collection. See https://github.com/mui/mui-toolpad/issues/385. We could try to get a bit more mileage out of the queries before we dive into that.

This can help me [here](
https://master--toolpad.mui.com/_toolpad/app/cl1on1bd80041a1pdrrfdt0rq/pages/e303n3o). The API is returning more than 500 records. 500 being the limit of 1 hit, to get the second batch I have to set an offset=500. If the entire data could come in a collection then doing further operations would be easy.

**Comment by oliviertassinari** [comment]
This issue's description now has almost all the pain points linked to standalone GitHub issues 👌.

I think that we can close this issue once we solve the GitHub API rate limit issue. It's probably the most important of all of the items, the app is usable without this problem being solved.

**Comment by oliviertassinari** [comment]
> the GitHub API rate limit problem.

@Janpot I wonder if the origin isn't different, while I was building this app, I was also trying https://airbyte.com/ to sync all the data of our GitHub repositories to a database we could run SQL queries. This might have been very API request intensive.

**Comment by oliviertassinari** [comment]
I'm closing for now, I need to figure out what's at the origin of my GitHub account API calls being rate limited. I have revoked all my API keys.

**Comment by oliviertassinari** [comment]
It looks like my issue with GitHub was Notion, not Toolpad:

<img width="848" alt="Screenshot 2022-10-24 at 16 37 52" src="https://user-images.githubusercontent.com/3165635/197552963-fba3c37e-9f40-401a-b2e3-fc190c2f54b0.png">
