### ISSUE TITLE
Support duplication of queries

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1172]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

An app may involve copying a query.
Just like duplicating a component we should support duplicating queries.

For now, the scope of duplication will be limited to the app. Later on we can support Global queries/copying queries from 1 app to the other.

1. Show a duplicate button just like we show components
2. Naming of the query?
3. How to show duplicate button?

**Comment by oliviertassinari** [comment]
@prakhargupta1 I have updated the issue title, prefer the active tense.
