### ISSUE TITLE
Quickly adding components leads to error

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#1221]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Start dragging any component from drawer onto canvas
2. Upon 3rd or 4th component (maybe it will need more?) you should get `node not found` error. Seems that it doesn't matter what kind of component is being added
<img width="714" alt="image" src="https://user-images.githubusercontent.com/437214/198314131-9fa2ba8a-15e3-43f8-b767-303eaaf3ce1b.png">

https://user-images.githubusercontent.com/437214/198314954-09f6fdb6-aed1-4484-82ec-e9c1bf03b440.mov

### Current behavior 😯

Prod build swallows error and we can continue to work, seems that it's only visible in the console.

Locally we get an error dialog

### Expected behavior 🤔

No error happening when we add components to the canvas

### Your environment 🌎

Local / latest version

**Comment by prakhargupta1** [comment]
Another [app](https://master--toolpad.mui.com/_toolpad/app/cl1on1bd80041a1pdrrfdt0rq/pages/cl3srtf4200003f6e1j50j390) is throwing similar error message: "Node "undefined" not found". Not sure if they are related, but I was unable to make it work.

**Comment by Janpot** [comment]
@prakhargupta1 That is different. Can you open a ticket?
