### ISSUE TITLE
Support overriding DataGrid column headers

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1230]
### Summary 💡

I'd like to give a custom name to a column separate from the underlying data field. It should be possible to add a header name in the DataGris column editor

**Comment by prakhargupta1** [comment]
Same as https://github.com/mui/mui-toolpad/issues/649 ?

**Comment by Janpot** [comment]
duplicate of https://github.com/mui/mui-toolpad/issues/649
