### ISSUE TITLE
Connections drop-down changes for the demo version

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1273]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

From: https://github.com/mui/mui-toolpad/issues/1213#issuecomment-1292167847

Proposal: https://www.figma.com/file/emgFiUXtGpHNqkUyEltcBR/Studio-wireframes?node-id=401%3A2
CC: @gerdadesign 

These are minimal changes that serve the purpose. We'll keep PostgreSQL and Google Sheets disabled.

**Comment by gerdadesign** [comment]
Thanks for talking about this one during our check in! 

Just adjusting the style to disabled and shortening the copy. 

![Image](https://user-images.githubusercontent.com/106991024/200378830-f8824438-1caf-405d-b98c-b261eadbf60a.jpg)

**Comment by prakhargupta1** [comment]
Only further change that I have to suggest is that the dialog box copy should be shortened to: **Create a new connection**
