### ISSUE TITLE
DataGrid height UX issues

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1277]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

DataGrid height

* can go below 0 => type definitions: add `min`, `max` and restrict the number inputs to these.
* doesn't update in component editor when edited through the drag handle

### Current behavior 😯

https://user-images.githubusercontent.com/2109932/199951391-d9cae155-b286-494a-ac51-1e6706553547.mov

### Context

Related https://github.com/mui/mui-toolpad/issues/1614

**Comment by apedroferreira** [comment]
Yeah, also the whole current implementation of vertical resizing is a bit limited and temporary, it should be improved along with the upcoming improvements to the resizing UX.

**Comment by prakhargupta1** [comment]
A user shared this feedback about the height of datagrid:

---


- On data grid again, I see the prop "height" for example, but it doesn't seem to be listed in the docs (https://mui.com/x/api/data-grid/data-grid/)

Is it just a straight html "height" attribute?

---
If yes, should such props be separate?
