### ISSUE TITLE
Provide types for the function runtime

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1324]
### Steps to reproduce 🕹

1. Create a function query
2. observe the type errors:

    ![Screenshot 2022-11-10 at 11 36 40](https://user-images.githubusercontent.com/2109932/201069159-d67dcb27-7b29-4049-97bb-5a7dd48307de.png)

Introduced in https://github.com/mui/mui-toolpad/pull/1180 where we removed the DOM lib by default from the TypeScript editor.
This is a good thing, because  the DOM lib included way more types than the function runtime supports. We'll just have to build a custom .d.ts file for the function runtime that only includes what it supports. for now:
- fetch, (Headers, Response, FormData,...)
- URL
- console
- setTimeout, clearTimeout
- AbortController
- TextEncoder
- streams
- ...?

Any way we can automate this? Can we do something with https://github.com/microsoft/TypeScript-DOM-lib-generator to generate a subset?

**Comment by prakhargupta1** [comment]
Closing as discussed with Jan
