### ISSUE TITLE
Update footer message in the demo

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1370]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In the demo, we are showing a message at the footer https://github.com/mui/mui-toolpad/issues/1254#issuecomment-1305972742

We should update the notification to: **Check out our roadmap <https://github.com/orgs/mui/projects/9> to stay updated and if you wish to talk to the team, here is the link <https://calendly.com/prakhar-mui/toolpad>  to schedule a call.**

Let me know if there is any suggestion to this message.

**Comment by Janpot** [comment]
How about

> Check out our [roadmap](https://github.com/orgs/mui/projects/9) to stay up to date. Or [schedule a call](https://calendly.com/prakhar-mui/toolpad) if you wish to talk to the team.

?

**Comment by apedroferreira** [comment]
Maybe even shorter?
```Check out our [roadmap](https://github.com/orgs/mui/projects/9) to stay up to date. Or [schedule a call](https://calendly.com/prakhar-mui/toolpad) to talk to the team.```

**Comment by bharatkashyap** [comment]
How about:
 
Check out our [roadmap](https://github.com/orgs/mui/projects/9) to stay up to date, or [schedule a call](https://calendly.com/prakhar-mui/toolpad) to talk to the team!

> Maybe even shorter?
> 
> > Check out our [roadmap](https://github.com/orgs/mui/projects/9) to stay up to date. Or [schedule a call](https://calendly.com/prakhar-mui/toolpad) to talk to the team.
