### ISSUE TITLE
Client-side fetch queries are crashing the app

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#1380]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Create a fetch query (e.g.: "fetch | default")
2. Enable "Run in the browser"
3. Press the "Preview button"

### Current behavior 😯

Doing the steps above crashes the app.

### Expected behavior 🤔

Doing the steps above shows the query result without crashing the app.

### Context 🔦

This seems like an important bug that should be fixed before fully launching the demo.

**Comment by Janpot** [comment]
Interesting, we'll need an integration test for this. Seems to not happen when I do:

```diff
--- a/packages/toolpad-app/src/toolpadDataSources/rest/runtime.tsx
+++ b/packages/toolpad-app/src/toolpadDataSources/rest/runtime.tsx
@@ -57,7 +57,7 @@ export async function clientExec(
 
     const result = await execfetch(fetchQuery, params, {
       connection: null,
-      fetchImpl: instrumentedFetch,
+      fetchImpl: window.fetch,
       evalExpression,
     });
```

**Comment by apedroferreira** [comment]
> memory leak in chrome?

Not sure, I noticed that it was making the request but something is crashing afterwards, didn't investigate much further yet.

**Comment by bharatkashyap** [comment]
I can reproduce as well (similar behaviour on Firefox as well)


https://user-images.githubusercontent.com/19550456/203854359-1db446c9-898a-4302-9b3a-f4bb46ed3d61.mov

**Comment by Janpot** [comment]
Fix in https://github.com/mui/mui-toolpad/pull/1383
