### ISSUE TITLE
When creating an app, instead of drop-down show templates as a grid

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1390]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Current UI:
<img width="498" alt="Screenshot 2022-11-29 at 12 49 14 PM" src="https://user-images.githubusercontent.com/92228082/204464519-bfc367c6-dc3c-4895-bb27-e961876fe98a.png">

Making the layout grid-like shall make templates more discoverable. 
Note: In future there will be 4-6 more templates that will come here, we need to keep that in mind while designing.

### Examples 🌈

![Image](https://user-images.githubusercontent.com/92228082/210716936-65805264-87cd-4bb2-ae59-f5347ba34419.png)

### Motivation 🔦

To help users visually differentiate between each template and help them choose the right one for their use-case.

**Comment by gerdadesign** [comment]
I tried two different options here. While the ask was to simply change the layout, there are a few considerations: 
- Add a description (all of these could use better copy, but I tried to be a little more informative than our current content) 
- Is it valuable to include the Connection type? I added it based on Retool & Appsmith including it, but lmk if it doesn't make sense here. 
- Adding categories; this helps people envision the application of the template and could help get buy in from other team members. 
- Some kind of preview: 
  - Ideally, the preview image would be of the app itself. That way the user does not feel disoriented between the preview and the actual template. They can make better decisions about which template works best for their needs. 
  - Right now, our templates are not sophisticated or relevant enough for someone to actually use them. @prakhargupta1  perhaps we should replace these with the examples you've been sending people instead? Or, dedicate some time to create really stellar templates that solve very specific and common use cases? 
  - For now, I am going with an illustrated preview style (similar to what is on our landing page for consistency).


---
NOTE: Trying out a quick Loom walkthrough of these options. Everyone at MUI should have access if you log in through your google account. Please watch that first, then review the presentation link if you would like more time with it, and finally, feedback can be here or in Figma for any specific contextual feedback. 

The feedback I'm looking for on this draft is: 
- which version makes the most sense given our current standing with Direction 13? 
- do the above added sections, categories, description, connection type, and preview choices make sense? 
  - this is more about the hierarchy and not the styling or copy itself 
- how can we get better templates? what's the difference between what would be considered a template vs. example app to show use cases? 

[Version 1 Loom walkthrough](https://www.loom.com/share/df9d51ab6369490382d7894b49003b4b)
[Version 1 Presentation](https://www.figma.com/proto/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=935%3A201593&scaling=min-zoom&page-id=917%3A195789&hide-ui=1) based on our current implementation and templates. 
[Version 1 frame](https://www.figma.com/file/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=935%3A201593&t=P8Qb0lYXPIB41ogF-1) for comments.


[Version 2 Loom walkthrough](https://www.loom.com/share/7559a6e5a24d4b2bb77b5aae254ce5f7)
[Version 2 Presentation](https://www.figma.com/proto/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=935%3A201598&scaling=min-zoom&page-id=917%3A195789&hide-ui=1) with a different Create New menu approach and template gallery with filters. 
[Version 2  frame](https://www.figma.com/file/14OEUnwh4ahMb2empYAEc8/Toolpad-UX?node-id=935%3A201598&t=P8Qb0lYXPIB41ogF-1) for comments.

**Comment by prakhargupta1** [comment]
Great work Gerda! Both of the options look good. I'll discuss the questions in tomorrow's team call and get back here with the detailed feedback.

**Comment by prakhargupta1** [comment]
It isn't applicable since: https://github.com/mui/mui-toolpad/discussions/1748. Closing the issue.
