### ISSUE TITLE
TextField value should reset when defaultValue property changes

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1420]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Use case: I want to update some values of a datagrid through a form. So I expect the values of selected row should prefill in the form. The ideal component inside a form for this function is TextField, but I can't bind a value to it. It seems to only take input.

Default value property also doesn't serve the purpose.

App [link](https://master--toolpad.mui.com/_toolpad/app/cl1on1bd80041a1pdrrfdt0rq/pages/8n63lnb)

**Comment by Janpot** [comment]
Did a little benchmark in other tools on how they handle this. The benchmark was:
* create two inputs
* make the second input default value equal to the first ones value
* type in the first input, then type in the second input, then type in the first one again

* retool, appsmith, openblocks and dynaboard all behave the same. When the default value changes, the input value is reset to the default value.

I'm fine with adopting the same behavior
