### ISSUE TITLE
No easy way to combine pages from 2 different apps 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1431]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to create a 2-page app. And I want to take page-1 from app-A and page-2 from app-B. 

I start to do this:
1. Duplicate app-A
2. Remove all pages other than page-1
But then, I can't get the page-2 from app-B.

As mentioned here https://github.com/mui/mui-toolpad/issues/813#issuecomment-1333802316 if all apps were just single pages, I could have simply made a folder with copies of the pages/apps.

It's low priority for now, we should do this as overall pages revamp

**Comment by Janpot** [comment]
I see several things here:
- Should app consist of multiple pages, or can we simplify them by removing that construct. i.e. 1 app === 1 page
- Copy + Paste of Toolpad objects. components, but also pages. Within an application, and across applictaions
