### ISSUE TITLE
A postgreSQL DB having sample data for example/template apps

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1432]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As discussed in the planning call, a postgreDB having sample order/refund/payment data would be useful to showcase examples.

These example apps will be part of docs.

### Examples 🌈

https://app.appsmith.com/templates/63037101e8e73110ce254d07

**Comment by Janpot** [comment]
@prakhargupta1 Do you have sample data?

**Comment by prakhargupta1** [comment]
No, is there some fake data generator that we can use?

**Comment by prakhargupta1** [comment]
Checked a couple of options and started using E-com DB from: https://uibakery.io/sql-playground
Should we make a copy for this?

**Comment by apedroferreira** [comment]
> Checked a couple of options and started using E-com DB from: https://uibakery.io/sql-playground
Should we make a copy for this?

Looks like it does the job, I guess it should be a fine solution instead of deploying and hosting our own database?

**Comment by prakhargupta1** [comment]
It does the job for now. But we'll have to create our version as we decided not to rely on external data sources.
