### ISSUE TITLE
A custom chart was flowing out of the canvas 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1447]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open: https://master--toolpad.mui.com/_toolpad/app/cl1on1bd80041a1pdrrfdt0rq/pages/y4d3lzj

### Current behavior 😯

<img width="1433" alt="Screenshot 2022-12-13 at 5 56 28 PM" src="https://user-images.githubusercontent.com/92228082/207321902-04b8eaec-5ca3-499d-8409-c0a5e81eaebd.png">

### Expected behavior 🤔

Chart should remain inside the component container

**Comment by Janpot** [comment]
Your component is responsible for responsively rendering itself within the available space. There isn't much we can do from the outside if you render it larger than the available space. Here you've set it to render at a fixed width of `900`.

I've updated your component to use the `makeWidthFlexible` function that comes with `react-vis`.
