### ISSUE TITLE
Cmd+S doesn't work in the function query editor

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1452]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open a function query
2. Make changes to the code
3. Press Cmd+S

### Current behavior 😯

Nothing happens

### Expected behavior 🤔

The query gets saved

### Context 🔦

It's supposed to work according to https://github.com/mui/mui-toolpad/blob/07e29aa8633701254000e6efe2cd422e9cd66ce6/packages/toolpad-app/src/toolpadDataSources/function/client.tsx#L210
But it seems to collide with the global Cmd+S shortcut

Ran into this while working on the "bundle size viewer" use-case

We could benchmark a few 3rd party libraries

* [`react-hot-keys`](https://www.npmjs.com/package/react-hot-keys)
* [`react-hotkeys`](https://www.npmjs.com/package/react-hotkeys)
* ...

**Comment by bharatkashyap** [comment]
The shortcut also fails in the query editor. +1 to audit a third-party library that could work uniformly across

**Comment by bharatkashyap** [comment]
This works if we move the hook to:
https://github.com/mui/mui-toolpad/blob/master/packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx, but that results in the shortcut not working inside the `BindingEditor`

**Comment by Janpot** [comment]
The hook is a dead end. The solution will likely involve binding key events to focussed dom elements.
