### ISSUE TITLE
A small doubt

### ISSUE THREAD

**Issue by ittat** [mui/mui-toolpad#1460]
Hi, Why are there two similar lines of code here?
https://github.com/mui/mui-toolpad/blob/master/packages/toolpad-app/src/toolpad/AppEditor/index.tsx#L57-L58

**Comment by Janpot** [comment]
That seems to be by accident, good catch 👍

**Comment by apedroferreira** [comment]
I had the fix in this PR already https://github.com/mui/mui-toolpad/pull/1417/files
