### ISSUE TITLE
Polish markdown component

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#1470]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/deploy/cl6rqzry10009arlv9sto6qja/pages/e943n9y

### Current behavior 😯

- There is a margin around the markdown.
- The `<a>` isn't rendered with the `<Link>` of Material UI.

<img width="717" alt="Screenshot 2022-12-19 at 12 16 23" src="https://user-images.githubusercontent.com/3165635/208424186-bd6e528e-d83d-4d57-a0c1-8550bd6d475d.png">

### Expected behavior 🤔

The opposite.

<img width="720" alt="Screenshot 2022-12-19 at 12 16 52" src="https://user-images.githubusercontent.com/3165635/208424263-5083123b-0a73-4de9-b1e2-5f3e4633654e.png">

### Context 🔦

I'm updating some of the Toolpad app we use for the support to use markdown. Related to #1298.

**Comment by oliviertassinari** [comment]
I wonder what we should do with the headers. At minimum they should use the theme typography but not sure about what's the right variants for them.

**Comment by oliviertassinari** [comment]
I noticed something else. In https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/ep03m95, when I click on the link, it breaks the layout.

<img width="640" alt="Screenshot 2022-12-19 at 16 52 34" src="https://user-images.githubusercontent.com/3165635/208478125-80be4087-0e49-4628-9eb1-1ab81a205e4a.png">

We could add `target="_blank"`.

**Comment by Janpot** [comment]
> There is a margin around the markdown.

I think it's the spacing that's between all elements on the page. Perhaps it makes sense to add the title inside of the markdown as well?

**Comment by bharatkashyap** [comment]
> > There is a margin around the markdown.
> 
> I think it's the spacing that's between all elements on the page. 

There definitely is some additional margin that `react-markdown` was adding, `markdown-to-jsx` fixed that

**Comment by oliviertassinari** [comment]
On https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/ip23ggo, it looks much cleaner, great 👍

**Comment by oliviertassinari** [comment]
Things that we could improve: 

- The margin between paragraph feels too small. It's currently at 6px. GitHub uses 16px. Retool has 8px but the text font-size is 12px, not 16px like us. 
- Fix the leading margin bottom: https://github.com/mui/mui-toolpad/pull/1477/files/66acedbede09680e45e593d84504d4c2391e53e5#r1064221934

**Comment by Janpot** [comment]
> Things that we could still improve:

Adjusted those in https://github.com/mui/mui-toolpad/pull/1690

**Comment by bharatkashyap** [comment]
@prakhargupta1 Should we close this since the to-dos listed in the comment above have been closed? 
We can potentially create another issue about separating the Text and the Markdown components back into two different ones
