### ISSUE TITLE
Allow inter-dependent queries

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#1471]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

A lot of the server-side actions are often required to be executed sequentially, for example: refetch elements in a table if an update action is committed. It would be useful to allow a user to configure this relationship at the time of creating queries.

### Examples 🌈

This would require adding an Autocomplete selection on the Query editor to select (possibly multiple) dependent queries, which are triggered on successful completion of the query being created/edited

**Comment by prakhargupta1** [comment]
Is it different from #1184 ?

**Comment by bharatkashyap** [comment]
> Is it different from #1184 ?

Closing as duplicate of #1184
