### ISSUE TITLE
Support lists component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1487]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://mui.com/material-ui/react-list/

As this will have sub-components. We should follow the same approach as we'll do in Cards component.

### Examples 🌈

<img width="676" alt="Screenshot 2022-12-24 at 12 41 59 PM" src="https://user-images.githubusercontent.com/92228082/209425541-edc082d6-2eba-446f-b728-a4c3859f350a.png">

https://marmelab.com/ra-enterprise-demo/#/

Also check DX of retool, appsmith.

**Comment by bytasv** [comment]
@prakhargupta1 so you want to be able to rebuild same design that is shown in example?
- avatar
- main text
- helper text
- numbers

Should each list item be constructed manually or should the list be built from array where I specify only how single list item looks like and the rest is automatically rendered?

**Comment by prakhargupta1** [comment]
Yes, this template should be fine. Instead of Avatar we can also show image. This way no new component need to added. So Image+Typography can be there by default. 

Retool has Image+Rating component as the default sub-components and deleting image from 1 deletes from other entries as well. This experience looks good to me.

It should be like an array where defining one automatically renders others. By default, we can show 3 items.

**Comment by apedroferreira** [comment]
I'll start working on this one if no one's picked it up already - will ask if I have any questions.

**Comment by Janpot** [comment]
There's an interesting component in retool called "List View"

It allows you to set a number of items, and allows you to drag in other components, as a template which is repeated the same number of items.

I wonder if we could improve on it:
- We allow you to template one item
- Instead of setting a number, we allow you to assign an array, with data that can be used in the template

**Comment by apedroferreira** [comment]
> There's an interesting component in retool called "List View"
> 
> It allows you to set a number of items, and allows you to drag in other components, as a template which is repeated the same number of items.
> 
> I wonder if we could improve on it:
> 
> * We allow you to template one item
> * Instead of setting a number, we allow you to assign an array, with data that can be used in the template

I was probably thinking of something like that, just passing in an array of objects with all the same keys, and build the list view from that data.
Also will probably try to make our component consistent with the API for the MUI List component as much as possible.

**Comment by bytasv** [comment]
I agree, I think the user flow should be similar to data grid - where one connects data source and then can somehow (ideally via drag and drop) define "template" which will be rendered
