### ISSUE TITLE
Translated page could not found (shows 404) in mui toolpad

### ISSUE THREAD

**Issue by siva-kannan3** [mui/mui-toolpad#1533]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

- Visit https://mui.com/toolpad/getting-started/overview/ and click the settings menu icon in the top nav.
- Change the language to Portuguese.
- The page redirects to a new link(https://mui.com/pt/toolpad/getting-started/overview/).
- Now, 404 page not be found issue occurs.

### Current behavior 😯

Shows page not be found ( 404 ).

### Expected behavior 🤔

Should show the translated page.

### Your environment 🌎

The issue occurs in documentation.

**Comment by Janpot** [comment]
Thank you for reporting this. The Toolpad docs aren't translated yet. We will disable the language switcher on these pages until they are.

**Comment by oliviertassinari** [comment]
Related to #37607, the sw.js show an outdated page of the docs where you can change language, but it's gone. I think that we can either remove the sw.js logic here or apply the same fix as https://github.com/mui/mui-x/pull/9030 to have our own sw.js

**Comment by Janpot** [comment]
> I think that we can either remove the sw.js logic here or apply the same fix as https://github.com/mui/mui-x/pull/9030 to have our own sw.js in Toolpad.

👍 There is an open PR to align the sw implementation with the other repos https://github.com/mui/mui-toolpad/pull/2190

In the meantime we can consider this issue fixed. Thanks for reporting @siva-kannan3
