### ISSUE TITLE
Add GA events in Toolpad demo

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1535]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

1. Before clicking on create, which template did the user choose or if they clicked on Continue with my last app.
<img width="484" alt="Screenshot 2023-01-09 at 5 01 12 PM" src="https://user-images.githubusercontent.com/92228082/211298698-5a192b6d-267e-4f0e-a251-d4486e959311.png">

2. No. of clicks coming on:

- Self-host button
- roadmap
- schedule demo

**Comment by Janpot** [comment]
Whenever I use this UI, it's not very clear to me. It feels like I have to click create, but a template is forced on me.

I wonder whether we should just show a grid where the options are all equal in effort to pick. e.g. show a grid of options:

- create blank application
- start from template 1
- start from template 2
- continue where you left off last time

**Comment by apedroferreira** [comment]
> Whenever I use this UI, it's not very clear to me. It feels like I have to click create, but a template is forced on me.
> 
> I wonder whether we should just show a grid where the options are all equal in effort to pick. e.g. show a grid of options:
> 
> * create blank application
> * start from template 1
> * start from template 2
> * continue where you left off last time

Yeah, it probably could be better designed... Making everything seem equal in the UI sounds like a good thing to do.
Another alternative could be for all the action buttons to be centered like the template button and stacked vertically, instead of having those actions in the corner.
Not sure if it would be worthwhile to get Gerda's input on this so we can have something that looks ok?

**Comment by prakhargupta1** [comment]
Agree on the thought of creating a grid like UI. There is an existing issue for this: https://github.com/mui/mui-toolpad/issues/1390
