### ISSUE TITLE
Reload of a page editor always switches to the first page

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1551]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open the editor on an app with multiple pages
2. Open any of the pages other than the first page
3. Hit reload

### Current behavior 😯

The url switches to the first page

### Expected behavior 🤔

The url stays on the selected page

### Context 🔦

This line is the culprit https://github.com/mui/mui-toolpad/blob/4f4f4f1e80c943098be66a9417f455006a9ae1dc/packages/toolpad-app/src/toolpad/AppEditor/index.tsx#L58

This will need an integration test

**Comment by apedroferreira** [comment]
Thanks for catching this, I'll look into it!

**Comment by Janpot** [comment]
We should also look if it's still possible to navigate to a Toolpad editor url with query parameters.

**Comment by apedroferreira** [comment]
> We should also look if it's still possible to navigate to a Toolpad editor url with query parameters.

You mean as a new feature? We didn't have any case where it was possible to do that yet, right?
If so I'll create a new issue for it.

**Comment by Janpot** [comment]
I think it was possible for pages, but I may be wrong. I'm pretty sure it didn't use to eliminate them. Not sure if also it did something with them.

**Comment by oliviertassinari** [comment]
It's a regression, I confused me a couple of timed this week.
