### ISSUE TITLE
Component can't be restored from this error

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1563]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open: https://master--toolpad.mui.com/_toolpad/app/clbxozkn30001vg9jj6x4k742/pages/59i3m1g
2. The component on bottom right cannot be returned to a working form. This happened when a related component was deleted. 

<img width="1140" alt="Screenshot 2023-01-16 at 4 56 45 PM" src="https://user-images.githubusercontent.com/92228082/212667985-bca72463-a722-40c8-bc70-21ef074b5750.png">

Is there a way to handle such scenarios better?

### Expected behavior 🤔
I should be able to get to the root cause to fix why the component is not working.

**Comment by prakhargupta1** [comment]
Yes, there were 2 components (text with some bindings for some calculations and a code component) over a paper component. I just moved code component out of the paper component and this happened.

Also, I was unable to Undo this.

**Comment by apedroferreira** [comment]
> Yes, there were 2 components (text with some bindings for some calculations and a code component) over a paper component. I just moved code component out of the paper component and this happened.

I just tried doing something like that with Text and a custom component and there's no issues, so it's probably something more specific... Also investigated the DOM a bit but didn't find anything.  
Without a reproducible, step-by-step example it's hard to figure out what might be wrong. Do you think you can find a way to replicate what happened here?

**Comment by prakhargupta1** [comment]
Sure, let's keep it open for now. I have seen this happening rarely though but whenever it will happen next I'll try to share the video and steps.

**Comment by bytasv** [comment]
IMO ideally in such cases we would capture dom and add it to the gh issue, so that should be easiest way to debug and fix such problems 🤔
