### ISSUE TITLE
From a button component, allow navigating to the current page 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1579]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Problem: I come to a page with some URL query parameters. Now, with the click of a button, I want to basically reload the same page but without the parameters. I can't configure this because, navigating to the same page is not allowed. Explainer screenshot:
<img width="1430" alt="Screenshot 2023-01-18 at 5 54 11 PM" src="https://user-images.githubusercontent.com/92228082/213171345-3748c377-0ac9-4fab-b7b7-df1ddeed19e2.png">

Retool supports this.
<img width="1435" alt="Screenshot 2023-01-18 at 5 58 39 PM" src="https://user-images.githubusercontent.com/92228082/213171535-5fff6129-08c4-4cc6-80a9-5c20f6d896a9.png">

**Comment by bytasv** [comment]
@prakhargupta1 I'm thinking would it be worth to consider extending navigation ui a bit futher and add option to specify page params?
(i.e. with retool)
![CleanShot 2023-01-18 at 14 42 45](https://user-images.githubusercontent.com/437214/213174634-56477d1f-0b53-4d32-b9f5-0765bb9feb01.png)

I feel like just navigating between pages limits a lot what can be done, I assume it should be pretty common to link to specific page with page param, i.e. from the table click on some employee link and open different page with information about that employee 🤔
