### ISSUE TITLE
Disallow binding to properties that can be manipulated in the canvas

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1614]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When using the drag handle to update the height for a datagrid.
If the height property has been bound to, the binding will be removed without notice.
Same for resizing/reordering and the columns prop
Same for image height?

Since this is a potential footgun anyway, let's remove the ability for binding to these specific properties.

**Comment by apedroferreira** [comment]
I think I didn't cover this here: https://github.com/mui/mui-toolpad/pull/1641
Will try to cover it too.

**Comment by apedroferreira** [comment]
Reopened. - it's still possible to bind to some of these properties in the binding editor, I'll exclude them.

**Comment by apedroferreira** [comment]
Finished fixing in https://github.com/mui/mui-toolpad/pull/1696
