### ISSUE TITLE
New Toolpad theming

### ISSUE THREAD

**Issue by gerdadesign** [mui/mui-toolpad#1619]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Now that we've implemented and lived with the default MUI branding theme, we're finding that it feels too large and spacious — more like a landing page versus a builder. The goal is to update our default theming styles to feel more compact and match the expected look and feel of more complex applications (Appsmith, Retool, Figma, Photoshop, etc) 

## Steps 
1. Use our own Material UI Figma file to create a new customized theme with more compact paddings, margins, and border-radii. 
2. Update our existing theme with these new default values

**Comment by apedroferreira** [comment]
Another parameter we could try to adjust to gain space could be font sizes in certain places.
For example, right now our inputs in the properties panel have a 16px font-size, but I see that in other tools they use a much smaller font. I guess that 14px or 12px could still work well there.

**Comment by Janpot** [comment]
I think the starting point of Toolpad theming should be the MUI theme: https://mui.com/material-ui/customization/default-theme/#explore

I believe we should look into:
- supporting "bring your own theme", a code file that creates a theme object (or a supplies a theme configuration object). importable in toolpad as the theme
- supporting a visual editor for each of the properties in the MUI theme
- figure out how the interaction between these two should work
