### ISSUE TITLE
Make fetch available as a global in server side code

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1655]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

fetch is not available as a global in serverside code. Let’s use this kind of [polyfill](https://github.com/vercel/next.js/blob/46e7658f7e5956af055cf9335049681b116d40d2/packages/next/server/node-polyfill-fetch.js)?

**Comment by Janpot** [comment]
Added in https://github.com/mui/mui-toolpad/pull/1651
