### ISSUE TITLE
Toolpad should have the fetch editor

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1656]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Keep visual editors (like fetch editor) in Toolpad-13. It will help in scenarios like: Creating a Google sheets based app, adding query params to the API. 

There will be 2 types of queries:
1) UI driven (fetch editor)
2) pro-code

Config of queries created from fetch editor will be written down to yaml.
Having a code generated for queries created from UI won't be good as 2 way sync won't be robust. 

Originally raised in: https://github.com/mui/mui-toolpad/issues/1650

**Comment by Janpot** [comment]
Added it back in

https://user-images.githubusercontent.com/2109932/219883117-a6128f7e-b3a3-4e01-803e-c5a8d5642a36.mov
