### ISSUE TITLE
Remove connections (functions data source included)

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1657]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Like in pro-code, connections will be with environment variables so it will be removed from the UI.
Functions data source is also going to get irrelevant as the same purpose could be achieved from scratch.

**Comment by apedroferreira** [comment]
> If I can understand correctly, this has already been removed from Direction 13:
It might also be about removing the code related to connections that we don't use anymore?
