### ISSUE TITLE
Handle .env file changes better

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1659]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Update env variables for serverside code when the .env file changes. Right now the user needs to restart Toolpad.

**Comment by Janpot** [comment]
Serverside functions are run in a child process. It's enough to restart the child process with new env variables. No need to restart the whole app.

**Comment by Janpot** [comment]
Did this today
