### ISSUE TITLE
Reference @types/node in user project

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1662]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently in `queries.js` references to `process.env...` give type errors. We could think about a similar solution to the `next-env.d.ts` file?, but for toolpad

**Comment by apedroferreira** [comment]
This seems to be working for me, I'm getting types from `node_modules/@types/node`. Did anything change?

**Comment by Janpot** [comment]
> Did anything change?

Looking into this, I think it gets installed transitively from dependencies of `toolpad-app`. I wrote this ticket when I was still messing around with a local setup that was based on `yarn link` and that didn't deal correctly with dependencies. For now we may be able to close this without further action.
