### ISSUE TITLE
Create a npm publishing flow

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1664]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

To be added

**Comment by apedroferreira** [comment]
Some maybe useful (or not) libraries related to this:
- https://github.com/changesets/changesets/tree/main
- https://github.com/microsoft/beachball

**Comment by Janpot** [comment]
I'm inclined to reuse parts of the current process if we can, at least initially. But happy to introduce new tools if they have significant advantages. Currently we use the in-house changelog generator, and the command I've so far been using to version/publish is based on `lerna`.

The main pain points I had in mind with this ticket were:

- Making the publishing process more failsafe, e.g. how can we avoid packages getting published without a production build having run. Is there a way where we can even introduce a smoke test before publishing to make sure that whatever will be uploaded will work correctly? (e.g. `.npmignore` not excluding crucial files)
- How much can/should we automate? Do we build on top of the CLI that uses prompts to guide you through the publishing process?
- Introduce a canary mode which will publish canary versions of the packages.
- Describing the process in more detail in RELEASE.md.

Not all of these have the same priority, e.g. the smoke test I mention could have high cost to develop.
