### ISSUE TITLE
Reach consensus on routing

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1668]
### Summary 💡

Decide about the structure of Toolpad URLs

To Do:

- [x] Remove `__LOCAL_MODE_APP_` from editor url. This exists currently to maintain a compatibility mode with legacy Toolpad, but we're removing this mode as part of the clean break with the legacy fork
- [ ] Currently the app lives under `/prod/...` for the same reasons. But perhaps it makes sense to move top-level?
- [x] Anything else?

**Comment by Janpot** [comment]
I think we can close this
