### ISSUE TITLE
Open editor improvements

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1689]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

* feedback when the editor fails to open for some reason
* Deal with `$EDITOR` not set and `code` not being installed on the `$PATH`. Guide towards installing vscode, and link to https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

We can benchmark and take inspiration from:

* `launchEditor` in [react-dev-utils](https://www.npmjs.com/package/react-dev-utils) seems to handle cases like this better
* playwright allows opening vscode in its ui mode

  ![Image](https://user-images.githubusercontent.com/2109932/229532493-bb4fc0cc-5463-4251-94fa-0c95fc69d9cd.png)

* next.js redbox callstack items link to code editor
   ![Image](https://user-images.githubusercontent.com/2109932/229531717-b9ca9b7c-66e1-40c4-996e-9d5c964c95e6.png)

* Add documentation + link to it when opening a code editor

**Comment by prakhargupta1** [comment]
In v0.1.12, I am getting this:

![Image](https://github.com/mui/mui-toolpad/assets/92228082/6c8e23eb-3212-4f18-b6a5-ccc839e93731)
