### ISSUE TITLE
Add templates to the Create Toolpad App CLI

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1715]
There can be 2 types of users:
1. Who didn't check the examples
2. Who checked the examples

For 1. we can show a CLI option when they write `yarn create toolpad-app` command. We can ask, Do you want to start with an example? If they say Yes, we can show a list.
We could not ask this question and instead on the first run, show them that there is an examples page that they can explore, and if they like any example they can reinitiate another project.

For 2. We should have the commands on the examples page for them to start directly.

**Comment by Janpot** [comment]
We could add an `--example` argument that loads an existing example similar to how Next.js does it https://github.com/vercel/next.js/tree/canary/examples/amp-first#how-to-use

**Comment by prakhargupta1** [comment]
Done in https://github.com/mui/mui-toolpad/pull/2885
