### ISSUE TITLE
Make Toolpad direction updates public

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1719]
### Summary 💡

To all of our existing users we need to inform that in the future they'll be able to use Toolpad as a package from npm and there will not be any more updates to the alpha docker image. This information needs to be shown in:

- [x] Documentation: Change Toolpad documentation to make it at least in sync with master branch after direction13 branch. https://github.com/mui/mui-toolpad/issues/1671 @Janpot 
- [x] Single source of truth, post that explains the changes to Toolpad: @Janpot 
    - In the roadmap? _no_
    - Separate documentation page? => _no_
    - Blog post? _no, we didn't have an announcement post_
    - Github discussion? _yes! https://github.com/mui/mui-toolpad/discussions/1748_
- [x] people using the legacy Toolpad application @Janpot  https://github.com/mui/mui-toolpad-0-0/pull/5
    - [x] Disable update banner, like the demo
    - [x] Banner or badge? Badge is too discrete. Banner would display the same way as on the demo app. Bottom + only on the editor. Non-dismissable. message and a link to the announcement
- [x] people landing on the README @Janpot https://github.com/mui/mui-toolpad/pull/1651/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
    - [x] update setup instruction
    - [x] replace demo with  message and a link to the announcement
- [x] people landing on the docs: Replace demo callout and link from https://mui.com/toolpad/getting-started/overview/ ?
- [x] people landing on the demo: Replace banner with same as above @Janpot  https://github.com/mui/mui-toolpad-0-0/pull/5
- [x] people landing on the landing page: Rethink content (@prakhargupta1 https://github.com/mui/mui-toolpad/issues/1670) @Janpot Folding into https://github.com/mui/mui-toolpad/issues/1671
- [ ] Add message in docker hub https://hub.docker.com/r/muicom/toolpad (investigate) Add link to discussion, npm package

- [x] Remove the announcement after fully phasing out legacy Toolpad

- [x] Next Github release: elaborate on the upcoming changes, link to the github discussion as well.

Suggestion:
We replace this with the message. 
<img width="1437" alt="Screenshot 2023-03-01 at 4 40 07 PM" src="https://user-images.githubusercontent.com/92228082/222122980-b9e42cd1-ee22-4729-8c17-f1f4436a1b95.png">

Message suggestion:
> A [big change](https://github.com/mui/mui-toolpad/discussions/1748) is coming: we're making Toolpad focus much more on integrating with your IDE, while providing the ease of building UI fast with a drag and drop.

**Comment by bharatkashyap** [comment]
> Message suggestion:
> Note: Big changes are coming - we're excited to announce a new direction for our product to better serve your needs. Stay tuned for further updates!

Suggestion: 

A big change to Toolpad is coming: we're making Toolpad focus much more on integrating with your IDEs, while providing the ease of building a drag and drop UI fast. Read more here.

The link in the banner could be a blog post, a Tweet thread, or even the landing page/documentation with updated content.

**Comment by Janpot** [comment]
Alternatively we could opt for a less intrusive approach to a banner:



https://user-images.githubusercontent.com/2109932/224719318-65c7d7cc-7ca3-4ee2-b27a-f447794a7c05.mov

**Comment by Janpot** [comment]
@mui/toolpad I've opened https://github.com/mui/mui-toolpad/discussions/1748
To separate discussions around the change from discussions around the messaging itself I propose while reviewing it you either directly update the content, or leave comments in this issue (#1719)

**Comment by prakhargupta1** [comment]
Reopening this as the demo doesn't show the banner. Though only single digit no. of apps are being built on the demo.
CC; @apedroferreira

**Comment by Janpot** [comment]
It's done
