### ISSUE TITLE
Pages delete automatically

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1724]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Create an app with 2-3 pages and abruptly the page will be deleted.

### Current behavior 😯

I am working on an app but somehow the pages keep getting deleted automatically. It has happened 5-6 time today. 
After this toolpad.yaml also gets erased.

<img width="649" alt="Screenshot 2023-03-02 at 6 21 53 PM" src="https://user-images.githubusercontent.com/92228082/222434910-c7279b19-3c2b-4123-b6bd-1fa411d89664.png">
<img width="850" alt="Screenshot 2023-03-02 at 6 11 43 PM" src="https://user-images.githubusercontent.com/92228082/222434914-a59ebfd3-30d2-4ac7-bed8-554147cefea0.png">

**Comment by Janpot** [comment]
Are you by any chance renaming the file extension to `.yaml`?

I have a potential fix in https://github.com/mui/mui-toolpad/pull/1725

**Comment by prakhargupta1** [comment]
> Are you by any chance renaming the file extension to .yaml?
No no. Sorry I meant, toolpad.yml

> Do you see any errors in the output of running yarn dev? So that is the output in the terminal, preferrably pasted as text, not a screenshot.
Nope, nothing reflects on the terminal when the page gets deleted.

**Comment by prakhargupta1** [comment]
This seems to have been fixed. Hasn't happened so far.

**Comment by Janpot** [comment]
Ok great 👍 Closing then. Feel free to reopen if it happens again
