### ISSUE TITLE
Support CLI --help command

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1744]
### Summary 💡

```
npx @mui/toolpad --help
```
Should print helpful message outlining all possible commands.

```
npx @mui/toolpad dev --help
npx @mui/toolpad build --help
npx @mui/toolpad start --help
```
Should each print a helpful message of the sub command

* Let's move to `yargs` to automate this somewhat?
* Let's add a `npx @mui/toolpad help` command as well as an alias for `npx @mui/toolpad --help`?

**Comment by apedroferreira** [comment]
Not sure what solution we're using right now for command line arguments, but having something help us with the `help` command instead of doing it all manually definitely sounds worth it, especially as we add more options. I'm familiar with `yargs` so I think we could use it.
