### ISSUE TITLE
Moving app to a different folder in the file manager resets app

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1769]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Move an app from folder A to folder B
2. queries.ts will reset to the original template also any custom component will be removed

Tried it with 2 apps.

### Expected behavior 🤔

All files should be copied seamlessly.

### Your environment 🌎

MacbookAir M1

**Comment by Janpot** [comment]
@prakhargupta1 Can you elaborate a bit more the steps to reproduce this problem? What do you mean exactly by "Move an app from folder A to folder B"? Do you stop `toolpad dev`, copy the files, start `toolpad dev` in the new folder? Be as detailed as possible.

**Comment by prakhargupta1** [comment]
I tried doing it again today. First I copied and pasted, then moved (cut-paste) the app. It works fine. The app came with all the files and was not broken. I did it when `toolpad dev` was not running. Yesterday, I may have moved it with the running app and hence the files were came broken. 
Closing this issue.
