### ISSUE TITLE
Docs: Add example page for Customers Admin app

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1774]
[Link](https://www.notion.so/mui-org/Customers-domain-UI-88e17647312e463ab38e655198b18195) to further details.

We'll put the working app in https://github.com/mui/mui-private repo and a showcase version in: https://github.com/mui/mui-public

**Comment by prakhargupta1** [comment]
Rate limitation on the Xano API that is being used:
<img width="575" alt="Screenshot 2023-04-25 at 3 45 51 PM" src="https://user-images.githubusercontent.com/92228082/234247247-cff49ea0-d05a-4598-9ec9-a48699201362.png">

**Comment by Janpot** [comment]
@prakhargupta1 It's possible to "fake" a backend in-memory. For example:

```tsx
import { createQuery } from "@mui/toolpad/server";

const customers = [{ name: "John Doe" }];

export async function getCustomers() {
  return customers;
}

export const addCustomer = createQuery(
  async ({ parameters }) => {
    customers.push({ name: parameters.name });
  },
  {
    parameters: {
      name: {
        typeDef: { type: "string" },
      },
    },
  }
);
```

We may also be able to leverage [`@faker-js/faker`](https://www.npmjs.com/package/@faker-js/faker) to generate data for demonstration purposes.

**Comment by prakhargupta1** [comment]
Thanks, just did this and removed dependence on Xano APIs.
