### ISSUE TITLE
For an authenticated REST API, allowed editing from the fetch editor

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1785]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I have a REST API that I want to use in Toolpad. Since it requires authentication I am bound to do it using code queries. It would be great if I could just add my secrets and API pro-code way and expose it as a connection in the fetch editor (like earlier).  Then I can just add my endpoint, params etc. and build faster. 

Snapshot of how it looks currently in master--toolpad
<img width="1401" alt="Screenshot 2023-03-22 at 10 28 26 PM" src="https://user-images.githubusercontent.com/92228082/227047426-7c9becaf-f22c-49b4-b8a3-a1b9926009ea.png">

We could allow just binding to `process.env.MY_VAR` in the binding editors for serverside code:

![Image](https://user-images.githubusercontent.com/2109932/229537106-6aaa406a-91b7-4a60-b69b-d5b281bc2fec.png)

**Comment by Janpot** [comment]
Alternatively, allow binding to environment variables directly
