### ISSUE TITLE
Add params option for page navigation with button onClick event

### ISSUE THREAD

**Issue by RBerthier** [mui/mui-toolpad#1800]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It seems not possible to add params option, when using page navigation when customising onClick event handler for button.

### Examples 🌈

![image](https://user-images.githubusercontent.com/891711/227718351-75f3b720-7744-4c56-a39c-159ca820e5aa.png)

After selecting a page to navigate to when clicking on a button, I would expect to have the possibility to add n* params to the page navigation. I didn't find any to way to do so.

### Motivation 🔦

I want to navigate from one page to another using params to specify some content.

For instance, I tried the Toolpad tutorial with the dog listing, and I created another page to display more details on a specific dog. For this second page I need to use a param in the page url to specify the dog I want to display information about. To navigate to the second page, I add a button on the first page, but I can't add the needed parameter.

**Comment by Janpot** [comment]
Yes 👍, makes sense. It looks like it originally was intended to be part of https://github.com/mui/mui-toolpad/issues/76 but never got implemented. We'll use this issue to keep track of it.
