### ISSUE TITLE
Button click binding is not working 

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#1801]
![image](https://user-images.githubusercontent.com/128947562/227752219-796ea857-190d-4e27-866c-522a20d3a2b7.png)

I am trying to make this happen on button click but it is not working please help with this and give me a suggestion if some corrections are needed @Janpot 

Thank you in advance

**Comment by Janpot** [comment]
Setting state in these handlers is currently unsupported. We've [talked](https://github.com/mui/mui-toolpad/issues/1569) about this before. I've played around with this over the weekend and came up with basic support for this in https://github.com/mui/mui-toolpad/pull/1807.

**Comment by Prajapati-developer** [comment]
![image](https://user-images.githubusercontent.com/128947562/228194177-bd599b95-4b06-451d-a116-8b9d3bb28727.png)
using this browser and I have tried your solution it is not working.

**Comment by Janpot** [comment]
@Prajapati-developer Thanks for coming back to me. The change wasn't published yet. I just pulbished version `0.1.1` which contains the update. Would you mind trying again?

> using this browser

Which operating system are you using?

**Comment by Prajapati-developer** [comment]
thanks, @Janpot for the quick reply I have tried the new version working as expected. and i'am using **Windows 10 Pro** OS .
and do we have some information that in the new version what's new feature has been included?
