### ISSUE TITLE
Revamp binding editor 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1810]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [ ] When I open my binding editor I sometimes forget which component am I editing, it would help if we show component name here in the title:

<img width="1209" alt="Screenshot 2023-03-27 at 12 32 23 PM" src="https://user-images.githubusercontent.com/92228082/227921201-02f0dc24-32d0-4a01-b942-1b6c81d2c863.png">

- [x] The highlighted blue-box instead of component type, should also have the component name. `Text1` in this case:

<img width="1139" alt="Screenshot 2023-03-27 at 12 51 53 PM" src="https://user-images.githubusercontent.com/92228082/227921949-8cf7d65b-9c67-4c4b-b16c-ac13ed779d3d.png">

**Comment by Janpot** [comment]
For 2. shall we replace the component type with the component name? Can you benchmark what other tools do here?

**Comment by prakhargupta1** [comment]
> For 2. shall we replace the component type with the component name? Can you benchmark what other tools do here?

Checked appsmith, retool and superblocks and they all show the component name.

**Comment by Janpot** [comment]
For 1. there are some considerations

- What about binding editors that are not on page elements? e.g. in the query editor
- Suppose we make this editor less dialog-like and tie it closer to the property control visually, like we did with the datagrid columns editor. Would that add enough context to solve this problem?

For 2. I'm opening https://github.com/mui/mui-toolpad/pull/1818

**Comment by prakhargupta1** [comment]
I think 2 would be the best approach as it leads to a more integrated and contextual UX. Let's try to solve it that way, I am adding `design:UX` label for further exploration.

**Comment by prakhargupta1** [comment]
Marking it closed as we have started showing 'property name'. It gives the needed context.

<img width="586" alt="Screenshot 2024-03-12 at 2 51 41 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/5089cd21-9f56-4afd-8dc4-34f7da97b1b8">
