### ISSUE TITLE
Should TextField component be renamed to TextInput?

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1811]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I get a bit confused between `Text field` and `Text` component. 
Replacing `Text field` by `Text input` should remove the confusion.

**Comment by Janpot** [comment]
We've followed the naming from the `@mui/material`. Do you think it would be less confusing for developers that are familiar with MUI already?

**Comment by prakhargupta1** [comment]
Ah ok! Let's stick to the MUI convention then though keeping this issue open for a while for visibility.
