### ISSUE TITLE
On landing page, highlight that Toolpad is a pro-code tool now.

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1812]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

With Toolpad becoming pro-code now, we should highlight this new information through a visual in the hero section.

May be something like this can help:

<img width="579" alt="Screenshot 2023-03-27 at 1 52 15 PM" src="https://user-images.githubusercontent.com/92228082/227933895-dc796c3f-a57c-4d84-80fc-0e0e1d061e8b.png">

(It is just an example for discussion, we can use better images)

More changes:
- [x] Show `npx create toolpad app` in the hero section, next to Get Started CTA.
- [x] Put email form out of hero section.
- [x] From use cases section, link docs section that shows showcase (3-5). Feature examples is something that we are keeping here: https://github.com/mui/mui-toolpad/tree/master/examples
Design we can implement: https://www.figma.com/file/4uv2dT18rXJPZBbrbpw61q?node-id=6826:597770#431401706
Being worked on here: https://github.com/mui/mui-toolpad/pull/1445
- [x] gif update @prakhargupta1 
- [x] change Alpha -> Beta https://github.com/mui/material-ui/pull/37288 https://github.com/mui/mui-toolpad/pull/2024
- [x] update email collection form (Sendinblue has rebranded to Brevo, for us everything remains same. The current list is # 30 and consists of users interested in Beta. I have created a new list # 56, which will be for users who are interested in Toolpad future updates/newsletters. When we move to Beta, let's also change this list and the content around this form) [Link to the list](https://my.brevo.com/lists/settings/id/56)
- [x] Edit copy of email form: https://www.figma.com/file/4uv2dT18rXJPZBbrbpw61q?node-id=6829:593596#431719838

### Examples 🌈
https://interval.com/
https://www.airplane.dev/
https://trigger.dev/

**Comment by gerdadesign** [comment]
### Design Draft 1
- Please review the design draft — loom for contextual walkthrough; figma for specifics 
- @prakhargupta1 I had already done some exploration around the use cases by the time you updated your comment in #1445, so it's still included in here. 
- In figma, I added two types of sticky notes throughout: 
  - **yellow** = notes from me about the design 
  - **red** = content needed from others. @Janpot  I'm hoping you will be able to shed some light on the lingering questions around what are the most relevant examples/code snippets to show in the mockup. 

[Loom walkthrough](https://www.loom.com/share/64d2fbca88694a3a9d457bb4138f652b)
[Figma](https://www.figma.com/file/4uv2dT18rXJPZBbrbpw61q/Marketing-site?node-id=6826%3A595569&t=0opgu2XPX8ZSGd60-1)
