### ISSUE TITLE
Nomenclature suggestions 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1830]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Based on yesterday's discussion, I am creating this issue to discuss nomenclature of Toolpad queries, APIs.

Current name | Options |
-- | -- |
serverside javascript | 1. Functions 2. Handlers
serverside HTTP request | 1. HTTP client 2. API request

**Comment by Janpot** [comment]
For me personally, the following makes most sense:

* `queries.ts` => `functions.ts`
* `createQuery` => `createFunction`
* Create query options:
  * "serverside javascript" => "serverside typescript function"
  * "serverside HTTP request" => stays "serverside HTTP request"

**Comment by apedroferreira** [comment]
queries.ts => functions.ts
createQuery => createFunction
Create query options:
"serverside javascript" => "Custom function"
"serverside HTTP request" => stays "HTTP request"

**Comment by apedroferreira** [comment]
Reopening just until the arcade is updated, then we can close this.

**Comment by prakhargupta1** [comment]
Arcade updated. Looks like due to some update on their side, old and new arcades have some difference in the dimensions. This led to some images getting cropped. Will try to fix it later.
