### ISSUE TITLE
Safari 16.3 not working :/

### ISSUE THREAD

**Issue by joshelboy** [mui/mui-toolpad#1836]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.    
```bash
npx create-toolpad-app
```
2.    Now follow the init process
3.
```bash
cd <my-toolpad-project> && npm run dev
```
4.    Try to call localhost:300x/preview/pages/.... in

-    Safari 16.3 (working) ✅
-    Firefox 111.01 (working) ✅

5.    Try to Drag & Drop ANY component into the "Drop components here"-Field

-> Safari crashes

This isn't critical, I just wanted to let you guys know.

### Current behavior 😯

Safari crashing and not adding any component

### Expected behavior 🤔

Safari not crashing and adding e.g Button to the component-field.

### Your environment 🌎

-    latest MUI via npx
-    M1 Mac - Ventura 13.6
-    Safari 16.3

**Comment by Janpot** [comment]
Thanks for reporting. We're currently only testing on chrome and firefox.

**Comment by Janpot** [comment]
Seems to be working for me on Safari 16.4

**Comment by joshelboy** [comment]
I will try again. I am in MacOS Beta, so this might have caused this.

**Comment by joshelboy** [comment]
Yep, it's all stable now!
It could potentially be related to the missing glob dependency yesterday, but I am not 100% sure.
I should close this, right?

**Comment by Janpot** [comment]
I believe we can close this for now yes. Thank you.
