### ISSUE TITLE
Transforming query results in error

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-toolpad#1855]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I've been following https://mui.com/toolpad/getting-started/quickstart/ and noticed that query transformation doesn't work

Steps:

1. Add a query and try to transform it as shown in the screenshot:

<img width="1179" alt="Screenshot 2023-04-04 at 17 21 16" src="https://user-images.githubusercontent.com/13808724/229840132-40cedb2b-b0ae-41c1-88bf-25823deb3864.png">

### Current behavior 😯

Error in the query preview

### Expected behavior 🤔

No errors in the query preview

### Context 🔦

I looked into it quickly and the error seems to be coming from

https://github.com/mui/mui-toolpad/blob/217a17e7dc6f581210a175422cf86839a627fa21/packages/toolpad-app/src/toolpadDataSources/applyTransform.ts#L10

Given the transform function `(data) => { return data.message }`, the evaluated code looks like:
```js
(data) => { return data.message }(/** data **/)
```
Shouldn't the transform function be wrapped in parenthesis?
```diff
-`${transformFn}(${JSON.stringify(data)})`,
+`(${transformFn})(${JSON.stringify(data)})`,
```

This seems to fix the issue. I can submit a PR

**Comment by cherniavskii** [comment]
> We'll deal with

Sure, thanks!

**Comment by bharatkashyap** [comment]
> > We'll deal with
> 
> Sure, thanks!

Thanks for the catch, Andrew 👍
