### ISSUE TITLE
Transform in UI queries throws parenthesis error

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1870]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Try transforming any response in master--toolpad and in the localhost mode. Snapshots below for the exact scenario:

App that I was working on: [https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/ep03m95]( https://master--toolpad.mui.com/_toolpad/app/cl6rqzry10009arlv9sto6qja/pages/ep03m95)

### Current behavior 😯

<img width="1436" alt="Screenshot 2023-04-11 at 2 29 11 PM" src="https://user-images.githubusercontent.com/92228082/231111178-a78ef221-e143-4160-87b9-96c7601b74e9.png">

### Expected behavior 🤔

![Screenshot 2023-04-11 at 2 29 01 PM](https://user-images.githubusercontent.com/92228082/231111228-f723b38e-3224-4385-ad7e-fbe4a2cdf6a8.png)

**Comment by bharatkashyap** [comment]
This is a duplicate of https://github.com/mui/mui-toolpad/issues/1855 and is fixed in the latest version by https://github.com/mui/mui-toolpad/pull/1856. Could you try updating the version and re-run?

**Comment by prakhargupta1** [comment]
Closing this issue as this has been fixed.
