### ISSUE TITLE
Renaming query should update the bindings depending on it

### ISSUE THREAD

**Issue by mnajdova** [mui/mui-toolpad#1887]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When renaming a query, it would be great if the bindings can be automatically updated. 

### Examples 🌈

For e.g. updating the name of a query, which data is used in a data grid, ideally shouldn't break everything, especially if the data from the query is used in multiple places.

### Motivation 🔦

This feature would help a lot when refactoring.

**Comment by Janpot** [comment]
Possible duplicate of https://github.com/mui/mui-toolpad/issues/94 ?

**Comment by mnajdova** [comment]
Yep, closing.
