### ISSUE TITLE
Observations when I used npx create-toolpad-app my-app command

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1890]
1. I thought my-app is going to be the name of the folder. But the CLI asks me to Give a project name that becomes the name of the folder. So, where is my-app used?

<img width="542" alt="Screenshot 2023-04-14 at 2 16 10 PM" src="https://user-images.githubusercontent.com/92228082/231993226-e5d49f14-93c0-45d2-a9f3-de48ed397697.png">
It's the same name here (tools) but in another setup, I used different names.

2. I had another app running on port 3000. And this process couldn't pick a new port. Earlier it was working fine, so may be a regression?

<img width="408" alt="Screenshot 2023-04-14 at 2 18 58 PM" src="https://user-images.githubusercontent.com/92228082/231993957-4e3dfa14-c6d4-4ee6-afbb-637a13f48e8f.png">

3. App started with the yellow alert box saying 'Non-existent page undefined'. 

I guess all of these will be fixed under: https://github.com/mui/mui-toolpad/pull/1795
but I thought of adding them here, just to be tracked.

**Comment by Janpot** [comment]
I believe it should work as follows:

- User provides a path `yarn create toolpad-app path/to/my/app`: toolpad doesn't prompt for a project name, app is created under the provided path. Note that it should be possible to specify `.` to use the current folder. If the path points to a non-empty folder, the CLI shows an error and exits
- User doesn't provide a path `yarn create toolpad-app`: toolpad prompts for a project name

**Comment by bharatkashyap** [comment]
> 1. I thought my-app is going to be the name of the folder. But the CLI asks me to Give a project name that becomes the name of the folder. So, where is my-app used?
> 
> <img alt="Screenshot 2023-04-14 at 2 16 10 PM" width="542" src="https://user-images.githubusercontent.com/92228082/231993226-e5d49f14-93c0-45d2-a9f3-de48ed397697.png">
> 
This will indeed by solved by #1795 

> 2. I had another app running on port 3000. And this process couldn't pick a new port. Earlier it was working fine, so may be a regression?
> 
> <img alt="Screenshot 2023-04-14 at 2 18 58 PM" width="408" src="https://user-images.githubusercontent.com/92228082/231993957-4e3dfa14-c6d4-4ee6-afbb-637a13f48e8f.png">
> 

This is indeed an unintended consequence of https://github.com/mui/mui-toolpad/pull/1882; the logic in the existing CLI was to abort if an explicitly specified port was found to be unavailable; the PR above adds a  `DEFAULT_PORT` variable which results in the port being treated as having always been explicitly specified. I'll create a fix for this.

> App started with the yellow alert box saying 'Non-existent page undefined'.

This I can't replicate with the current version of the CLI, but regardless of that we do need to create an integration test for the CLI which I can work on - I'll create a separate issue for that

**Comment by bharatkashyap** [comment]
Okay to close this in favour of the individual linked issues @prakhargupta1?

**Comment by prakhargupta1** [comment]
Video for 3rd one: 2 issues:
a. It automatically opens a wrong tab somehow
b. Starts with the yellow box saying non-existent page

https://user-images.githubusercontent.com/92228082/232664578-79224932-7d03-4184-9646-9db26adef248.mov
