### ISSUE TITLE
"Resources" folder is not created on startup sometimes

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1914]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Started a fresh project using yarn create toolpad app (later also tried using npx)
2. Somehow, it doesn't come with resources or components folder
3. After yarn dev, when I click on server side javascript query, I get the below error and the app stops

### Current behavior 😯

<img width="1392" alt="Screenshot 2023-04-20 at 1 11 35 PM" src="https://user-images.githubusercontent.com/92228082/233296763-9fa5408f-21c9-4e95-8691-151b865a7b8c.png">

### Your environment 🌎

Mac
Toolpad version v0.1.6

**Comment by Janpot** [comment]
I can't reproduce

> Started a fresh project using yarn create toolpad app (later also tried using npx)

Can you share the **exact** commands and input that you've used to get to this project.

From your screenshot it looks like you have a pg_admin folder inside of a pg_admin folder. Are you sure you're starting toolpad in the right folder?

**Comment by apedroferreira** [comment]
Just tried and I can't reproduce it either.

**Comment by apedroferreira** [comment]
This is exactly the error we had on Windows... 
But the `create-toolpad-app` you were using yesterday shouldn't have included those fixes yet, right?

**Comment by apedroferreira** [comment]
Ok I also got this after all but nothing crashed:

<img width="891" alt="Screenshot 2023-04-21 at 12 33 26" src="https://user-images.githubusercontent.com/10789765/233625816-036804b3-4c1c-425a-aa74-8f72100fc8b6.png">

I think it's a temporary error when we create a new toolpad app with `create-toolpad-app` and run `yarn dev` and we go to create a custom function. It works but because it didn't create the `resources` folder right away it shows this error in the console when it tries to get the list of available function.

So we should probably fix this just not show the ugly console error.

**Comment by prakhargupta1** [comment]
But since there is no `resources` folder. I can't write a code query.
I'll upgrade to v0.1.7 and retry.

**Comment by apedroferreira** [comment]
> But since there is no `resources` folder. I can't write a code query. I'll upgrade to v0.1.7 and retry.

It ended up creating the `resource` folder for me when I pressed `Open editor`, but it wasn't there in the beginning.
I think the fixes in v0.1.7 are unrelated to the issue should still be there.

**Comment by prakhargupta1** [comment]
Upgraded to v0.1.7 and this issue is gone!

**Comment by prakhargupta1** [comment]
This again happened today when I created a fresh app using yarn create toolpad-app. Somehow resources folder isn't created sometimes.

<img width="1391" alt="Screenshot 2023-05-02 at 2 16 33 PM" src="https://user-images.githubusercontent.com/92228082/235621273-e798935b-7816-42c2-9ea7-f076e8872984.png">

**Comment by prakhargupta1** [comment]
This is still happening in v0.1.11. Components folder is also not being created.

**Comment by Janpot** [comment]
So far that has been deliberate. The idea was that the project folders comes as thin as possible and these folders get created on demand as the first function is added or the first component is added. Do you think we should always create these folders/files when the project starts up, even when users don't need them?

**Comment by prakhargupta1** [comment]
Ok, just validated this. After learning how Toolpad works, there would be times when a user would start from a function or code component, so creating them by default sounds reasonable to me.
Having these folders not created makes me question if there was some issue in the installation process.

**Comment by prakhargupta1** [comment]
On my machine when I create a fresh toolpad app, following issues are being observed:
1. Custom component creation works fine. A folder gets created, but the Open button doesn't work. It says No code editor found. Also reported [here](https://github.com/mui/mui-toolpad/issues/1689#issuecomment-1559107296)
2. When creating a custom function, I see no function to pick from and as there is no folder in resources. Not sure what is the trigger for folder creation in this case.

https://github.com/mui/mui-toolpad/assets/92228082/74f6fac4-2205-46ea-880f-15af3be33967
