### ISSUE TITLE
Data grid issue 

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#1922]
![image](https://user-images.githubusercontent.com/128947562/233577427-88883cd6-1829-4d39-be06-7b8ba86f73a7.png)
as you can see I have reused the id field for the action field then it is modifying the id field whenever I am modifying the action field.

**Comment by bharatkashyap** [comment]
@Prajapati-developer I'm not sure what exactly is happening. Could you share either a video, or the zipped up app so I can try and reproduce the situation?
