### ISSUE TITLE
Previewing app is broken in an instance

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1983]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I want to show the preview step in the landing page video but it shows an error when I click on preview button. 

### Current behavior 😯

https://user-images.githubusercontent.com/92228082/236999212-4263ca6a-6d99-410f-8d7b-298f6a2fea6a.mov

### Context 🔦

I have upgraded to v0.1.10, but the error still comes.
The error doesn't come for other projects that have same config.

### Your environment 🌎

v0.1.9

**Comment by Janpot** [comment]
Try running `rm yarn.lock && yarn` and see if that changes anything, but before you do that, can you share your project folder? including `yarn.lock`?

**Comment by prakhargupta1** [comment]
Ran `rm yarn.lock && yarn` and chose v0.1.10, still facing the issue.
