### ISSUE TITLE
Renaming a page doesn't delete old page

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

1. Update name of any page
2. Then see if the changes remain preserved after you restart the app.

Also, in the preview the new name doesn't show.

### Current behavior 😯

https://user-images.githubusercontent.com/92228082/237060570-34f55fb0-7ac5-4597-8e3c-07cf22632d86.mov

### Your environment 🌎

Latest (v0.1.10)

**Comment by bharatkashyap** [comment]
I can't seem to be able to replicate this

https://github.com/mui/mui-toolpad/assets/19550456/c3e57749-6777-49b1-9e3b-5da28deb9701

**Comment by prakhargupta1** [comment]
I just restarted my system and started fresh. On first rename, it works fine (just that another page is created in the project, is that expected?)
On 2nd rename attempt, it doesn't work edit and preview show different names (old and new)

**Comment by bharatkashyap** [comment]
@prakhargupta1 I can't replicate this either, I can rename any number of times and there is no difference between edit and preview.

It does create another page in the folder - I think that is a bug (we should be deleting the older page when a renamed copy of the page is created).

**Comment by bharatkashyap** [comment]
@prakhargupta1 I could replicate this today, and this gets solved when the old page is deleted from the file structure. I'll look into finding a fix for this

**Comment by JerryWu1234** [comment]
did anyone see this bug? 
I want to try it.
