### ISSUE TITLE
Support Stats component

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2025]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

A single numerical output, capable of showing:

- title
- number
  - formatting
  - units
 - optional description
 - optional status (good/bad/average/...)
 - 

### Examples 🌈

benchmark:

retool:

![Screenshot 2023-05-16 at 14 39 40](https://github.com/mui/mui-toolpad/assets/2109932/6e03421d-0f8f-436b-b0bb-eb82ce0cfd58)

appsmith:

![Screenshot 2023-05-16 at 14 39 18](https://github.com/mui/mui-toolpad/assets/2109932/ab3d1046-0c71-486c-8f28-309bece831aa)

grafana:

Multiple stats:

![Screenshot 2023-05-16 at 14 41 38](https://github.com/mui/mui-toolpad/assets/2109932/86347225-02a2-4d00-8beb-3d1833f10e6d)

https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/stat/

### Motivation 🔦

* Commonly used custom component in internal use cases (KPI dashboards)

### Benchmark

- https://www.notion.so/mui-org/Stat-component-cbf8ec1d45a34f3fadd6b16f21114487

**Comment by apedroferreira** [comment]
Could this not be done with a Card component that elements can be dragged into, and allowing more control over text?
But if other tools have a `Stats` component I guess there might be a common enough use case for something out-of-the-box.

**Comment by Janpot** [comment]
Yes, this can be done with existing components. But together with chart and table it's probably the most used primitive on dashboards. You can also see that in our public tools repo it's currently implemented as a code component, and reused multiple times https://github.com/search?q=repo%3Amui%2Fmui-public%20codeComponent.HealthBadge&type=code.

**Comment by oliviertassinari** [comment]
I wonder if the people who upvoted https://github.com/mui/mui-toolpad/issues/748 don't want this issue instead.

**Comment by Janpot** [comment]
> I wonder if the people who upvoted #748 don't want this issue instead.

👍 I think that's a fair assumption
