### ISSUE TITLE
Custom components can overflow in UI page, causing visual inconsistencies

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#2028]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Create a custom component with a manual width larger than the page width
2. Place and select the created custom component
3. The selection border around the component does not go around the whole component - it only goes as far as the page width goes

### Current behavior 😯

Custom component elements overflow, making the selection/hover border look wrong.

### Expected behavior 🤔

Overflow should be handled in a way that avoids undesirable visual issues.

Also: custom component documentation should be improved in order to guide users towards not creating custom components that are too wide.

**Comment by Janpot** [comment]
- We should document how custom component implementers should think about sizing and how they can make their components responsive to the available space
- Meanwhile we need to come up with a good behavior that mitigates components not behaving well. Perhaps we can even detect this and guide users to the right documentation? (See also "linting" in https://github.com/mui/mui-toolpad/issues/1851) 
- We need to be mindfull about cases where overflow is actually wanted, e.g. think about menus, popovers,...

**Comment by apedroferreira** [comment]
It looks like the overflow issue from https://github.com/mui/mui-public/pull/102#discussion_r1198878556 only happens with the old version of Toolpad that that project is using, and not the latest one.
It does not happen if I update `"@mui/toolpad` and run `yarn install`, that's why I wasn't able to reproduce it at first...
It's hard to find what fixed it though.

Other than that it seems like Toolpad already handles overflows quite well, maybe I had already taken a look at that before.

So I think we could just slightly improve the documentation on custom components for now?

**Comment by Janpot** [comment]
Can't reproduce on latest Tooplad version
