### ISSUE TITLE
Anomaly in form component or canvas

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2033]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I wanted to add another button in the form component, but realized that it is not possible.
When I was trying it, somehow the button got in a weird state from which I can't delete it or move it. When I try to do any of this, it deletes the form/page.

https://github.com/mui/mui-toolpad/assets/92228082/baf52975-0319-4fe9-aa46-d7675f35f445

The stuck app can be found here: https://github.com/mui/mui-toolpad/pull/1445
Examples > showcase > adminApp

### Your environment 🌎

v0.1.11

**Comment by apedroferreira** [comment]
Damn, lots of weirdness there, thanks for providing the info, I'll take a look.
