### ISSUE TITLE
Custom function parameters not visible

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2047]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. https://mui.com/toolpad/connecting-to-datasources/custom-functions/#parameters

### Current behavior 😯

<img width="686" alt="Screenshot 2023-05-20 at 01 43 33" src="https://github.com/mui/mui-toolpad/assets/3165635/c2f13e78-058b-4861-b2b1-aa62f16ac923">

### Expected behavior 🤔

<img width="697" alt="Screenshot 2023-05-20 at 01 33 57" src="https://github.com/mui/mui-toolpad/assets/3165635/9d23ed38-c59e-4858-ae6e-0128dccddbe3">

### Context 🔦

It's a regression from v0.1.12. It works correctly in v0.1.11.

As a side note, I think that this is wrong: 

https://github.com/mui/mui-toolpad/blob/52cf22f24392057910606b58595f9f4cb26465bf/packages/toolpad/package.json#L34-L35

Since these packages are in the alpha stage, I think that they should have a pinned version.

```json
 "@mui/toolpad-app": "0.1.12", 
 "@mui/toolpad-core": "0.1.12", 
```

To be able to correctly move from v0.1.12 to v0.1.11, I had to do:

```diff
{
  "name": "my-toolpad-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "toolpad dev",
    "build": "toolpad build",
    "start": "toolpad start"
  },
  "dependencies": {
-   "@mui/toolpad": "^0.1.12"
+   "@mui/toolpad": "0.1.11",
+   "@mui/toolpad-app": "0.1.11",
+   "@mui/toolpad-core": "0.1.11"
  }
}
```

Painful. I would like it to be:

```diff
  "dependencies": {
-   "@mui/toolpad": "^0.1.12"
+   "@mui/toolpad": "0.1.11"
  }
```

**Comment by Janpot** [comment]
> Since these packages are in the alpha stage, I think that they should have a pinned version.

Agreed, even outside of alpha stage they should probably have pinned versions (we should actually integrate these back into `@mui/toolpad` but that's a different issue to solve).

It actually used to be pinned, Seems like that [changed](https://github.com/mui/mui-toolpad/pull/1998/files#diff-9c83476cf1a09cd4147facc6b871c7542a4cf8757e9837839a8a540a84f3e199R56-R58) when moving to 0.1.11. Lerna updates the version to `^` by default. I'm changing the versioning script in https://github.com/mui/mui-toolpad/pull/2054 (cc @apedroferreira)
