### ISSUE TITLE
[docs] Restructure

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2052]
As discussed, below is the new docs structure. 

#### A quick brief on Toolpad

1. Overview
1. Installation
1. Build your first app (installation section to be linked)
1. Examples (list of examples from GitHub)
1. Roadmap

#### It will have the 3 existing sections: Connecting to DS, Building UI, Data binding

1. Building UI (current canvas and component library section + page shell parameter)
1. Connecting to data (Queries: HTTP requests, Custom functions, Manually calling queries)
1. Managing state (current data binding section + page variables)
1. Deployment
1. Custom components
1. Theming (Move component styling here)

#### Narrow use cases, to solve immediate pains that come while building a Toolpad app. Eg:

1. Connect to MySQL/Postgresql
1. Delete a data grid row
1. Create custom columns (current data grid section)
1. Deploy to render.com
1. Embed applications
1. Add basic auth

#### How to build e2e app. 
(I think we can invest on this later, as I would prefer these to be video tutorials)

## Reference
1. File schema 
1. Javascript API
1. Components
1. Configuration (env vars to configure Toolpad itself with)

**Comment by Janpot** [comment]
@bharatkashyap I'll restructure the reference pages in https://github.com/mui/mui-toolpad/pull/2001
