### ISSUE TITLE
Custom component not visible after creation in the Component library sidebar

### ISSUE THREAD

**Issue by mnajdova** [mui/mui-toolpad#2053]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Click the plus for adding a custom component
2. Optional - update the component code
3. Expand the component library panel - the component is not visible

### Current behavior 😯

The component is appearing in the component library panel after restarting the server

### Expected behavior 🤔

The component should be visible immediately. 

### Your environment 🌎

Windows 11 Pro
yarn version 1.22.5

**Comment by Janpot** [comment]
I can't reproduce on Mac with that repo/PR. It could be a windows issue.

**Comment by apedroferreira** [comment]
Seems to be a Windows issue, works for me on Mac but I can reproduce it in Windows. I can look into it.
