### ISSUE TITLE
Improve custom function creation flow

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2063]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As discussed yesterday, we need to improve the custom function creation flow. Ideally, a user should initiate function creation from the Toolpad UI and then should be taken to their IDE. So there has to be a **Create function** button.

One way we can do it is by showing a **Create function** field as the last item of the drop-down. Clicking on this will ask for the function name then a toast notification will appear that will take the user to the file.tsx in IDE (just like create component flow). 
Note: It also implies that each function will be created as a new file in resources folder.

![Screenshot 2023-05-24 at 6 50 53 PM](https://github.com/mui/mui-toolpad/assets/92228082/70e02c5c-8a22-4e26-8249-85a1cc3f1377)

We can keep the Open Editor button as it is.

**Comment by Janpot** [comment]
I've implemented a first version of this today https://github.com/mui/mui-toolpad/pull/2062
