### ISSUE TITLE
Horizontal alignment not working for text component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2071]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Add a text component to the canvas.
2. Try to align it from the inspector panel.

### Current behavior 😯

https://github.com/mui/mui-toolpad/assets/92228082/a4220226-1a45-4525-b6fb-fec8062d9c8d

### Your environment 🌎

v.0.1.13

**Comment by rohanprasadofficial** [comment]
@prakhargupta1 , is it available to take up ? I am willing to work on this ?

**Comment by rohanprasadofficial** [comment]
Taking this up
