### ISSUE TITLE
Cannot read properties of undefined (reading 'F_OK')

### ISSUE THREAD

**Issue by SethTurin** [mui/mui-toolpad#2092]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. All I did was try the code in the quickstart : 
 `npx create-toolpad-app dog-app`

### Current behavior 😯

it exits with the error:
`Cannot read properties of undefined (reading 'F_OK')`

### Expected behavior 🤔

I mean, I assume it should create an app or something. I didn't get very far so I don't really know.

### Context 🔦

This was the very first thing I tried, and currently I'm just experimenting.

### Your environment 🌎

It looks like the npx command installed version 0.1.13

I'm using Windows 11

**Comment by SethTurin** [comment]
This issue was happening because of an old version of Node.  I updated Node and it works now.

**Comment by Janpot** [comment]
Thanks for reporting. There's an open [PR](https://github.com/mui/mui-toolpad/pull/193) to lower the minimum Node.js version that should solve this exact error.

But the DX could be better. Unlike `yarn` and `pnpm`, it looks like `npx` doesn't check compatibility with the `engines` field. Perhaps we can add a quick check for node.js version in `create-toolpad-app`? cc @bharatkashyap
