### ISSUE TITLE
Update `create-toolpad-app` to match `engines` 

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#2094]
- [ ] From https://github.com/mui/mui-toolpad/issues/2092#issuecomment-1567937877, we should have a node version check before running 
- [x] ~We should also add `engines` to the `package.json` file created by `create-toolpad-app`~ This is up to the user, as long as we don't generate code that is incompatible with certain node.js versions then the restrictions of `@mui/toolpad-app` and `create-toolpad-app` should do their jobs.
- [ ] Also a `.gitignore` on the root level with `node_modules` inside it so that this step does not have to be manually done when committing the project? @Janpot

**Comment by wulinsheng123** [comment]
May i do this ?

**Comment by Janpot** [comment]
> We should also add engines to the package.json file created by create-toolpad-app

I think we can leave this one up to the user, as long as our package has a correct engines field it should be fine.

**Comment by JerryWu1234** [comment]
> I think we can leave this one up to the user, as long as our package has a correct engines field it should be fine.

What range do the engines field? May I contribute to this issue?

**Comment by Janpot** [comment]
Sorry, I meant it's up tot the toolpad user to decide the engines range of their project, we don't need to choose it for them. I've updated the issue description.

**Comment by JerryWu1234** [comment]
> * From [Cannot read properties of undefined (reading 'F_OK') #2092 (comment)](https://github.com/mui/mui-toolpad/issues/2092#issuecomment-1567937877), we should have a node version check before running

OK I check the node version of the package is >=16.1
I will check the node version greater than or equal 16.1 before it runs.
and we initialize with [that link](https://github.com/github/gitignore/blob/main/Node.gitignore.)
Please tell me if there is any error message.

**Comment by JerryWu1234** [comment]
May I ask what the meaning of the DX is?
what's the full name?
