### ISSUE TITLE
Page tab to be shown in the right panel 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2095]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When a component is clicked, the right panel starts showing the related component props.  The pages state goes to the background and is reachable only when component is deselected. 
We should keep it easily discoverable irrespective of component selection. 2 ways we can do it are:

1. A page tab before Component tab would help. When user clicks a component then the component tab becomes active.
2. Move queries, page params out of the right panel (part of UX revamp)

<img width="390" alt="Screenshot 2023-05-31 at 2 13 25 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/daa22c3d-c2c6-46c3-89b5-95a9bbdd9d25">

### Benchmarks 🌈
Other tools don't have their queries section in the right panel, it's either left panel or at the bottom.

**Comment by JerryWu1234** [comment]
>Move queries, page params out of the right panel (part of UX revamp)

The second way, I was a little confused about it. Where should I put it if we move the queries?

**Comment by JerryWu1234** [comment]
@prakhargupta1

**Comment by prakhargupta1** [comment]
> The second way, I was a little confused about it. Where should I put it if we move the queries?

Currently, we show the list of queries on the right panel. Instead, we can show it in a bottom panel. We'll first design the right UX for this.

**Comment by JerryWu1234** [comment]
> > The second way, I was a little confused about it. Where should I put it if we move the queries?
> 
> Currently, we show the list of queries on the right panel. Instead, we can show it in a bottom panel. We'll first design the right UX for this.

because you provided two ways 
so that How do I choose one of these ways if I want to fix it? Or whatever way is up to me?

**Comment by JerryWu1234** [comment]
@prakhargupta1 
When it comes to these UIs, what is your development process like?
one of your team will offer UI ?

**Comment by prakhargupta1** [comment]
> because you provided two ways
> so that How do I choose one of these ways at random if I want to fix it? Or whatever way is up to me?

For now, we'll follow the first approach. Later, (when we internally agree on a UX design) we'll work as second solution.
