### ISSUE TITLE
Issues with environment variables

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2099]
Trying out new environment variable support. Having a few issues:

- [x] I can't enter an environment variable in a binding unless it's defined in the `.env` file. 
- [x] Toolpad is reading the .env file to interpolate environment variables instead of reading them from the environment. This is causing issues like https://github.com/mui/mui-private/issues/267#issuecomment-1564361133. The .env file is a convenience to locally store variables. We will also use it for suggestions and linting, but by no means is it the single source of thrut. It's just one way of setting up the variables. For reading actual values use `process.env`.
- [ ] The `$$env` method allows us to up front determine some variables the application expects to have access to. We should show a warning on startup when any of the used variables are not defined.

**Comment by apedroferreira** [comment]
Ah yes, environment variables aren't going to work in production this way, we need to read from `process.env`... 
I'll add a fix for 1 and 2 first separately before the others to get it live asap.

**Comment by oliviertassinari** [comment]
> 1. I can't enter an environment variable in a binding unless it's defined in the .env file.

I'm not sure it's a bad outcome. I like that it gives a clear signal of what are the .env variables available. It gives the confidence that the latest env value you added was correctly loaded.

Now, I'm not sure about the "Environment variable" UX: 

<img width="349" alt="Screenshot 2023-06-01 at 10 30 45" src="https://github.com/mui/mui-toolpad/assets/3165635/9358de7b-7e1d-49c7-a32b-28ea7246c0c8">

It might be better as a normal binding value, but making it clear that it's only available when running the queries server-side.

> 2. Toolpad is reading the .env file

Ahhh, now I get why it doesn't work.

**Comment by Janpot** [comment]
> There are advantages. It gives a clear signal of what are the .env variables available. It gives the confidence that the latest env value you added was correctly loaded.

The way I'm thinking about it currently is sort of two-way. 
* We make sure we can easily statically analyze a toolpad project to see which environment variables it expects. This allows us to warn in dev and prod when one is missing. 
* Additionally in dev, we could offer to UI to automatically create it when we detect it's not in the env file. for example: 
  * We could show a google oauthflow and automatically store the token in the .env file in the end
  * We could show a basic auth user+password and save the header in .env
  * We could show a db connection UI with a "test connection" button, and upon saving store the connection string in the .env file.
* In the other direction, we can offer autocomplete support for variables that are already defined in .env file.

> It might be better as a normal binding value, but making it clear that it's only available when running the logic server-side.

The reason we started this way is because it makes variables very explicit and we can unambiguously extract them out of a toolpad application. Additionally it allows us to keep the logic fully on the server and never expose secrets to the browser. Moving from a more restricted to a more free approach is also easier to do over time migration-wise. Some discussion around this: https://github.com/mui/mui-toolpad/pull/1859#pullrequestreview-1418047754
