### ISSUE TITLE
A how to guide for 'how to import and use Toolpad in an existing codebase'

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2107]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, in our docs we have instructions to start a fresh Toolpad app. We should also have a dedicated page to show how Toolpad can be used in a existing project. Eg: A next.js app

### Examples 🌈

https://interval.com/docs/best-practices#running-interval-inside-your-existing-codebase
https://github.com/interval/interval-nextjs/wiki/Adding-Interval-to-a-Next.js-app-using-a-different-process

**Comment by CAGLADJ** [comment]
When including Toolpad into an existing next.js app, is it still necessary to build, before it is possible to use the pages, which have been created/edited in Toolpad?

**Comment by Janpot** [comment]
@CAGLADJ At the moment Toolpad run as a separate Node.js application. In the future we may explore ways to embed the Toolpad pages inside of your application, you can check the open feature request for this: https://github.com/mui/mui-toolpad/issues/1183

**Comment by prakhargupta1** [comment]
Done in https://github.com/mui/mui-toolpad/pull/3214
