### ISSUE TITLE
action how will work in table grid ?

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#2110]
![image](https://github.com/mui/mui-toolpad/assets/128947562/8c6560a6-4059-4e12-9cb7-9173d5c6a046)

@prakhargupta1  hello 
I want to make an action field where clicking on that button want to delete that row API is there but need to write those things on the custom component is there any way where I can directly bind my action instead of making a custom component and writing logic there? and click on that logic is getting performed but the table is getting blank

**Comment by prakhargupta1** [comment]
@Prajapati-developer Hello!

For now, you can delete a row by following the steps mentioned [here](https://github.com/mui/mui-toolpad/issues/1039#issuecomment-1520074417). You'll have to make a common delete button that will apply for a selected row.

Soon we'll support adding an action button in the datagrid and deleting the row from there.
