### ISSUE TITLE
form reset button is not a resetting field of autocomplete and file field value 

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#2112]
![image](https://github.com/mui/mui-toolpad/assets/128947562/aa010e3a-7777-456a-853c-e60d2b8263b9)

**Comment by apedroferreira** [comment]
Hi @Prajapati-developer, the autocomplete field is not integrated with the Form component, but it should.
We'll fix it, thanks for reporting this issue!

**Comment by apedroferreira** [comment]
Hi @Prajapati-developer, we just merged a fix for the Autocomplete component not working with forms - thanks again for raising this issue.

I could not find the issue with the File Picker though - feel free to give us some more details about how it happens, or a way that we can reproduce it, and I will look into it.
