### ISSUE TITLE
Make page title editable from the editor

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2125]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, our page title is not editable from the editor. (`Employees` from the below screenshots)
A user can edit it from the page.yaml. This task is about editing it from the Toolpad UI.

<img width="1192" alt="Screenshot 2023-06-05 at 1 16 51 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/e72e3571-2465-48cb-b0e7-d58c6ab9c117">

<img width="811" alt="Screenshot 2023-06-05 at 1 20 43 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/1c62a796-c371-4b23-ab6b-96e7bc611c53">

**Comment by Kirera-Wainaina** [comment]
Hello, I'd like to work on this issue.

**Comment by Janpot** [comment]
I believe we can add a textfield to update the title here:

<img width="1192" alt="243286656-e72e3571-2465-48cb-b0e7-d58c6ab9c117 (1)" src="https://github.com/mui/mui-toolpad/assets/2109932/5732015f-a635-4f02-9a9b-18c5690023bf">

**Comment by Kirera-Wainaina** [comment]
When you create a page, initially the page title is based on page-`Node name`. Creating a text field could mean that they may not match. 
1. I could make the title to match the `Node name`. Meaning that when you change the `Node name`, the title could will match as well. This is the default when you first create a page.
2. Create a text field so the user can customize the page title.

Just so we are clear, you want 2 over 1.

**Comment by prakhargupta1** [comment]
For me, `Employees` (in the screenshot above) as another concept only brings more confusion.  I agree with solution 1. shared by @Kirera-Wainaina. 

Maybe later we can remove the title field from the .yaml, unless it needs to be there.

**Comment by Kirera-Wainaina** [comment]
Cool, 
I'll work on the text field.
