### ISSUE TITLE
Running the build command ends in RollupError

### ISSUE THREAD

**Issue by CAGLADJ** [mui/mui-toolpad#2126]
I was trying out the toolpad and installed it through `npx create-toolpad-app`. I used the toolpad a bit (added components to a page, etc.).

When following the [deployment guide](https://mui.com/toolpad/deployment/) in the documentation, running `npm run build` ended in the following error message:

```
Could not resolve entry module "index.html".
Error [RollupError]: Could not resolve entry module "index.html".
    at error (file:///C:/Users/.../node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
    at ModuleLoader.loadEntryModule (file:///C:/Users/.../node_modules/rollup/dist/es/shared/node-entry.js:24017:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
```

The installed @mui/toolpad version is 0.1.14

What did I miss? I couldn't find anything about having to create an `index.html` file inside the documentation.

The full terminal message is below:
```
C:\...>npm run build

> toolpad@0.1.0 build
> toolpad build

info  - building Toolpad application...
vite v4.3.9 building for production...
✓ 0 modules transformed.
✓ built in 20ms
Could not resolve entry module "index.html".
Error [RollupError]: Could not resolve entry module "index.html".
    at error (file:///C:/Users/.../node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
    at ModuleLoader.loadEntryModule (file:///C:/Users/.../node_modules/rollup/dist/es/shared/node-entry.js:24017:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
toolpad build [dir]

Build Toolpad app for production

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
  --dir      Directory of the Toolpad application        [string] [default: "."]

Error: Command failed with exit code 1: C:\Program Files\nodejs\node.exe 
C:\Users\...\node_modules\@mui\toolpad-app\dist\cli\appBuilder.js
    at makeError (C:\Users\...\node_modules\@mui\toolpad-app\dist\cli\index.js:1124:17)
    at handlePromise (C:\Users\...\node_modules\@mui\toolpad-app\dist\cli\index.js:1945:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildCommand (C:\Users\...\node_modules\@mui\toolpad-app\dist\cli\index.js:2938:3) {
  shortMessage: 'Command failed with exit code 1: C:\\Program Files\\nodejs\\node.exe C:\\Users\\...\\node_modules\\@mui\\toolpad-app\\dist\\cli\\appBuilder.js',
  command: 'C:\\Program Files\\nodejs\\node.exe C:\\Users\\...\\node_modules\\@mui\\toolpad-app\\dist\\cli\\appBuilder.js',
  escapedCommand: '"C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\node_modules\\@mui\\toolpad-app\\dist\\cli\\appBuilder.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by Janpot** [comment]
Thanks for reporting. You don't need to create and `index.html`, Toolpad does that for you. I suspect a issue with the `build` command when running on windows. Would you mind sharing your project folder so we can double check?

**Comment by CAGLADJ** [comment]
What would be the easiest way to share it?

**Comment by Janpot** [comment]
> What would be the easiest way to share it? Should the node_modules be included?

Either as a GitHub repository, or zip up your project folder and attach as a file on a comment. Don't include node_modules, a package.lock or yarn.lock will be enough.

**Comment by CAGLADJ** [comment]
Okay, here it is.
[projectFolder.zip](https://github.com/mui/mui-toolpad/files/11650993/projectFolder.zip)

**Comment by Janpot** [comment]
@CAGLADJ  I'm proposing a [change](https://github.com/mui/mui-toolpad/pull/2131) that could solve this issue. I currently don't have access to a windows machine to fully test this, but if you don't mind verifying whether this would solve your issue.

Run
```
npm install --force https://pkg.csb.dev/mui/mui-toolpad/commit/6b2f443d/@mui/toolpad
```
in your project and try again.

**Comment by CAGLADJ** [comment]
@Janpot Thank you, it looks like it is working. So, for now I will have to install toolpad with the command above? I guess, this will be included in the next release?

**Comment by Janpot** [comment]
Yes, we'll release another version tomorrow
