### ISSUE TITLE
Queries stop working when a page is renamed

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2127]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Rename a page
2. Check if the queries are working

### Your environment 🌎

v0.1.13

**Comment by prakhargupta1** [comment]
Relates to: https://github.com/mui/mui-toolpad/issues/1984

**Comment by JerryWu1234** [comment]
I can't replicate this bug.
But the dev mode has more pages than the preview mode.
![image](https://github.com/mui/mui-toolpad/assets/27261522/698397ed-4d7f-4a24-8e15-0d06c817a320)
![image](https://github.com/mui/mui-toolpad/assets/27261522/2a818473-a380-4f35-ab3d-531f990259da)

**Comment by prakhargupta1** [comment]
Renaming a page seems to be creating this. These may have been deleted from the edit mode but somehow reappeared in the preview mode.

Regarding queries, use a query to bind 2 components and then rename the page. The query will stop working.

**Comment by Janpot** [comment]
For future reference

https://github.com/mui/mui-toolpad/assets/2109932/b37b09c8-21bf-4086-9c5b-4a78273e768b

**Comment by prakhargupta1** [comment]
This seems to have fixed?


https://github.com/mui/mui-toolpad/assets/92228082/dcd20944-38cd-486a-9102-b94e0c6eb833
