### ISSUE TITLE
Performance degradation on the example app

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2139]
### Steps to reproduce 🕹

Steps:

1. Run and profile the example application: https://github.com/mui/mui-toolpad/pull/2096
2. Notice the app being very sluggish, up to a point we can call it unusable.
3. Record a performance trace
4. Notice it renders on every keystroke and the renders take about ~200 - ~250ms to complete (I'm on a Macbook air M1):
      
    ![Screenshot 2023-06-06 at 13 32 29](https://github.com/mui/mui-toolpad/assets/2109932/87ff22fe-17c9-44e5-8292-b050a6b26d86)

### Current behavior 😯

It's just too slow. Did a quick code review and the biggest contributor to this sluggishness seems to be because we are recalculating the state for the whole page on every node we render. This is a regression that was likely introduced when we added nested scopes to the runtime to enable List and Form components. 
Before that the whole page used to be calculated on every keystroke, but only once. This is also a bit wasteful, but nothing compared to doing it on every node which turns a O(n) algorithm into O(n^2) (n being the amount of nodes on the page).

### Expected behavior 🤔

The page state is only calculated once for the whole page

**Comment by apedroferreira** [comment]
I didn't notice at the time but those changes might have an impact on the performance...
Thanks for looking into it, let me know if I can help with anything!
