### ISSUE TITLE
Update gifs to videos in docs 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2164]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Videos take less space and provide controls like pause, fullscreen to the user.

### Examples 🌈

https://docs.windmill.dev/docs/core_concepts/auto_generated_uis

### Motivation 🔦

To provide better docs experience.

**Comment by Gimnath-Perera** [comment]
Hi @prakhargupta1 can you assign this to me ?
