### ISSUE TITLE
failing during setup of a new project

### ISSUE THREAD

**Issue by githubtraveler** [mui/mui-toolpad#2168]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. setup the npm library for mui tools and toolpad
2. npx create-toolpad-app <project-name>
3. result: 
failed to initiate the project.

### Current behavior 😯

export from Mac terminal (excluded private info):
info - Creating Toolpad project in <project path name>
info  - Initializing package.json file
info  - Initializing .gitignore file
ENOENT: no such file or directory, copyfile '..../node_modules/create-toolpad-app/dist/.gitignore' -> '...<project path>/.gitignore'

### Expected behavior 🤔

should initiate the project: create folder with all the files. 

### Your environment 🌎

Mac, chip M2.

**Comment by Janpot** [comment]
Thank you for reporting, I can confirm. Working on a fix in https://github.com/mui/mui-toolpad/pull/2169
