### ISSUE TITLE
custom function not showing for query 

### ISSUE THREAD

**Issue by Prajapati-developer** [mui/mui-toolpad#2211]

**Comment by Janpot** [comment]
This needs a full reproduction.
For the future, please use the [bug template](https://github.com/mui/mui-toolpad/issues/new?assignees=&labels=status%3A+needs+triage&projects=&template=1.bug.yml)

**Comment by Janpot** [comment]
https://github.com/mui/mui-toolpad/pull/2133 has fixed some edge-cases where fuctions don't show up. This will be part of version 0.1.18
