### ISSUE TITLE
Toolpad examples not working in codesandbox

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2229]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

The codesandbox link we have added in examples for a [QR code generator app](https://mui.com/toolpad/examples/qr-generator/) is not working. 

There is another `custom-data-grid` app in our examples folder that has a [codesandbox link](https://codesandbox.io/p/sandbox/github/mui/mui-toolpad/tree/master/examples/custom-datagrid-column) which is also not working. The error is: "ENOSPC: no space left on device, write"

2 recently added examples, npm-stats and admin-app are working fine. Somehow, old apps are having issues. We discussed that it could be due to the size of node modules folder.

**Comment by Janpot** [comment]
It looks like we're hitting size limits in codesandbox. 

<img width="530" alt="Screenshot 2023-06-29 at 10 10 32" src="https://github.com/mui/mui-toolpad/assets/2109932/72036e98-17de-43bf-9647-099be012a2ef">

Where does this 6GB come from?

project folder is about 1GB:
```sh
$ du -sh .     
966M    .
```
yarn cache folder is about 5GB:
```
$ du -sh /project/home/janpot/.cache/yarn/v6
4.9G    /project/home/janpot/.cache/yarn/v6
```

After manually purging the cache and reinstalling:

```
$ du -sh $(yarn cache dir)
2.5G    /project/home/janpot/.cache/yarn/v6
```
I'm opening https://github.com/codesandbox/codesandbox-client/issues/7697 with them

On our side we can also do a few things to reduce install size:

A fresh install of the `qr` example yields a 750MB folder. I noticed Next.js takes up about 250MB of that space, that includes:
* the next node module: 66MB
* the .next output folder: 40MB
* the @next/swc... package: 95MB

I'm pushing https://github.com/mui/mui-toolpad/pull/1999 forward to start getting rid of it.

Other big space consumers are:
* @mui/icons-material: 135MB => having esm only would probably reduce this to around 45MB
* monaco-editor: 90MB => we should be able to move this to dev dependency as it gets bundled
* date-fns: 25MB 
* react-devtools-inline: 25MB => we should also be able to move this to dev dependencies as we compile it into a runnable script
* @mui/material: 20MB
