### ISSUE TITLE
Undo/Redo action

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#226]
The very first frustration I had using the tool today is not being able to undo a change. I have tried a change that didn't work, now, I'm not sure how to get back to the previous state that was better. It doesn't incentive me to experiment.

To do:

- [x] basic undo/redo based on a undo history stack of the dom state https://github.com/mui/mui-toolpad/pull/1225
- [x] Keyboard shortcut: Undo <kbd>Ctrl</kbd>+<kbd>Z</kbd> and Redo <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> #1274
- [x] undo/redo button needs to be disabled when the stack is empty
- [x] If undoing/redoing change that is in a different view - don't do the undo, focus that view instead (i.e. we made changes in connection view, went to canvas editor and did undo - we should end up in connection view). For extra context, read the discussion in https://github.com/mui/mui-toolpad/pull/1225#discussion_r1007856833
- [x] make atomic changes instead of using a throttle to combine changes, currently known issues:
  - [x] Combine multiple changes when typeing an input of a string property value. What's the best way?
  - [x] Make insertion of elements atomic https://github.com/mui/mui-toolpad/pull/1374
  - [ ] ...?
- [ ] Display a history of changes
- [x] Make dom selection part of undo/redo

### How do other tools push to history when typing text?
|                                   | debounce | throttle | word delimiters |
|---------------------------------|:--------:|:--------:|:---------------:|
| google docs                             | ✅        | ✅        |                 |
| notion | ✅        |          | ✅               |
| vscode            |          |          | ✅               |
| figma                             | ✅        |          |                 |

**Comment by newguy-123** [comment]
To get some idea on how Undo and Redo should work in different scenarios:
https://github.com/appsmithorg/appsmith/issues/1426#issuecomment-810842190

**Comment by apedroferreira** [comment]
First prerequisite for undo/redo: https://github.com/mui/mui-toolpad/issues/845

**Comment by bytasv** [comment]
As a follow up to https://github.com/mui/mui-toolpad/pull/1225 we should make following UX improvement:
- [ ] If undoing/redoing change that is in a different view - focus that view (i.e. we made changes in connection view, went to canvas editor and did undo - we should end up in connection view)

High level pseudo-code proposal:
```ts
function getViewForDom(dom: AppDom): ToolpadView
function isSameView(view1: ToolpadView, view2: ToolpadView): boolean
function navigateToView(ToolpadView): void
```

**Comment by apedroferreira** [comment]
> High level pseudo-code proposal:

Maybe `focusOnView` instead of `navigateToView`? Other than that sounds good if we need this type of solution.

**Comment by Janpot** [comment]
This was just some pseudo-code to illustrate an idea, I didn't intend for this to be used as a starting point or anything.

**Comment by oliviertassinari** [comment]
The undo / redo is broken on https://master--toolpad.mui.com/_toolpad/app/cl9my2gkr0001q89lt82h56ey

https://user-images.githubusercontent.com/3165635/201174983-5b2f95b7-0a90-4d9e-a1af-2afeef9a8855.mov

When I press <kbd>Cmd</kbd>+<kbd>Z<kbd> key, it undo 2 actions, not one. It seems to be related to waiting for the change to commit

**Comment by bytasv** [comment]
> The undo / redo has a bug

@oliviertassinari thanks, that's a great catch. I already found the cause - it happens because throttled undo stack update is triggered after we undo action which messes up the state. I have one working solution to the issue that makes situation way better, but not perfect yet, I should post an update soon

> I don't think that the undo/redo button will ever be used more than 5% of the time, I think that it could be hidden from the interface, into a submenu like notion has

I do agree, I could just remove the buttons. @gerdadesign any issues from your end if we remove the buttons? Maybe you could share what was the motivation of having them designed in the UI? Maybe we are missing some important details?

**Comment by oliviertassinari** [comment]
I could find a strange behavior: when doing an undo or a redo, the sync state doesn't show correctly: It keeps saying "All changes saved"

<img width="150" alt="Screenshot 2022-11-12 at 22 54 41" src="https://user-images.githubusercontent.com/3165635/201496041-c77cb909-7432-4394-b240-ef61152c3b72.png">

**Comment by bytasv** [comment]
I'm removing undo/redo buttons as part of https://github.com/mui/mui-toolpad/pull/1308 👍

**Comment by Janpot** [comment]
This has been implemented
