### ISSUE TITLE
Broken image in the examples README

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2264]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open https://github.com/mui/mui-toolpad/tree/master/examples/qr-generator
2. Check the screenshot

### Current behavior 😯

No screenshot, just a JSON blob

### Expected behavior 🤔

Screenshot visible in the markdown
Screenshot file included in the example folder

### Context 🔦

This happens on all examples

**Comment by prakhargupta1** [comment]
It is happening because this .md file is being used for the docs page as well and this image is being rendered there.
I don't know how can I make image selection conditional from this .md file.
