### ISSUE TITLE
Use MUI X Charts Library in Chart component

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#2309]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a first approach, we used `recharts` for the Chart component, in order to get a working component out as easily as possible.
We should migrate from `recharts` to the MUI X charts library, including finding possible issues or suggestions for the library itself.

### Motivation 🔦

Using our own libraries/products as much as possible.

**Comment by Janpot** [comment]
This [comment](https://github.com/mui/mui-toolpad/pull/2230#issuecomment-1635329738) is about moving this example to the new toolpad chart component you created, not about moving the toolpad chart component to `@mui/charts`
