### ISSUE TITLE
Create a logo for MUI Toolpad

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#234]
For example, to get a fancy page favicon

<img width="607" alt="Screenshot 2022-03-28 at 20 23 17" src="https://user-images.githubusercontent.com/3165635/160462180-365b3964-e280-4253-b7d0-72b9665a7ca4.png">

I don't think that it's part of the first step to making the repo public but it could be one of the priorities of the design role we are hiring for.

**Comment by gerdadesign** [comment]
Per voting on Slack, we had the most votes for the color Blue. When I checked again, it changed to a tie between Blue and Orange. We also had a lot of discussion in the thread, so checking if we are ok to move forward with Blue for now or do we want to continue the color conversation _before_ we release the landing page? 

I believe we will still have the opportunity to revisit the branding later on when MUI Toolpad has matured.


![Image](https://user-images.githubusercontent.com/106991024/183514549-8a4da6dd-f85f-4581-9915-12349883b77c.jpg)

**Comment by oliviertassinari** [comment]
@gerdadesign I think that ultimately, it's your call.

*I can see that the arrival of the new laptop with a high-density screen will be welcome 😁*

**Comment by gerdadesign** [comment]
Per our final vote via slack, [blue](https://www.figma.com/file/fNowz3HeGrUJshzjUvvY1e/Toolpad-landing-page?node-id=1019%3A64196) is the winner! 



![Image](https://user-images.githubusercontent.com/106991024/184667003-39e20a76-7c21-4e23-9e8f-da16684c8382.svg)

**Comment by oliviertassinari** [comment]
@gerdadesign Ok great thanks. I have updated the team logo on GitHub https://github.com/orgs/mui/teams/toolpad

<img width="299" alt="Screenshot 2022-08-17 at 00 15 16" src="https://user-images.githubusercontent.com/3165635/184994641-e25027c8-c3b9-4a38-a1bf-2405a302b72a.png">

It looks better when assigning:

<img width="384" alt="Screenshot 2022-08-17 at 00 16 53" src="https://user-images.githubusercontent.com/3165635/184994879-efe21707-b405-4383-b9d9-63644413cc07.png">
