### ISSUE TITLE
Reorganise query editor and link docs

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2395]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Suggestions:
1. Add a title
2. Move Preview button to the bottom right
3. Link docs
4. Add title for query settings

Current:
![Screenshot 2023-07-31 at 3 33 36 PM](https://github.com/mui/mui-toolpad/assets/92228082/64758028-df5f-4ae6-b111-165b8f4d975a)

Suggested:
![Screenshot 2023-07-31 at 3 32 57 PM](https://github.com/mui/mui-toolpad/assets/92228082/d59aca4a-5e72-45fe-9962-69d40eb0cc58)

Note: These also apply for custom functions UI

### Motivation 🔦

Add clarity and docs linkage to troubleshoot when someone is stuck

**Comment by bharatkashyap** [comment]
Started an effort here https://github.com/mui/mui-toolpad/pull/2393

**Comment by prakhargupta1** [comment]
Closing it as we are moving away from this modal.
