### ISSUE TITLE
Add a 'Get a demo' button on Toolpad home page

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2402]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We currently have a video and examples to explain how Toolpad can be used. But there would be many users who may have many questions just about getting started on Toolpad, let's remove this hurdle by allowing them to get on a call with us and see Toolpad live in Action.

[Link to be used](https://calendly.com/prakhar-mui/toolpad)

Later on, we can add a form to get a better idea of user requirements.

Benchmarks:
https://www.dronahq.com/
https://www.tooljet.com/
https://retool.com/

**Comment by prakhargupta1** [comment]
> Another alternative is to follow https://mui.com/base-ui/, move the getting started instructions lower and a "Get demo" button in the hero section along with "Get started"

I agree it's a good choice! For the bottom section, we can have 2 sections each for Get Started and newsletter.

**Comment by bharatkashyap** [comment]
>  For the bottom section, we can have 2 sections each (side by side) for Get Started and newsletter.

I meant something like this:
<img width="409" alt="Screenshot 2023-08-02 at 2 58 38 PM" src="https://github.com/mui/mui-toolpad/assets/19550456/ddae99d1-f594-470b-b8a8-e0aa194e0149">

**Comment by prakhargupta1** [comment]
> I meant something like this:

My bad, just saw the base UI page again and came here to edit my comment😅. This is perfect! 
Ok, let's change it to Book a demo.
