### ISSUE TITLE
Failing "Create-toolpad-app:test" test on cloning repository

### ISSUE THREAD

**Issue by Kirera-Wainaina** [mui/mui-toolpad#2414]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Clone the repository onto my machine
2. `cd mui-toolpad`
3. Install dependencies - `yarn install`
4. `yarn test` -> Initially fails 2 / 3 tests
5. `yarn dev`
6. `yarn test` -> fails 1 / 3 tests

### Current behavior 😯

Running `yarn test` Immediately after cloning the repository, results in two of the tests failing.

Running `yarn dev` and `yarn test` after that results in one test failing: **create-toolpad-app:test**
![failing-test](https://github.com/mui/mui-toolpad/assets/52700465/db737b92-5889-4921-a965-1d64a04e8f30)

### Expected behavior 🤔

I expect the tests to pass considering I haven't made any changes

### Your environment 🌎

OS: "Ubuntu 22.04.2 LTS"
Node: v16.20.1
MUI: v0.1.21

**Comment by Janpot** [comment]
👍 Yes, this is a bit of a flaky and slow test. It's installing the node modules for the created toolpad project. @bharatkashyap Perhaps we should omit installation during the tests?

**Comment by Kirera-Wainaina** [comment]
You are right about the installations taking time. I've adjusted time to `jest.setTimeout(600000);` which 10x the timeout time but it leads to another problem.
![Screenshot from 2023-08-03 14-44-37](https://github.com/mui/mui-toolpad/assets/52700465/a75be897-0145-49ae-bec6-c3103f8ccf06)

**Comment by Janpot** [comment]
It's annoying that we can't see the output of running the `create-toolpad-app` command. Could you apply

```diff
diff --git a/packages/create-toolpad-app/tests/index.spec.ts b/packages/create-toolpad-app/tests/index.spec.ts
index 85e19a6d5..3db699e81 100644
--- a/packages/create-toolpad-app/tests/index.spec.ts
+++ b/packages/create-toolpad-app/tests/index.spec.ts
@@ -3,6 +3,7 @@ import * as path from 'path';
 import * as url from 'url';
 import readline from 'readline';
 import { Readable } from 'stream';
+import { buffer } from 'stream/consumers';
 import { execa, ExecaChildProcess } from 'execa';
 import { jest } from '@jest/globals';
 import { once } from 'events';
@@ -38,9 +39,11 @@ test('create-toolpad-app can bootstrap a Toolpad app', async () => {
   testDir = await fs.mkdtemp(path.resolve(currentDirectory, './test-app-'));
   cp = execa(cliPath, [path.basename(testDir)], {
     cwd: currentDirectory,
+    stdio: 'pipe',
   });
-  const result = await cp;
-  expect(result.stdout).toMatch('Run the following to get started');
+  cp.stdout!.pipe(process.stdout);
+  const stdout = await buffer(cp.stdout!);
+  expect(String(stdout)).toMatch('Run the following to get started');
   const packageJsonContent = await fs.readFile(path.resolve(testDir, './package.json'), {
     encoding: 'utf-8',
   });
```

and try again? This should make visible where it gets stuck.

**Comment by Kirera-Wainaina** [comment]
I figured `fetch` is from `node-fetch` so I've imported it and increased the time to timeout in Jest. It now works. What I've done to solve to issue.
```diff
diff --git a/packages/create-toolpad-app/tests/index.spec.ts b/packages/create-toolpad-app/tests/index.spec.ts
index 85e19a6d..0d2ca923 100644
--- a/packages/create-toolpad-app/tests/index.spec.ts
+++ b/packages/create-toolpad-app/tests/index.spec.ts
@@ -6,8 +6,9 @@ import { Readable } from 'stream';
 import { execa, ExecaChildProcess } from 'execa';
 import { jest } from '@jest/globals';
 import { once } from 'events';
+import fetch from 'node-fetch';
 
-jest.setTimeout(60000);
+jest.setTimeout(600000);
 
 const currentDirectory = url.fileURLToPath(new URL('.', import.meta.url));

```
Let me know if you still need me to go ahead and do what you are suggesting.

**Comment by Janpot** [comment]
> Let me know if you still need me to go ahead

👍 Much appreciated if you'd open a PR. Importing from `node-fetch` would be helpful, but then also add it to this package's `devDependencies`, and make sure to set the version to exactly `2.6.12` (we're staying on the 2.x line for another package and will upgrade in a separate effort).

To avoid multiplying our ci runtime by 10 for failing create-toolpad-app tests we could do something like:

```tsx
jest.setTimeout(process.env.CI ? 60000 : 600000);
```

but if the shorter timeout works for you with the `node-fetch` fix, I'd probably just keep it the way it is.

> ... and do what you are suggesting.

Yes, let's include these changes, it's very helpful to see this output when debugging the test.
