### ISSUE TITLE
In the page params dialog box, link the docs page

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2423]
### Summary 💡

![Screenshot 2023-08-28 at 16 00 26](https://github.com/mui/mui-toolpad/assets/2109932/6ee98cf4-8ed2-4c45-aca1-382aa1598771)

### Shaping

1. Replace the text with 
    > Page parameters allow you to pass external data into the Toolpad page state via the URL query. Read more in the [docs](https://mui.com/toolpad/concepts/managing-state/#page-parameters).

2. In between the text and the parameters list, add a live preview for how it's to be used in a toolpad url. e.g. when the user added variables `foo` and `bar`. Show:
   > Usage preview: 
   > ```
   > ?foo=&bar=
   > ```

**Comment by prakhargupta1** [comment]
Hey @Kirera-Wainaina, Thanks for checking it out. Allow me a few days to get back on this one. I need to internally check about linking which docs make the most sense.

**Comment by prakhargupta1** [comment]
@Kirera-Wainaina We groomed this issue yesterday, feel free to pick it up.

**Comment by Kirera-Wainaina** [comment]
I'll work on it.
