### ISSUE TITLE
sidebar: pages don't scroll

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2430]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. have more pages than the sidebar heigth can hold https://github.com/mui/mui-public/tree/master/tools-public
1. try to scroll

<img width="393" alt="Screenshot 2023-08-04 at 14 55 58" src="https://github.com/mui/mui-toolpad/assets/2109932/7bf300f8-44f8-4e96-9871-ec385f3b7100">

### Current behavior 😯

It doesn't scroll

### Expected behavior 🤔

It should scroll

**Comment by JerryWu1234** [comment]
let me take a look this problem
