### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by koolschool935** [mui/mui-toolpad#2504]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. yarn create toolpad-app my-toolpad-app
2. cd my-toolpad-app
3. yarn dev

### Current behavior 😯

When accessing editor at localhost:3000 error apears "structuredClone is not defined"

### Context 🔦

Seems like canvas issue

### Your environment 🌎

Edition Windows 11 Pro
Version 22H2
OS build 22621.1992
Experience Windows Feature Experience Pack 1000.22644.1000.0

Latest MUI Toolpad

**Comment by koolschool935** [comment]
im using v20.4.0

**Comment by koolschool935** [comment]
same on 18.17.1

![slika](https://github.com/mui/mui-toolpad/assets/48473053/81ce4d3f-495c-4126-8221-bd1d90345fe3)
this is error message

**Comment by apedroferreira** [comment]
Thanks! Maybe the canvas is using an old Node version, we'll look into it, thanks for reporting the issue.

**Comment by apedroferreira** [comment]
Hi @koolschool935 , can you please run `npx @mui/envinfo` and tell me the output + which browser you use?
Maybe the browser you're using does not support `structuredClone`? https://caniuse.com/?search=structuredClone

**Comment by koolschool935** [comment]
Hey,

I'd been using an old version of Firefox for like a year because I really liked its UI. Tried it on Chrome and it worked fine there.

Realized it was my bad for not checking in a different browser earlier. Thanks for asking, "Which browser do you use?" That simple question actually solved my issue. 🤦‍♂️

Thanks a lot for your help!

**Comment by apedroferreira** [comment]
> Hey,
> 
> I'd been using an old version of Firefox for like a year because I really liked its UI. Tried it on Chrome and it worked fine there.
> 
> Realized it was my bad for not checking in a different browser earlier. Thanks for asking, "Which browser do you use?" That simple question actually solved my issue. 🤦‍♂️
> 
> Thanks a lot for your help!

No worries, glad we figured it out! :)
