### ISSUE TITLE
Page explorer panel height should presist

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2516]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As shown in the video, the width of the right panel persists. The same UX should also be there for page explorer.

https://github.com/mui/mui-toolpad/assets/92228082/b9272eae-57c3-4102-9fc9-0604bb429d94

**Comment by Janpot** [comment]
@bharatkashyap Correct me if I'm wrong, but I believe this would be closed by https://github.com/mui/mui-toolpad/pull/2398?

**Comment by bharatkashyap** [comment]
> @bharatkashyap Correct me if I'm wrong, but I believe this would be closed by #2398?

Yes. this should be fixed by adding an `autoSaveId` for this panel
