### ISSUE TITLE
Navigate action in Toolpad

### ISSUE THREAD

**Issue by newguy-123** [mui/mui-toolpad#252]
- [ ] 1. Native Toolpad features?
https://docs.appsmith.com/v/v1.2/core-concepts/connecting-ui-and-logic/internal-functions
- [ ] 2. Sharing data via Query params or local?
https://docs.appsmith.com/v/v1.2/core-concepts/connecting-ui-and-logic/sharing-data-across-pages

**Comment by oliviertassinari** [comment]
This issue feels too broad. It seems that #79 and #76 covers sub parts of this issue.
