### ISSUE TITLE
Use custom page name in the navigation sidebar

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2527]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently the sidebar navigation shows the page name. The range of options is quite limited for this value as Toolpad object names can only be valid javascript identifiers. 
However, we should allow customizing the name in the sidebar navigation (and potentially other places). How about introducing a "display name" property on the page to set a human readable entry in the navigation sidebar?

### Motivation 🔦

See discussion https://github.com/mui/mui-toolpad/discussions/2526

**Comment by JerryWu1234** [comment]
let me take a look

**Comment by JerryWu1234** [comment]
@Janpot 
1. Could I turn on this limitation let user type whatever they want ?

**Comment by JerryWu1234** [comment]
mark
