### ISSUE TITLE
Add a search box in the component library

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2529]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Problems it can solve:

1. A user can search for input and relevant results like textfield can be shown
2. A user can search for markdown and text can be shown
3. A user can find a component that they created. When they are building a big application with many custom components it will definitely be of help.

### Examples 🌈

-Retool shows correct results even if I make a typo:
<img width="257" alt="Screenshot 2023-08-23 at 11 41 36 AM" src="https://github.com/mui/mui-toolpad/assets/92228082/988fcbb3-1fdc-4294-8bbf-13f024173ec4">

-Similar experience on appsmith
<img width="254" alt="Screenshot 2023-08-23 at 11 43 10 AM" src="https://github.com/mui/mui-toolpad/assets/92228082/57ea9525-0bde-40f0-b8c4-b14e9fcd8cfe">

**Comment by JerryWu1234** [comment]
I want to try it.
this issue needs a UI or I can develop directly ?

**Comment by Janpot** [comment]
> this issue needs a UI

The UI will remain the same, except there will be a textfield at the top op the component drawe, full width, with a search icon. Typing in the textfield will show the same sections of components, but each one of them filtered. If a filtered section is empty, we will omit it altogether.

**Comment by JerryWu1234** [comment]
I did a similar function before.

**Comment by JerryWu1234** [comment]
In my  implementation, I will use this [library](https://www.npmjs.com/package/fuse.js)

**Comment by JerryWu1234** [comment]
![image](https://github.com/mui/mui-toolpad/assets/27261522/3eef9d5c-2532-4b8a-b4a1-7827eaa58f97)

**Comment by Janpot** [comment]
Closed by https://github.com/mui/mui-toolpad/issues/2529
