### ISSUE TITLE
Charts UX improvements

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2542]
### Steps to reproduce 🕹

Collecting a few small UX issues around the new Chart component

- [x] The series cycle between two default colors. Can we define a larger palette of colors to use from?
- [x] When creating a new dataseries, I'd expect the series editor for that newly added to open automatically.
- [x] Remove Chart from "future components" section
- [ ] ?

**Comment by apedroferreira** [comment]
I've added these 2 here as they weren't very complex/difficult: https://github.com/mui/mui-toolpad/pull/2500
I've decided to use the `blueberryTwilight` color palette in https://mui.com/x/react-charts/styling/ as the default.
