### ISSUE TITLE
Query editor panels location changed

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2555]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![Screenshot 2023-08-28 at 16 03 02](https://github.com/mui/mui-toolpad/assets/2109932/3bbab452-691f-4b48-b46b-0b1f0f4a4cef)
![Screenshot 2023-08-28 at 16 03 17](https://github.com/mui/mui-toolpad/assets/2109932/695bf3db-fad9-404d-a48c-7cea583123a8)

The orientation of these panels seems to have have switched. What's now on the bottom used to be the right panel.

Did this happen in https://github.com/mui/mui-toolpad/pull/2398?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by apedroferreira** [comment]
I checked if this was caused by https://github.com/mui/mui-toolpad/pull/2544 just in case, but apparently not.

**Comment by bharatkashyap** [comment]
This did indeed happen in #2398 (intentional - I mentioned it as a change in the PR description but it probably got missed in the reviews)
