### ISSUE TITLE
Link custom component doc from the component library

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2560]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Custom components: Add question mark behind “CUSTOM COMPONENTS” subtitle in the components editor. One line explainer in the tooltip:
> Expand Toolpad with your own React components. [Click](https://mui.com/toolpad/concepts/custom-components/) to read more.

**Comment by rohanprasadofficial** [comment]
@prakhargupta1 do you mean this section here with question mark and tooltip ? 

<img width="814" alt="image" src="https://github.com/mui/mui-toolpad/assets/30728574/83fb407f-db62-4c8f-a3ec-a51e05546388">

**Comment by rohanprasadofficial** [comment]
ok taking this up.
