### ISSUE TITLE
Link docs for theme editor

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2561]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In the theme editor on the right side panel,  add short text:
> Customize the app with a MUI theme. Read more about this in the [docs](https://mui.com/toolpad/concepts/theming/).

<img width="311" alt="Screenshot 2023-08-29 at 12 18 42 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/72185054-4ba3-4a04-8488-52dbe5a0e23e">

<img width="306" alt="Screenshot 2023-08-29 at 12 18 49 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/dd5d268c-a489-43c8-b8bd-1951dd796214">

**Comment by rohanprasadofficial** [comment]
@prakhargupta1 , is it available/triaged to take up ? I am willing to work on this ? a

**Comment by rohanprasadofficial** [comment]
Taking this up
