### ISSUE TITLE
Link docs for display mode

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2562]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Display mode: add a tooltip with a short explainer:
> Control how the navigation panel is rendered in the final application. Read more in the [docs](https://mui.com/toolpad/concepts/display-mode/).

**Comment by rohanprasadofficial** [comment]
Taking this up 👍
