### ISSUE TITLE
Support data grid column type date formats

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2581]
### Summary 💡

Today, developers can set their column type to date:

<img width="277" alt="Screenshot 2023-08-30 at 14 14 54" src="https://github.com/mui/mui-toolpad/assets/3165635/9e375a18-4935-48cb-a426-88947c57cdca">

However, have no options to decide what formatting it should use exactly. It's using the default MUI X column type formatting https://mui.com/x/react-data-grid/column-definition/#column-types, so effectively `value.toLocaleDateString()`.

It would be great to be able to choose from more options, a bit like numbers

<img width="291" alt="Screenshot 2023-08-30 at 14 17 19" src="https://github.com/mui/mui-toolpad/assets/3165635/61d3a11c-dd0b-455f-81cd-90a21b63168b">

### Examples 🌈

- Metabase

<img width="368" alt="Screenshot 2023-08-12 at 20 33 03" src="https://github.com/mui/mui-private/assets/3165635/a63fb82d-5492-460a-a422-e597d77d9dd0">

### Motivation 🔦

Less code to write. For now, I will stick to using dayjs: https://github.com/mui/mui-private/blob/c5f0a6288cbbd052cee7f141d2f117bc186ece6a/tools-private/toolpad/resources/invoice.ts#L77

```jsx
    invoice_date: dayjs(row.invoice_date).format('MMMM D, YYYY'),
```

It's a continuation of #2371.

**Comment by Janpot** [comment]
Taking an initial stab at it in https://github.com/mui/mui-toolpad/pull/2589
