### ISSUE TITLE
[charts] The skeleton used when loading feels off

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2602]
### Steps to reproduce 🕹

Steps:

1. Open https://tools-public.mui.com/prod/pages/9r8fshsf

### Current behavior 😯

A big grey flash.

https://github.com/mui/mui-toolpad/assets/3165635/075701ae-5e04-4148-9809-0769ec30d23c

https://mui.com/material-ui/react-skeleton/ wasn't designed to be used with large surface area.

### Context 🔦

https://github.com/mui/mui-x/issues/10194

### Your environment 🌎

v0.1.24

**Comment by apedroferreira** [comment]
Ok, I thought it could still look fine and more consistent with a Skeleton after having discussed https://github.com/mui/mui-toolpad/pull/2400#discussion_r1286826017 but you're right.
Let's revert back to a spinner.

**Comment by Janpot** [comment]
let's move the image to a spinner as well then?

**Comment by apedroferreira** [comment]
> let's move the image component to a spinner as well then?

There have been no complaints about the image and images load a bit differently, so maybe it's fine to keep the skeleton for them?
