### ISSUE TITLE
In HTTP query POST call, the binding button of body is hidden by default

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2623]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://github.com/mui/mui-toolpad/assets/92228082/349b9efb-3f44-4923-b47c-376975908b8f

Also, as discussed on call in scenarios like this we can bring the binding button into the view by aligning it to the top section of the adjacent box.

**Comment by Janpot** [comment]
A recent change has made the top panel not scrollable. I think we can fix that for the scope of this issue? A redesign of the whole query editor is already on the roadmap.

**Comment by prakhargupta1** [comment]
Fixed in the new UI.

<img width="977" alt="Screenshot 2024-03-12 at 2 35 32 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/86621428-ad41-4956-a30c-67524ba51df1">
