### ISSUE TITLE
No quick way to ask for help from the docs

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2624]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In case a user needs quick help on Toolpad docs, currently there is no way to chat with the team. Generally, there is a chatbot. Given we have Discord at this moment, it would be good if we could show an inon that guides them to Discord.
We should show it on all pages, so maybe on the left sidebar?

SImilary, we can also show it inside Toolpad from the help menu:
<img width="280" alt="Screenshot 2023-09-04 at 4 37 04 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/56a43a83-e1a2-4761-903d-316ccd633698">

Note: There is an option Unknown in the current menu. The screenshot is from: "^0.1.26"

**Comment by Janpot** [comment]
I feel strongly against adding a dedicated chat as for an open source product we shouldn't create private channels with the user unless it's about sensitive data. We'd be investing time in support where no other users would benefit from.

I'm all for guiding them better to the existing channels, discord, stackoveflow, github issues

**Comment by prakhargupta1** [comment]
> I feel strongly against adding a dedicated chat as for an open source product we shouldn't create private channels with the user unless it's about sensitive data. 

Completely agree! Public discussions on Discord, StackOverflow, GitHub should be ideal.

**Comment by prakhargupta1** [comment]
1. Let's link https://mui.com/toolpad/support/support/
from a Support menu in this menu.
2. Remove the **Unknown** item
