### ISSUE TITLE
[docs] Content idea: How MUI uses Toolpad

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2683]
I believe we could write a piece of content on how MUI depends on Toolpad. I'm opening this issue to test the idea a bit. We could cover https://tools-public.mui.com/ or some of the private apps we have.

### Examples

- https://www.notion.so/blog/how-notion-uses-notion
- https://retool.com/blog/retool-for-critical-sales-processes/

**Comment by prakhargupta1** [comment]
Done. https://mui.com/blog/toolpad-use-cases/
