### ISSUE TITLE
Show query parameter in the query path automatically

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2686]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In HTTP request, after setting up a query parameter I am required to bind it to the query using the binding editor as mentioned [here](https://mui.com/toolpad/concepts/http-requests/#parameters)

It would be better if we could keep it simple and add parameter to the path on our own. 

### Examples 🌈

Retool:

https://github.com/mui/mui-toolpad/assets/92228082/2a03e122-29a5-405d-b1d2-5c32d1b6257a

**Comment by prakhargupta1** [comment]
I was looking to add params like `?param1=value1` and URL parameters is how I should do it to avoid manually appending them to the query.
But then, the concept of parameters is quite straightforward in retool as it allows doing it inline using mustache operator. It is not a blocker, just an input on reducing steps.

**Comment by JerryWu1234** [comment]
When we set up a parameter, it will be appended to the URL.
I guess this is what you want to do.
I think I can try it

**Comment by JerryWu1234** [comment]
can this issue assign me?

**Comment by prakhargupta1** [comment]
@JerryWu1234 Thanks for checking it out. We can look into this one later, as it is an enhancement.

**Comment by JerryWu1234** [comment]
@prakhargupta1 I saw this label was from new feature to status:waiting for maintainer. So everything is ready ?

**Comment by prakhargupta1** [comment]
I am closing this for now as it is not a blocker; we can see if it pops up later.
