### ISSUE TITLE
create-toolpad-app doesn't expand the home folder

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2704]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.  run `yarn create toolpad-app ~/Desktop/my-app` from any folder

### Current behavior 😯

An app is created in `$PWD/Desktop/my-app`

### Expected behavior 🤔

An app is created in `$HOME/Desktop/my-app`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: Not Found
    Safari: 16.6
```
</details>

**Comment by JerryWu1234** [comment]
@Janpot I saw you finish this Bug . righ?

**Comment by Janpot** [comment]
I fixed the handling of absolute paths (i.e. starts with `/`), but not for paths relative to the home folder (starts with `~`).

In node it can be found with 

```tsx
import * as os from 'os';
console.log(os.homedir());
```
We can detect whether the path starts with `~` and in that case resolve it form the homedir.

**Comment by JerryWu1234** [comment]
I got it.. I will put into my collection, and fix it late .

**Comment by JerryWu1234** [comment]
@Janpot don't forget to close this issue
