### ISSUE TITLE
Component: Password display

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2737]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

To allow users to create password fields, Toolpad should provide either a password input, or a mode on the TextField to mask the content.

### benchmark

* retool: has both password input and text input
* dynaboard: has both password input and text input as well as a password mode on the text input
* appsmith: has a text input with password mode

**Comment by apedroferreira** [comment]
My first thought was that just a "secret" mode or something in the text input component might be enough - depends on how much specific functionality we think we could add for passwords that a regular text input won't have.

**Comment by Kirera-Wainaina** [comment]
What about using a `select` component in the component properties settings? A user gets to choose the type of input: `password` or `text`? With the default being `text`

![password-select-slot](https://github.com/mui/mui-toolpad/assets/52700465/84cf067b-a078-46c4-9fe0-d4c444cb26e4)

**Comment by Kirera-Wainaina** [comment]
I'll start working on it.
