### ISSUE TITLE
Allow setting a default value in autocomplete component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2864]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Like other components, I should be able to set a [default value](https://mui.com/material-ui/api/autocomplete/#Autocomplete-prop-defaultValue) in autocomplete.

**Comment by JerryWu1234** [comment]
let me try.this bug

**Comment by JerryWu1234** [comment]
@Janpot maybe should close this pr
