### ISSUE TITLE
Canvas overlay doesn't update after resize

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2865]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. select an element in the canvas
2. resize the canvas

### Current behavior 😯

https://github.com/mui/mui-toolpad/assets/2109932/b87930e4-dd27-48ab-82c7-d824b0236142

The canvas overlay doesn't update

### Expected behavior 🤔

It should update the size of the node hud.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Janpot** [comment]
I bissected the commits on master and the issue seems to have been introduced in https://github.com/mui/mui-toolpad/pull/2760

**Comment by apedroferreira** [comment]
I had a fix here https://github.com/mui/mui-toolpad/pull/2818, but I guess your suggestion is probably better, I hadn't realized this was a recent regression.
