### ISSUE TITLE
Add support for SSO with Google

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#2873]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

**Comment by JerryWu1234** [comment]
I want to try this,
but I don't sure there is whether any information I missed.

**Comment by Janpot** [comment]
@JerryWu1234 This will likely be picked up by someone on the Toolpad team itself. There are too many details we need to solve internally on how we will implement a split in paid vs. core features.

**Comment by prakhargupta1** [comment]
This is now supported. Docs: https://mui.com/toolpad/studio/concepts/authentication/#google
