### ISSUE TITLE
Support server-side row creation

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#2888]
Add CRUD operations to the Toolpad [data providers](https://mui.com/toolpad/concepts/data-providers/).

The data provider interface can be augmented with a `createRecord(fields)` method. When available the frontend component should automatically provide a create button in the data grid which adds an empty editable row and a commit button that calls the `createRecord` in the backend with the new fields

**Comment by JerryWu1234** [comment]
do you have more details?
I want to take this PR

**Comment by Janpot** [comment]
We just merged https://github.com/mui/mui-toolpad/pull/3001. Creation will be similar.

**Comment by JerryWu1234** [comment]
> We just merged #3001. Creation will be similar.

I got it.
let me try it.

**Comment by JerryWu1234** [comment]
@Janpot this can assign me ? let me easy to find out when i want to find this issue

**Comment by Janpot** [comment]
@JerryWu1234 I'll be picking this up myself
