### ISSUE TITLE
Implement pro features flag with license key

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#3113]
### Duplicates

- [X] I have searched the existing issues

### Summary

After adding RBAC we can use it as the first pro feature of Toolpad.

**Features needed:**
- Provide license key in environment variable to be able to use pro features. Use same method as MUI X.
- Add a property to `application.yml` to enable/disable pro features + an indicator in the UI of the current value of this property.
- Show a watermark over Toolpad application if pro features are enabled but license key is not provided.
- Hide pro features in the UI if pro features are not enabled.
- If a Toolpad application is started with pro features being used in the `.yml` configurations but pro features are not enabled, block application from starting and show message telling which keys to remove or to enable pro features.
- Document this.

### Examples

MUI X follows a similar model.

### Motivation

Adding paid features to Toolpad.

**Comment by Janpot** [comment]
Have you tried with [`[dependenciesMeta.injected](https://pnpm.io/package_json#dependenciesmetainjected)`](https://github.com/pnpm/pnpm/issues/3102)?

**Comment by apedroferreira** [comment]
> Have you tried with [`dependenciesMeta.injected`](https://github.com/pnpm/pnpm/issues/3102)?

Did you mean this as an answer in https://github.com/mui/mui-toolpad/pull/3114 instead?
I can try it.

**Comment by apedroferreira** [comment]
@bharatkashyap I think nothing here https://github.com/mui/mui-toolpad/pull/3077 should be needed before this, as in `master` the schema already has the properties for roles and page roles in `authorization.yml`, but let me know if anything from there is needed or needs to be clearer!

**Comment by Janpot** [comment]
> Did you mean this as an answer in https://github.com/mui/mui-toolpad/pull/3114 instead?

Yes thanks, not sure how I got this mixed up

As for this issue. I believe we can start with implementing the `plan` flag in the config which if set to something else than `'free' | undefined`:
* shows a warning that makes you as a user aware that you're potentially using features which we don't plan to keep free or MIT forever, and if you're uncomfortable with it, you should reset the flag
* enables UI and features that we intend to be pro features.

if unset:
* block Toolpad apps from starting up if any pro features are detected in the YAML.
* (future) show CTAs in the UI to swicth to a plan.

We can implement the actual license and watermark in a separate effort. Perhaps after we've implemented a few more auth providers or pro features?

**Comment by apedroferreira** [comment]
> We can implement the actual license and watermark in a separate effort. Perhaps after we've implemented a few more auth providers or pro features?

Sounds good, I guess the paid features wouldn't be very deep for now so we can start with that.

**Comment by bharatkashyap** [comment]
@

> > Did you mean this as an answer in #3114 instead?
> 
> Yes thanks, not sure how I got this mixed up
> 
> As for this issue. I believe we can start with implementing the `plan` flag in the config which if set to something else than `'free' | undefined`:
> 
> * shows a warning that makes you as a user aware that you're potentially using features which we don't plan to keep free or MIT forever, and if you're uncomfortable with it, you should reset the flag
> * enables UI and features that we intend to be pro features.
> 
> if unset:
> 
> * block Toolpad apps from starting up if any pro features are detected in the YAML.
> * (future) show CTAs in the UI to swicth to a plan.
> 
> We can implement the actual license and watermark in a separate effort. Perhaps after we've implemented a few more auth providers or pro features?

@janpot Should the `plan` flag be written to the config automatically if the user uses a paid feature?

**Comment by Janpot** [comment]
no, the app should not start
