### ISSUE TITLE
[docs] Getting Started/ First App is not working?

### ISSUE THREAD

**Issue by TSRGSG** [mui/mui-toolpad#3118]
### Related page

https://mui.com/toolpad/getting-started/first-app/

### Kind of issue

Broken demo

### Issue description

I was looking for trying the getting started demo and it appears that starting from the imageQuery section it does not work. I tries both locally and using https://stackblitz.com/

![image](https://github.com/mui/mui-toolpad/assets/32558834/b0a2425c-a8fe-4a9b-8d18-4011777b281f)

### Context

I want to try to complete the getting started demo.

**Search keywords**: getting started, first app, dog app

**Comment by bharatkashyap** [comment]
Correct - this is due to the documentation code snippet having a `;` which is causing the query to fail.  Removing that fixes this issue. I'll fix the instructions - thanks for the report :)
