### ISSUE TITLE
Interfacing with external libraries

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#314]
Allow importing and using npm modules or external dependencies and then use them in databinding.
We could natively support some libraries like https://momentjs.com/ in Toolpad.

Additionally, we will have to allow users to use the library of their choice.

### Examples 🌈

- https://docs.appsmith.com/v/v1.2/core-concepts/connecting-ui-and-logic/working-with-js-libraries
- https://docs.retool.com/docs/custom-js-code

### Motivation 🔦
For Toolpad to be close to pro-code, this is highly needed feature.

### Risks
1. It is a good feature but has security risks.
2. Isolation would be required as there can be scenarios where the older/same version of  a library is being imported which is not allowed.

**Comment by Janpot** [comment]
I propose we start by allowing a user to write a single javascript module that we import on the client-side:
* a module has exports that will become available either as global variables in the binding editor, or we under a certain key.
* Users can import external modules from ESM cdns, like https://esm.sh/
* Users can export whatever they want and use it in bindings
* We won't allow native modules on node.js

**Comment by oliviertassinari** [comment]
I think that we could take the notion of ETL from our data engineers. It could make sense for us to have transformers. I assume they would need to be pure functions, and likely only have access to their parameters.
