### ISSUE TITLE
[docs] how to host toolpad app production version on iisnode.

### ISSUE THREAD

**Issue by teowave** [mui/mui-toolpad#3153]
### Related page

https://mui.com/toolpad/how-to-guides/

### Kind of issue

Missing information

### Issue description

I have produced an app in mui-toolpad, and I am trying to deploy it alongside another app under iis using iisnode. There seems to be no documentation about how to do this.

So my question is: Do you have any suggestions on how to host the production version of the mui-toolpad app on iisnode? I am using IIS on Windows 2022 server, with iisnode already installed. I am running some react pages already through node.js and iisnode directly, in parallel with the legacy c#/MVC app, and it works well. But with mui-toolpad there seem to be a few paradigms that escape me

Grateful for any pointers

All the best

### Context

I am trying to run a toolpad app under iisnode

**Search keywords**: iisnode, iis

**Comment by Janpot** [comment]
I'm not really familiar with iis and iisnode. But I believe your best bet would be to run Toolpad as a request handler in your node.js webserver. See https://github.com/mui/mui-toolpad/blob/master/examples/custom-server/index.mjs

What does your node.js sebserver look like? Is it using express.js?

**Comment by teowave** [comment]
Hi, Jan - thank you for your very prompt reply. 

We are using express.js indeed in our node webserver. 

Thank you for the provided link, it is indeed very helpful, and its linked description as to how it works at https://mui.com/toolpad/concepts/custom-server/ 

Maybe a link to this page https://mui.com/toolpad/concepts/custom-server/ could be added in the documentation in the deployment section, it should save a lot of looking around 

We should be able to deploy it now, thank you for your help

**Comment by Janpot** [comment]
@teowave Were you able to deploy?

I'm adding a small page on our docs about issnode with some pointers: https://github.com/mui/mui-toolpad/pull/3155

**Comment by teowave** [comment]
@Janpot - thank you for following this up with us

We have tried to deploy all day today, we didn't quite manage, Ecmascript gets in the way big time, iisnode requires commonjs

I have tried to run your example but got this error.
Application has thrown an uncaught exception and is terminated:
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\WebSites\*\TOOLPAD-CLIENT\toolpad\server.mjs not supported.
Instead change the require of C:\WebSites\*\TOOLPAD-CLIENT\toolpad\server.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Program Files\iisnode\interceptor.js:210:1)

To resolve this issue i am trying to transpile  my code using typescript but i am facing this error when i try to load 'createHandler' function.
Cannot find module '@mui/toolpad' or its corresponding type declarations.

Alternatively i try to use babel with @babel/plugin-transform-modules-commonjs plugin and get this error on running app.
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Work\*\my-toolpad-app\node_modules\get-port\index.js from C:\Work\*\my-toolpad-app\node_modules\@mui\toolpad\dist\exports\index.js not supported.
Instead change the require of C:\Work\*\my-toolpad-app\node_modules\get-port\index.js in C:\Work\*\my-toolpad-app\node_modules\@mui\toolpad\dist\exports\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Work\*\my-toolpad-app\node_modules\@mui\toolpad\dist\exports\index.js:41:31)
    at Object.<anonymous> (C:\Work\*\my-toolpad-app\dist\server.js:3:42) {
  code: 'ERR_REQUIRE_ESM'

Any help would be appreciated

**Comment by Janpot** [comment]
@teowave In terms of Node.js support, we follow the [maintenance line of Node.js](https://nodejs.org/en/about/previous-releases). Meaning that we support Node.js 18 and up. Toolpad seems to work on Node.js 16 but we're not actively trying to support it. Which version of Node.js are you trying to run on?

**Comment by teowave** [comment]
Machine that uses iisnode has node v 20, Dev machine thats used for building has node v 18

**Comment by Janpot** [comment]
are you transpiling your express server. e.g. from typescript?
