### ISSUE TITLE
Ability to rename nodes

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#3168]
### Summary

We used  to be able to rename nodes, it seems that we can't anymore

<img src="https://github.com/mui/mui-toolpad/assets/3165635/944984a4-80f9-454d-b27b-6f7b4046e57a" width="252">

### Motivation

I noticed this in https://github.com/oliviertassinari/mui-olivier-tools/pull/6. I wasn't should about using `select.value` for my binding, I was going to rename the node from `select` to `org`.

*BTW, it was super fast to build, I guess if I had used Pro-code, it would have been as fast, but for a person who doesn't know a lot about frontend but still has an engineer mind, damn 👌.*

**Search keywords**: rename nodes

**Comment by apedroferreira** [comment]
You can still do it by double-clicking on the note in that list, right?
I guess we used to have the option too on the right, not sure when we removed it or if there was a reason to...

**Comment by oliviertassinari** [comment]
Oh, I didn't realize

**Comment by Janpot** [comment]
Let's add a menu to the tree items with rename and delete actions inside? The menu can be hidden until the item is hovered.

**Comment by apedroferreira** [comment]
Don't we already have a menu?

https://github.com/mui/mui-toolpad/assets/10789765/ba8f2d19-01e9-47da-b6fe-8e3bd1b2fdef

Maybe showing it on hover only isn't as obvious as it needs to be?
