### ISSUE TITLE
doesn't work on node.js 18

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3172]
### Steps to reproduce

Steps:
1. `nvm use 18`
2. `NODE_ENV=test TOOLPAD_AUTH_SECRET=123 pnpm toolpad dev test/integration/auth/fixture-domain/toolpad --dev`
3. open http://localhost:3000/prod

### Current behavior

Toolpad goes into some sort of loop showing failures in the console like:

```
ReferenceError: crypto is not defined
```

### Expected behavior

2 things:
- this should never go into a loop, even if there is a backend error
- Toolpad needs to work on Node.js 18

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: auth node 18

**Comment by apedroferreira** [comment]
Thanks, I'll take a look at it asap.
