### ISSUE TITLE
[sheets] `files.list` API response caching strategy

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#321]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

The current query keys for the `FILES_LIST` query is the selected spreadsheetId and the spreadsheet query - but this throws an error if the user selects a sheet that was deleted in the interval. What should the caching strategy of this API be?

**Comment by Janpot** [comment]
The execution of the API itself can just throw error if the spreadsheet doesn't exist anymore.
For the autocomplete, I guess we can use a [free solo](https://mui.com/material-ui/react-autocomplete/#free-solo) and show  the error somewhere if the `FILES_LIST` fetch fails (perhaps [in the input](https://mui.com/material-ui/react-text-field/#validation))
I'm not sure we should solve this with caching, I think the query input should just be able to deal with any situation that can occur.

**Comment by bharatkashyap** [comment]
I think I didn't explain properly: the issue is that the cached query (via React Query) contains a response that includes a deleted file. Should an error be thrown if the user selects that file and a refetch triggered?

**Comment by Janpot** [comment]
if we detect that the user selected a file that's deleted, we can refetch the files query and deselect again. not sure we need to show an error somewhere. at least not in a blocking way.

**Comment by bharatkashyap** [comment]
The current behaviour seems to be able to handle this situation:

![Image](https://user-images.githubusercontent.com/19550456/170694075-c89c3690-9578-4d81-aec9-67f86edb1159.png)
