### ISSUE TITLE
For a logged in user, the avatar icon overlaps with the UI

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3212]
### Steps to reproduce

Log in to tools-private, browse pages, notice the overlap.

Introduced after https://github.com/mui/mui-private/pull/376

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: authentication

**Comment by apedroferreira** [comment]
I guess we might need some kind of appbar on top, I'll try to find a good solution.
