### ISSUE TITLE
Module resolution fails in resources/components folders

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3213]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Create a component and try to `import { createComponent } from '@mui/toolpad/browser'`

### Current behavior

Errors in vscode

<img width="592" alt="Screenshot 2024-02-14 at 12 26 49" src="https://github.com/mui/mui-toolpad/assets/2109932/048a7047-c962-4055-a0cf-87f73b894d35">

### Expected behavior

No errors shown in vscode, intellisense works for Toolpad types

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: resources components module resolution

**Comment by prakhargupta1** [comment]
It's fixed.
