### ISSUE TITLE
Share selected row IDs between data providers

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#3279]
### Summary

When using multiple Data Grids with data providers attached to each, make it possible to share the `id` of a selected row on the first grid in the `getRecords` method of the data provider of the second.

### Examples

```js
export default createDataProvider({
  
  async getRecords({id, paginationModel: { start = 0, pageSize=3 } }) {
    console.log("id",id) // Selected row id of the first grid


          
          const response = await axios.get(`end-point/${id}?api_key=...`,{
        headers: {
          'Content-Type': 'application/json',
         }
      });
 ```

### Motivation

From @VitaliiDubinin:  
> The idea is to have possibility to choose object in the first table, then when I select any object in the first table it will show its nested object in the second table and give me possibilities to make changes in the nested objects by dataProvider.

**Search keywords**: data provider

**Comment by Janpot** [comment]
I believe this would be solved by https://github.com/mui/mui-toolpad/issues/3052.
When a data provider lives on the page the same way a query does, we could allow binding page state to its filter.

**Comment by bharatkashyap** [comment]
Agreed @Janpot - I'll close this as a duplicate
