### ISSUE TITLE
HTTP method OPTIONS is needed for HAL REST API's integration

### ISSUE THREAD

**Issue by dsingh45** [mui/mui-toolpad#3307]
### Summary

All CRUD methods are already available for creating a Query, however OPTIONS method is also required while integrating with HAL (hypertext application language) supported REST APIs. Generally, OPTIONS method is specific to preflight browser requests but for HAL supported, self documenting REST APIs, OPTIONS response carries hyper-schema of the resource.

**Search keywords**: OPTIONS HTTP Method for HAL REST API

**Comment by Janpot** [comment]
Sure, we can support OPTIONS: https://github.com/mui/mui-toolpad/pull/3308

**Comment by Janpot** [comment]
Will be included in the upcoming release
