### ISSUE TITLE
[DataGrid] Support row grouping and aggregation

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3331]
### Summary

The Toolpad built-in DataGrid component should support [row grouping](https://mui.com/x/react-data-grid/row-grouping/).

* We should add a checkbox for "groupable" in the column definition UI, disabled? by default.
* We should add a checkbox for "aggregable" in the column definition UI, disabled? by default

Column definition UI:
<img width="905" alt="Screenshot 2024-04-02 at 10 53 37 AM" src="https://github.com/mui/mui-toolpad/assets/92228082/cc5a5c85-b9dc-4f83-9ed7-c38fb0699afb">

**Search keywords**: datagrid row grouping

**Comment by b4s36t4** [comment]
Would love to work on this.

> What type of `control` prop I should be using to render the `names` of provided columns and how should I make the control multi-select. Should I need to be creating a new custom component here?

I took `rowGrouping` as the `argType` with `default` as `[]` i.e empty array but when I tried to render it `rowGrouping` is passed `empty string` is there any issue with assigning default value or somewhere it's getting overridden?

<img width="1241" alt="Screenshot 2024-03-31 at 1 25 54 AM" src="https://github.com/mui/mui-toolpad/assets/59088937/0b1410aa-ca34-46e7-965c-5b40ad32b313">

My current progress is, I was able to add the prop i.e `Row Group model` which accept an array of string and passing it to `DatagridPro` component.
