### ISSUE TITLE
Elements in the canvas should scroll into view after selection

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3338]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Create a page with several items under the fold
2. Select items under the fold in the hierarchy explorer
3.

### Current behavior

https://github.com/mui/mui-toolpad/assets/2109932/05ec0625-5247-4078-9a15-0b5104d9c7d8

It looks like no item was selected

### Expected behavior

selected items should scroll into view

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: scroll selection

**Comment by b4s36t4** [comment]
https://github.com/mui/mui-toolpad/assets/59088937/0b8699fa-d446-4cfc-91df-bf9ca8ce5678

If I'm not too late or too early, spend some time on implementing this, would love to see this get's merged :)

cc: @Janpot

**Comment by Janpot** [comment]
feel free to open a PR, I think it shouldn't animate

**Comment by b4s36t4** [comment]
@Janpot I have linked the PR, please review whenever possible.
