### ISSUE TITLE
Update Header UI to show GitHub stars

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [mui/mui-toolpad#3371]
### Summary

This feature fetches the number of stars from your GitHub repository using the GitHub API. Upon loading the webpage, JavaScript retrieves the star count and dynamically updates it beside the GitHub icon on the UI header. This ensures visitors can easily see the popularity of your repository at a glance, as the displayed count always reflects the current number of stars.

### Motivation

The purpose of this feature is to provide visitors with immediate visibility into the popularity of our GitHub repository. By fetching the number of stars using the GitHub API and dynamically updating it beside the GitHub icon

**Search keywords**: GitHub Star

**Comment by bharatkashyap** [comment]
@gurjeetsinghvirdee Is this a feature request for the Toolpad editor? I don't see how, but please elaborate on what this issue is about.

**Comment by bharatkashyap** [comment]
@gurjeetsinghvirdee We have a star count on the landing page already on https://mui.com/toolpad. Changing the GitHub icon in the header would require changes to the [`AppHeader`](https://github.com/mui/material-ui/blob/next/docs/src/layouts/AppHeader.tsx) which is shared across all product websites; so far we haven't considered adding a star count to header enough of a need so I would advise against creating an issue for this on the Material UI repo.

**Comment by bharatkashyap** [comment]
@gurjeetsinghvirdee If your intent was to add a functionality to Toolpad where the built application can include a functionality to fetch and display GitHub stars for any repository, please let me know and I'll reopen this issue as a request to be able to modify the header UI of applications built with Toolpad

**Comment by gurjeetsinghvirdee** [comment]
@bharatkashyap 
 I'd be happy to work on this. 
Could you please assign me the task!
