### ISSUE TITLE
Install Toolpad Studio in an existing project

### ISSUE THREAD

**Issue by MetamericDevin** [mui/mui-toolpad#3385]
### Related page

https://next.mui.com/toolpad/studio/getting-started/installation/

### Kind of issue

Missing information

### Issue description

Npm install for existing project is pnpm install -S @toolpad/studio
should be npm install -S @toolpad/studio

### Context

help avoid confusion

**Search keywords**: npm install

**Comment by bharatkashyap** [comment]
- This was fixed by https://github.com/mui/mui-toolpad/pull/3323 and will be fixed in the latest release of the docs today
