### ISSUE TITLE
[docs] Links are missing a trailing slash in server rendered pages

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#3401]
### Steps to reproduce

https://github.com/mui/mui-toolpad/pull/3301#issuecomment-2054213837

**Comment by Janpot** [comment]
I know we've discussed it before, but I can you remind me again why we use `trailingSlash`? I'd like to document it in the [configuration](https://github.com/mui/material-ui/blob/c353fb3048d00979a7aea6b6b2f4901354a26a02/docs/nextConfigDocsInfra.js#L51). Having worked a lot on this in the next.js codebase, it feels a bit to me like a neglected feature and I'd expect it to regress regularly.

**Comment by oliviertassinari** [comment]
Ok, origin found: https://github.com/mui/material-ui/pull/16705. We started to use `trailingSlash` precisely to avoid introducing changes to the URLs. 

Points added to https://www.notion.so/mui-org/docs-infra-Change-docs-domain-0ce329e7ebc34aba8fbf4f3c5e13eb5d?pvs=4#275627e520784cf4b77733f7805465d9 so we don't forget about this.
