### ISSUE TITLE
react-pages example fails to load

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3423]
### Steps to reproduce

Link to live example: https://github.com/mui/mui-toolpad/tree/master/examples/react-pages

Steps:
1. Try running it.
2. It throws the below error:

<img width="1183" alt="Screenshot 2024-04-19 at 6 43 47 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/c19b5818-08cc-4624-8c7b-b03b2d22da91">

**Search keywords**: react-pages

**Comment by Janpot** [comment]
I think we should discontinue this experimental feature
