### ISSUE TITLE
Improve component discoverability

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#344]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add an input component

### Examples 🌈

The input is one of the most-used components, in MUI and for instance in https://www.youtube.com/watch?v=7GgBnbHF8Rg, is pivotal to be able to search inside a data grid or to create forms.

<img width="317" alt="Screenshot 2022-04-30 at 22 53 41" src="https://user-images.githubusercontent.com/3165635/166122298-a695b4bc-4b77-4c7b-b0c3-ba6ff04e9235.png">

### Motivation 🔦

I'm working on a support tool for MUI X to decode the license keys. It would have been great to have access to this component.

**Comment by Janpot** [comment]
I believe the `TextField` component already does this. If that's the case, then this is probably a discoverability issue. We could rename it to "Input" and/or work on the design of the component catalog?
If not, what would the `Input` component do that the `TextField` doesn't?

**Comment by oliviertassinari** [comment]
Ah right, I didn't thought about searching for the the text field 🙃. We will need a search to find components, I believe, e.g. like Figma is doing.

**Comment by Janpot** [comment]
I also think it could help to group components as the catalog grows. Like for instance in the docs: inputs together, layout together,...

**Comment by oliviertassinari** [comment]
And of course, illustrations 😁. I'm adding the UX label as I think we need to involve a designer on this issue

<img width="520" alt="Screenshot 2022-05-01 at 18 14 19" src="https://user-images.githubusercontent.com/3165635/166155228-24439d3c-fa77-41db-93e5-e21ee1f7a804.png">

**Comment by prakhargupta1** [comment]
Same as https://github.com/mui/mui-toolpad/issues/344
