### ISSUE TITLE
Allow to modify the name of custom components

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#345]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Once a custom component is created, it can't be renamed.

### Examples 🌈

It can only be deleted

<img width="254" alt="Screenshot 2022-04-30 at 22 58 58" src="https://user-images.githubusercontent.com/3165635/166122463-e9c447e0-a338-425e-9dde-ee1bd891feba.png">

### Motivation 🔦

I changed my mind about how the component should be named. I thought that TextField would be great, but then, it conflicts with TextField from Material UI.

**Comment by oliviertassinari** [comment]
Haha, quick and dirty fix, niice

<img width="1208" alt="Screenshot 2022-05-01 at 16 02 37" src="https://user-images.githubusercontent.com/3165635/166149319-1c4c7b1a-e9a9-46f7-8bef-7e64b037bd8f.png">

**Comment by Janpot** [comment]
We already have a component that updates the name of any arbitrary object in the application DOM. I've just dropped it in for the code components, we can fix the UX separately.
