### ISSUE TITLE
Unclear UX of 'Open' button in custom functions editor

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3462]
### Steps to reproduce

When no function is present, Clicking 'Open' button shows a resource file instead of creating and opening the default function.

Also, given we have the open code icon against each function, maybe we can completely remove the Open button?

### Current behavior

https://github.com/mui/mui-toolpad/assets/92228082/6be85623-d2ca-4ece-acf3-8483376553e1

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: open button

**Comment by prakhargupta1** [comment]
A UI suggestion on the functions editor. We could bring out the drop-down UI, remove the Open button, and have radio buttons to choose the function:

<img width="820" alt="Screenshot 2024-04-26 at 8 02 27 PM" src="https://github.com/mui/mui-toolpad/assets/92228082/fd512af4-a2a4-4896-b3d4-6c84828db785">

**Comment by Janpot** [comment]
I don't think radio buttons are the right UX here, but a selectable+filterable list makes sense imo. a preview of the code file as well.
