### ISSUE TITLE
Sync multiple tabs opening the same page

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#348]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When working on an application, it's possible to open two tabs for the same app. However, changes done to one tab are not kept in sync with the other. We take the risk to lose previous work if saving changes from a tab that is behind.

### Examples 🌈

Codesandbox keeps two tabs in sync. This feature request might be part of a collaboration feature, but it might also be different here, it's about a single user with multiple tabs.

As a quick workaround, we could imagine only accepting the save events that are coming on top of the latest version that is stored in the DB, if the app detects an outdated save attempt, he could then reload the tab.

**Comment by prakhargupta1** [comment]
@Janpot Can this be closed now? It works now.
