### ISSUE TITLE
Toolpad is UI is slow and freezes when trying to add a filePicker component

### ISSUE THREAD

**Issue by Zenith201** [mui/mui-toolpad#3528]
### Steps to reproduce

Link to live example: (required)

Steps:
1.Run the editor
2.Add FilePicker
3.App will freeze 

### Current behavior

Freezes whole page

### Expected behavior

FilePicker added

### Context

Add FilePicker component

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: slow toolpad ui freezing

**Comment by Janpot** [comment]
@Zenith201 I can't reproduce this. would you mind running `npx @mui/envinfo` and paste the output here?
