### ISSUE TITLE
Id column not assigned to a datagrid.

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3553]
### Steps to reproduce

I was unable to use the data provider updateRecords method as it could not pick the selected row's ID.
It may have happened when I changed the underlying data source even though I refreshed the columns.

Video showing a same data provider code resulting in a different response for the 2 grids. Notice the Id field drop-down:

https://github.com/mui/mui-toolpad/assets/92228082/f317fe16-213a-4ec6-97be-6755e274cd1b

**Search keywords**: id column

**Comment by Janpot** [comment]
Please add a reproduction, otherwise we won't be able to debug this problem.
