### ISSUE TITLE
Support resizing of components

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#359]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Improve the visual editor by adding the feature to resize components through a resize handle (inputs horizontal only, data grids vertical). It should be extensible enough so that we can share the logic with other components. Bonus points if there’s a way for custom components to integrate resize handles as well.

### Motivation 🔦

Retool, Appsmith both have this option

**Comment by apedroferreira** [comment]
Closing, as basic resizing functionality has been merged.
However, even though the current resizing features are sufficient I don't think they're complete enough. All components with variable height or width should allow those properties to be resizable with handles, as well as their spacing.
I've created an issue for a refactor (https://github.com/mui/mui-toolpad/issues/712) that should make it easier to improve the resizing behavior. Will create one or 2 issues for improving the resizing of components and their spacing too.
