### ISSUE TITLE
[DashboardLayout] Add badges to navigation entries

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3608]
### Summary

I would like to be able to draw attention to certain pages by displaying a badge next to the title. Perhaps navigation entries can have a `badge` property?

### Examples

![Screenshot 2024-05-27 at 11 54 24](https://github.com/mui/mui-toolpad/assets/2109932/22388aef-c8b6-4189-91bf-ea2d917fbc42)

**Search keywords**: navigation badge

**Comment by apedroferreira** [comment]
Couldn't really find a similar feature in other products but I'm thinking we can start with something simple by adapting the MUI Badge https://mui.com/material-ui/api/badge/ in an optional `badge` property with the `badgeContent` (`just `content` in this case) and `color`.
