### ISSUE TITLE
Datafetching, serverside post-transformation

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#366]
## Problem

My API data needs shaping before it's usable on the client. I'd like to be able to have it pretransformed on the server so that I can use it in my preferred shape on the browser

## Solution

In the API editor, at the bottom, add a code editor that allows writing a transformation to be applied to the API result. This should contain a javascript function where the first parameter is the data to be transformed and it returns the transformed object. e.g.

```ts
(data) => Object.entries(data.myProperty).map((data, index) => ({ ...data, id: index }))
```

Apply this transformation serverside before sending the API response

## Note

Make sure to add this to https://github.com/mui/mui-toolpad/issues/365  if that gets implemented first

**Comment by oliviertassinari** [comment]
I don't see this feature, should we reopen? I'm looking at

<img width="1247" alt="Screenshot 2022-05-27 at 14 10 56" src="https://user-images.githubusercontent.com/3165635/170696758-97caae45-512e-4e47-9e41-b198e6b93a21.png">
