### ISSUE TITLE
[studio] Support password validation

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#3826]
Feedback received: valid password
from https://mui.com/toolpad/studio/components/text-field/#password

The users seems to be asking for the option to configure password validation. Configurations like:

Password should not contain any space. 
Password should contain at least one digit(0-9). 
Password length should be between 8 to 15 characters. 
Password should contain at least one lowercase letter(a-z). 
Password should contain at least one uppercase letter(A-Z). 
Password should contain at least one special character ( @, #, %, &, !, $, etc…).

**Search keywords**:

**Comment by apedroferreira** [comment]
This might fit into this old issue https://github.com/mui/mui-toolpad/issues/3261

**Comment by prakhargupta1** [comment]
Duplicate https://github.com/mui/mui-toolpad/issues/3261
