### ISSUE TITLE
[docs] Core landing page drawer glitch

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3827]
### Steps to reproduce

Link to live example: https://mui.com/toolpad/

Steps:
1. Go to https://mui.com/toolpad/
2. Click the menu button in the dashboard layout
3.

### Current behavior

https://github.com/user-attachments/assets/8adfef1e-1c84-4f0e-8331-5aca27cf85b5

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: landing page glitch

**Comment by apedroferreira** [comment]
It needs to use the `window` prop as it's in an iframe, I can fix it now.
