### ISSUE TITLE
[docs] Toolpad Core DashboardLayout demo improvements

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#3836]
### Related page

https://mui.com/toolpad/core/react-dashboard-layout

### Kind of issue

Other

### Issue description

As mentioned in https://github.com/mui/mui-toolpad/pull/3776, we can try improving the `DashboardLayout` component docs as follows:
- making each code preview shorter so that it doesn't take up as much scroll space, and ideally the code preview is not tall enough to be scrollable
- split each feature more in a separate demo

### Context

Improving Toolpad Core docs.

**Search keywords**: components demos dashboard layout

**Comment by oliviertassinari** [comment]
A benchmark for the docs of this: https://github.com/azouaoui-med/react-pro-sidebar.
