### ISSUE TITLE
Support entities

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#385]
Recently we implemented support for server-side [pagination](https://mui.com/toolpad/concepts/data-providers/#pagination) through the concept of [data providers](https://mui.com/toolpad/concepts/data-providers). We should extend the capabilities to also include:

1. Filtering #2886
2. Sorting #2539 
3. Row editing #2887
4. Row creation #2888 
5. Row deletion #2889 

Relates to: https://github.com/mui/mui-x/issues/8179

**Comment by prakhargupta1** [comment]
It looks essential but I am unable to visualize. Can you help me understand how it may function? Also, is there a similar concept in other low-code tools?

**Comment by JerryWu1234** [comment]
@Janpot  these problems is very suitable for me.
https://github.com/mui/mui-toolpad/issues/2539
such as this one.
Could you offer more details?

**Comment by Janpot** [comment]
@JerryWu1234 I've updated the issue and turned it into an umbrella for improvements on [Toolpad data providers](https://mui.com/toolpad/concepts/data-providers/). Did you get a chance already to try them out? The [documentation page](https://mui.com/toolpad/concepts/data-providers/) should get you right on track. We would like to closely align this feature with [MUI X](https://github.com/mui/mui-x/issues/8179) in the near future and add filtering/sorting/... capabilities.

**Comment by JerryWu1234** [comment]
>Did you get a chance already to try them out?

I didn't, but I developed the pagination function and filtering before.
