### ISSUE TITLE
Source control with GitHub

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#389]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Make it possible to use GitHub as the source of truth for the deployment of a Toolpad app. GitLab and Bitbucket support could come later on. This would be very similar to how pro-code works when pushing to a branch that Netlify/Vercel/Cloudflare Pages then deploys. In practice, it means that changes done in the Toolpad UI would lead to opening a PR on GitHub. The PR would have its own live preview.

### Examples 🌈

- https://docs.retool.com/docs/source-control
- https://docs.appsmith.com/core-concepts/git-sync
- https://retool.com/blog/git-branching-with-source-control/
- https://docs.flutterflow.io/settings-and-integrations/integrations/github

### Motivation 🔦

If we do build this feature, then we could wonder: why not build a version of Toolpad that can be run on local files, alongside a pro-code codebase?

**Comment by prakhargupta1** [comment]
Q) Should we keep Git sync to work at App level or workspace level ? (Workspace: Collection of Apps)

Keeping it to App level would mean that an App maps to a Repository. 
Pros:
1. There would be more than 1 files in the codebase, so a dedicated space for clarity would be good.
2. Not all Apps in a workspace would have the need to be Git synced.
Cons:
It will lead to many repos that may become unmanageble?

A user should be able to do the following:
1. Allow creating a Repo from Toolpad App
2. Allow creating a branch in the repo
3. Allow commiting from Toolpad
4. View branch wise previews
5. Merging branches
6. Resolving conflicts during merge ?
7. Opening and merging a PR



Appsmith Gitsync feature in action: https://www.youtube.com/watch?v=emdZaG-tzgw

**Comment by prakhargupta1** [comment]
Closing it as with the pro-code version of Toolpad source control with GitHub (or others) is natural.
