### ISSUE TITLE
Push pro-code components to Toolpad

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#390]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Allow developers to extend Toolpad to use their own components. It's almost the same as #362 but this issue is about pro-code integration, local dev environment 

### Examples 🌈

- https://docs.plasmic.app/learn/code-components/
- https://www.makeswift.com/docs/guides/manual-setup
- https://supabase.com/edge-functions
- https://www.builder.io/c/docs/getting-started
- https://uiflow.gitbook.io/uiflow/uiflow-guides/add-custom-components-via-cli

### Motivation 🔦

 A local dev environment might be how developers prefer to work for some of the building blocks that Toolpad is made of.

**Comment by oliviertassinari** [comment]
RFC: v

**Comment by prakhargupta1** [comment]
Closing this issue, as in the new Toolpad pro-code components can be easily created in the IDE and used in local dev environment. The RFC and #362 talk about importing from GitHub and other sources.
