### ISSUE TITLE
[studio] Maximum request body size / 413 Payload Too Large

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#3902]
### Steps to reproduce

Steps:
1. Call a backend function with a payload of 630 KB

### Current behavior

<img width="740" alt="SCR-20240807-mpoa" src="https://github.com/user-attachments/assets/6fa38cc6-f802-4eb6-aadd-03b444f7e810">

### Context

I'm trying to use #1537 to improve https://www.notion.so/mui-org/DES-d648e13aa0c1468fa78622882dac6364. Tina @TinaDein  is struggling to pull the latest changes from git. So I thought maybe I could create a quick Toolpad app for it.

<img width="544" alt="SCR-20240807-mzan" src="https://github.com/user-attachments/assets/c4007c7e-eda8-4a7a-9375-1641d2e6928c">

Now, the problem seems to be that in

https://github.com/mui/mui-toolpad/blob/0112499a6ae22422c6ed6ddf8545616d9aaae35e/packages/toolpad-studio/src/server/rpc.ts#L57

we use the default `limit` value: https://expressjs.com/en/resources/middleware/body-parser.html#bodyparserjsonoptions, which is '100kb'.

In Retool: https://docs.retool.com/apps/guides/components/special-inputs/file-inputs

> The maximum size for uploaded files is 40MB.

The alternative is to use Toolpad Core for this, but it's not really a point yet where is ready to be used as I understand it. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by Janpot** [comment]
Can you try with https://pkg.csb.dev/mui/mui-toolpad/commit/4f952f42/@toolpad/studio ?

**Comment by oliviertassinari** [comment]
<img width="763" alt="SCR-20240807-nswa" src="https://github.com/user-attachments/assets/a953cd0a-d7f6-456e-8343-73c74ad2ed61">
