### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#395]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Maybe some developers would want to be able to work on Toolpad offline.

### Examples 🌈

- https://wishlist.webflow.com/ideas/DESIGNER-I-13
- https://open.spotify.com/episode/26PE83xergh7uFeXOpbsWD?si=D8ROJJGhS4SDylaMpRbzMw

**Comment by prakhargupta1** [comment]
Closing it as it is done.
