### ISSUE TITLE
Add local file support

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#398]
Complementary to https://github.com/mui/mui-toolpad/issues/395 and https://github.com/mui/mui-toolpad/issues/389
Select a file on the local file system to sync toolpad changes to instead of to the Toolpad backend. This would essentially treat Toolpad as a local file editor.

### Benchmark

Example: https://motif.land/blog/syncing-text-files-using-yjs-and-the-file-system-access-api

**Comment by oliviertassinari** [comment]
Interesting thoughts on the matter: https://twitter.com/swyx/status/1533910738942562304.

**Comment by Janpot** [comment]
That statement doesn't make much sense to me.

> Stackblitz runs Node fast in the browser

It's running in your browser. Literally, not on a server and streaming it to your browser. That makes it inherently local. I see webcontainers as the spiritual successor of tools like codespaces. If anything, this may mean that the local workflow will very much be alive and kicking 10 years from now. Just running your server in the browser, instead of on your OS.

> [@GitHub](https://twitter.com/github) runs entirely on Codespaces

Not going to be surprised if some day codespaces will be powered by something like webcontainers.

**Comment by prakhargupta1** [comment]
Closing it as it is done.
