### ISSUE TITLE
[docs] Demo PromptDialog crashes

### ISSUE THREAD

**Issue by Gabriel-LH** [mui/mui-toolpad#4004]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-toolpad/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20PromptDialog%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/toolpad/core/react-use-dialogs/
2. ??
3. demo *PromptDialog* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v0.5.2  |
| Netlify deploy | https://66cdc44fd6a4af000816ac21--mui-toolpad-docs.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by bharatkashyap** [comment]
I can't replicate this on Firefox or Chrome or Safari - could you describe your environment and what you're experiencing in greater detail?
