### ISSUE TITLE
[core] Should the authentication buttons be theme aware?

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#4015]
### Summary

I was exploring Toolapd core theming and noticed that the buttons in sign-in and sign-out components are not theme aware. While a newly added button takes the primary.main of the palette (check the screenshot below). I would assume the authentication buttons to be theme aware.

<img width="825" alt="Screenshot 2024-08-29 at 12 24 24 PM" src="https://github.com/user-attachments/assets/a08b0f60-e3a5-44df-94b7-d2b272b14bba">

**Search keywords**: button

**Comment by Janpot** [comment]
The buttons is theme aware, it's just not a primary button. Do you think the sign-out button should be a primary action?

**Comment by prakhargupta1** [comment]
> Do you think the sign-out button should be a primary action?

In this account popover, it seems to be the primary and only action.
But as menu item, [No](https://github.com/mui/mui-toolpad/pull/3992#issuecomment-2316949424).
