### ISSUE TITLE
Support arbitrary secrets

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#402]
Allow defining secrets in the application that can be referred to in serverside bindings. e.g. I define a secret `myGithubApiKey` and then in serverside bindings I can use it e.g. [in a header](https://github.com/mui/mui-toolpad/issues/401) as `` `${secrets.myGithubApiKey.value}` ``.

Secrets are encrypted in the database and never loaded on the frontend in unencrypted form.

Note: perhaps we should even keep the secret value outside of the application dom and have that injected during deploys. That way we could set up multiple environments

**Comment by prakhargupta1** [comment]
Should be done after UI/UX revamp.

**Comment by prakhargupta1** [comment]
We'll take a different approch.
