### ISSUE TITLE
[studio][docs] Book a demo link doesn't work

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#4021]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Open https://mui.com/toolpad/studio/
2. Click on a Book a demo

### Current behavior

Crash

### Expected behavior

Unknown

### Context

See it in https://app.ahrefs.com/site-audit/3833384/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&current=30-08-2024T021431&filterId=9b88587038fc9bb2e08e0ff143d5f328&issueId=c64d89a6-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by bharatkashyap** [comment]
@prakhargupta1 https://calendly.com/prakhar-mui/toolpad seems to be 404ing, is this a regression or is the URL incorrect?

**Comment by prakhargupta1** [comment]
Last week, I had to change this link to a generic https://calendly.com/prakhar-mui/30mins to cater to X and Toolpad users. 
Missed updating it in the linked docs. I'll fix it.
