### ISSUE TITLE
Copy & paste components

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#413]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add the ability to copy & paste a component, to essentially, duplicate it.

### Motivation 🔦

I'm working on an internal tool for MUI X, I have built a license key decoder, and I'm now working on a license key generator (instead of using the CLI).

<img width="276" alt="Screenshot 2022-05-14 at 01 06 13" src="https://user-images.githubusercontent.com/3165635/168399799-f1bb2dfc-1ea1-4396-a326-85a0518e54f4.png">

https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/pages/cl2kfa28r00013f69amqv1prv

I would like to have two headers.

### Benchmark

- https://www.appsmith.com/blog/may-round-up-app-theming-new-copy-paste-experience-and-product-updates#block-4

**Comment by prakhargupta1** [comment]
Closing it as it was a duplicate to: https://github.com/mui/mui-toolpad/issues/1036

**Comment by oliviertassinari** [comment]
@prakhargupta1 

1. Why not close #1036 instead of this one? Usually, the duplicate is the older issue or the one that has less information. Both criteria seem to apply here.
2. When you close as a duplicate, please mark as a duplicate: https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate#marking-duplicates

**Comment by oliviertassinari** [comment]
Duplicate of #1036
