### ISSUE TITLE
Add default value support to components

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#414]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add the ability to pick the default value for a component

### Motivation 🔦

I would like the license key generator to default to a subscription mode. I'm using the Select component, in which it's impossible to implement.

<img width="260" alt="Screenshot 2022-05-14 at 01 25 38" src="https://user-images.githubusercontent.com/3165635/168401005-c8cde8e0-9f65-4a3d-9cb3-d75cf5e62921.png">

**Comment by Janpot** [comment]
It's currently possible (as a test I've set your license model to "perpetual" by default), but the UI currently doesn't update with it. The reason is that default values are set on the first render only. I'd consider this a bug.

**Comment by oliviertassinari** [comment]
I have found a new use case for that defaultValue with a TextField. I would like it to be `new Date(new Date().getTime() + 1000 * 366 * 60 * 60 * 24).getTime()`.

**Comment by oliviertassinari** [comment]
I have landed again on this problem. It behaves strangely. Here is a different angle:

1. Add a `TextField` on the page
2. Set the value to `Foo`
3. 💥 the value is not visible on the text field
4. 💥 same in the binding view

<img width="221" alt="Screenshot 2022-08-06 at 19 28 13" src="https://user-images.githubusercontent.com/3165635/183259565-f2c2babf-54f2-4ecd-b422-b2a3851e5f70.png">

5. Reload: ✅

**Comment by Janpot** [comment]
> It behaves strangely.

The reason it behaves like this is that default value is only used during the first render. When the default value is changed while the component is already being rendered, it doesn't have an effect. But I agree it's strange behavior, we should probably make an exception to it for when the value is changed by the user in the editor.

There may also be a benefit to having a separate `defaultValue` property.

**Comment by oliviertassinari** [comment]
> The reason it behaves like this is that default value is only used during the first render.

+1 to try to experiment with remounting the component when the `value` changes. Effectively, to perform what a browser reload would do. If it's not enough, then `defaultValue`, might be needed.

**Comment by oliviertassinari** [comment]
I have found a new use case. I would like in https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/editor/pages/cl4hla87800029xoihl7tf4qz to be able to use a page parameter.

To be more precise, my use case is to be able to add `?order=121` in the URL, which would be equivalent to execute:

```sh
npx @material-ui/x-license --order 121
```

**Comment by Janpot** [comment]
> I can't bind the URL parameter to the "value":

Are you looking for a way to two-way bind? as in, changes in the text editor should also be reflected in the url?

**Comment by oliviertassinari** [comment]
> Are you looking for a way to two-way bind? as in, changes in the text editor should also be reflected in the URL?

No, one-way binding: URL -> Default value.

**Comment by oliviertassinari** [comment]
Awesome, a feature now in used for https://master--toolpad.mui.com/deploy/cl4hla83p01949xoizo5uxf2a/pages/cl4hla87800029xoihl7tf4qz?order=5225
