### ISSUE TITLE
Page grid layout

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#42]
Create a layout mode to arrange components on a fixed grid

**Comment by prakhargupta1** [comment]
Is it related to https://github.com/mui/mui-toolpad/issues/101 ?
Or does it need Waiting for upvotes label?

**Comment by Janpot** [comment]
This issue was more tracking building a free form grid like retool, dynaboard, appsmith,... But we should just pick a paradigm and go for it I think

**Comment by prakhargupta1** [comment]
@Janpot @apedroferreira Is this task still relevant?

**Comment by apedroferreira** [comment]
> @Janpot @apedroferreira Is this task still relevant?

I guess not, unless you want to try it at some point.

**Comment by prakhargupta1** [comment]
Ok, as the drag-drop UX has started to work well, I'll mark this closed. We can reopen later if we there comes a need to try the fixed grid approach.
