### ISSUE TITLE
Show production release version in the Releases view

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#427]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. I don't know the production release until I open it.
2. The rocket buttons don't work.

<img width="1207" alt="Screenshot 2022-05-17 at 12 16 10 PM" src="https://user-images.githubusercontent.com/92228082/168746840-f7b1be35-7986-40c3-a176-8f19e9c278e1.png">

### Expected behavior 🤔

1. Let's show the current deployed version in this view.
2. If that button is for deployment, then I think we can remove it from this list view. 1. shall be informational enough and if user wants to change the version she can go to the detailed view to deploy.

**Comment by Janpot** [comment]
@prakhargupta1 I'm doing a few quick updates to improve the behavior https://github.com/mui/mui-toolpad/pull/434. Regarding deleting releases I had a realization that the current behavior is not the right one. I've removed it for now, tracking adding it back in in https://github.com/mui/mui-toolpad/issues/433
