### ISSUE TITLE
Set minimum and maximum value for component number attributes

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#461]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Right now, for component properties that have a number value, any integer value can be set, including negative numbers.
For some for these attributes, we want there to be a minimum and maximum value that can be set.
This will make it less likely for the layout to break, or any other unintended behaviors to happen.

**Comment by prakhargupta1** [comment]
Is it related to all or some particular components? 
Where do we show 'component number attributes'?

**Comment by apedroferreira** [comment]
> Is it related to all or some particular components? Where do we show 'component number attributes'?

I could help on any UI controls for components that use numbers, even new custom components - for example if a row has a giant `gap` value like `9999` it would probably break the layout pretty bad.
This probably isn't high priority for now as we don't have that many cases/components where something like this can have bad consequences.

<img width="283" alt="Screen Shot 2022-08-18 at 16 36 38" src="https://user-images.githubusercontent.com/10789765/185436061-e0a7b15a-30af-48a6-89a3-98f08c75c723.png">
<img width="297" alt="Screen Shot 2022-08-18 at 16 36 49" src="https://user-images.githubusercontent.com/10789765/185436052-05a2e8bf-b947-4939-bd52-6edf1d32e48e.png">
