### ISSUE TITLE
"Remove binding" button doesn't close the binding dialog

### ISSUE THREAD

**Issue by mbrookes** [mui/mui-toolpad#486]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The binding is cleared, but the dialog stays open.

### Expected behavior 🤔

The dialog should close.

### Steps to reproduce 🕹

Steps:

1. Open an existing binding
2. Click "Remove binding"

**Comment by Janpot** [comment]
👍  https://github.com/mui/mui-toolpad/pull/487
