### ISSUE TITLE
Page structure explorer

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#490]
Create a panel that can show the page hierarchy as a tree and allows selecting/reordering page nodes. 

Benchmark:
https://getshogun.com/help/en/articles/1821780-using-the-layout-tab-to-view-page-structure

Retool
![Image](https://user-images.githubusercontent.com/92228082/185237516-0f1a5748-7e49-4fbe-854d-4c804778beb6.png)

### Shaping:

Must haves:

- left sidebar, vertical split, bottom panel will be a tree view
- Will try to use MUI lab TreeView component
- All DOM elements of current page
- We indicate the selected element, and allow selecting from this view
- Do we show rows and columns?
  - Let's show them and evaluate
- upon selection, expand the subtree that contains the selection, scroll into view
- To display nested children:
  - if the prop is `children` then we just nest them as the children of the component
  - if the prop is anything else we add an item in between with the name of the prop
- Overflow of the tree results in scroll

e.g.

```
Container:
  Paper:
    Button
    Text
Container:
  List:
    *renderItems*:
      Row:
         Button
         Text
```

Secondary:

- icons: Let's match the icons from the component catalog
- delete elements
- drag to reorder
- double-click to rename

**Comment by apedroferreira** [comment]
the bottom left part of the editor screen might be a good area for this?

**Comment by Janpot** [comment]
Intuitively I'd place this at the left. In the same area is the project hierarchy. At least, that's where almost any other tool that I can think of places it.
