### ISSUE TITLE
Make responsive container of pages configurable

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#492]
Allow for pages to stretch edge to edge, or configuration the maximum width of the fluid responsive container.

**Comment by prakhargupta1** [comment]
Would this allow the user to make apps responsive?
@apedroferreira @Janpot

**Comment by Janpot** [comment]
Currently the whole page is in a responsive container. If there is demand we can make that configurable. COnverting this issue to a wait for upvotes.

**Comment by apedroferreira** [comment]
> 

The page is "responsive" right now, but we're not adapting anything for smaller screens, which means probably nothing will look very good in smaller screens yet.
I think this is a different thing but not that difficult to do, we could just add the ability to customize horizontal margins in the page, or setting a maximum width, that could work too.

**Comment by Janpot** [comment]
Duplicate of https://github.com/mui/mui-toolpad/issues/1183
