### ISSUE TITLE
Query post-transformation, autocompletion support

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#503]
Currently it's unintuitive to build a post-transformation. The code editor doesn't help the user at all with autocomplete. One possible solution could be to, instead of expecting a function expression, we expect a function body, we can the supply `data` in the `globalScope` property of the editor to get autocomplete for free.

```tsx
return data;
```
instead of
```tsx
(data) => {
  return data;
}
```

@bharatkashyap what do you think?

**Comment by bharatkashyap** [comment]
> ```tsx
> return data;
> ```
> 
> instead of
> 
> ```tsx
> (data) => {
>   return data;
> }
> ```

This scenario creates this error:
<img width="830" alt="Screenshot 2022-05-31 at 1 23 36 PM" src="https://user-images.githubusercontent.com/19550456/171121775-6341a846-099d-49d4-9a69-8f854339db45.png">

**Comment by Janpot** [comment]
You can add `diagnosticCodesToIgnore: [1108]` under `monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions`

**Comment by bharatkashyap** [comment]
Another point here is that in the the scope preview alongside the transform function editor:

<img width="590" alt="Screenshot 2022-05-31 at 3 30 57 PM" src="https://user-images.githubusercontent.com/19550456/171148352-b5f654f4-6fa5-4f0e-b93b-50080b78b457.png">

we should always have the unmodified API response in the scope, and that would mean we should also pass the unmodified response to the client along with the transformed one, isn't it?

**Comment by Janpot** [comment]
> That would mean we should also pass the unmodified response back to the client along with the transformed one, isn't it?

We can always make 2 requests, 1 with "Transform response" enabled, and one without.

I think the tricky part will be in that currently we only update the preview on user action.

**Comment by bharatkashyap** [comment]
Makes sense. We could add another field to the `ApiResult` type, from:
```tsx
export interface ApiResult<D = any> {
  data: D;
  fields?: ApiResultFields;
}
``` 
to, possibly 
```tsx
export interface ApiResult<D = any> {
  networkResponse: D;
  transformedData?: D;
  fields?: ApiResultFields;
}
```

We would however have two JSON previews on one page with the same variable `data`  having different values:

<img width="1186" alt="Screenshot 2022-05-31 at 4 22 31 PM" src="https://user-images.githubusercontent.com/19550456/171157432-7ee89ff7-5396-408c-b976-23470ae8500b.png">
