### ISSUE TITLE
Create a pit of success to share the application built

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#572]
Users don't always realize they're sharing their app under the release-specific URL. Users won't receive updates when using this URL as the app gets deployed. We should clearly mark the app when it's accessed through this URL and provide a link to a shareable canonical URL for their app.

One idea could be to add a banner at the top with an explainer and link.

**Comment by oliviertassinari** [comment]
A couple of ideas on how we could improve this. (José & I get tricked)

1. Adding "share" section.

Figma
<img width="866" alt="Screenshot 2022-06-18 at 16 32 45" src="https://user-images.githubusercontent.com/3165635/174443073-364b2172-2acf-411e-a51e-cd0e9c5923c2.png">

Notion
<img width="523" alt="Screenshot 2022-06-18 at 16 33 05" src="https://user-images.githubusercontent.com/3165635/174443086-6c5509ae-ea25-4267-a082-4f50cacf9254.png">

Airtable

<img width="784" alt="Screenshot 2022-06-18 at 16 33 39" src="https://user-images.githubusercontent.com/3165635/174443112-45c777dd-7764-4479-b908-d09f772f3c94.png">

2. On the release page, link the public URL https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/releases.

Netlify: https://app.netlify.com/sites/material-ui/deploys?filter=master

<img width="655" alt="Screenshot 2022-06-18 at 16 35 34" src="https://user-images.githubusercontent.com/3165635/174443192-2ee618d6-e9ac-49fe-beb0-663f21e0ef5c.png">

Render: https://dashboard.render.com/static/srv-c8uf1hkobjd4knp4svg0/events

<img width="768" alt="Screenshot 2022-06-18 at 16 36 27" src="https://user-images.githubusercontent.com/3165635/174443222-f612260f-3c76-4831-8c5b-32b47d51b1d4.png">

**Comment by joserodolfofreitas** [comment]
Another consideration on the pain point:
The sharing experience is definitely a big part of it, but I have bookmarked the release link on the browser bar too. Ideally, that link would also point to the latest.

**Comment by Janpot** [comment]
Started sketching some changes to the release pages to deal with some of these issues https://github.com/mui/mui-toolpad/pull/583.

**Comment by prakhargupta1** [comment]
In the new Toolpad, the app URL is controlled by the user. Does that make this issue irrelevant?

**Comment by Janpot** [comment]
> Does that make this issue irrelevant?

Yes, this issue was tightly aligned with the concept of releases
