### ISSUE TITLE
Support GET, POST, DELETE, query methods

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#611]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Support different types of query methods. We currently only support GET.

<img width="306" alt="Screenshot 2022-06-25 at 16 58 49" src="https://user-images.githubusercontent.com/3165635/175779303-3ea62081-d40e-4874-9432-bf415a60abd4.png">

More benchmark https://www.notion.so/mui-org/Queries-6c9f84d68db5466c9e2738633deaa1e7

**Comment by prakhargupta1** [comment]
This is already done in functions data source. Further enhancements to this are being explored in https://github.com/mui/mui-toolpad/issues/777

Would it make sense to provide templates for each of the above request method, so that the user doesn't have to start from scratch? 
@Janpot

**Comment by Janpot** [comment]
I'm still on a longer standing effort to bring POST request bodies to the fetch datasource and some updates on how we handle binding values as we discussed in a few team meetings ago
https://github.com/mui/mui-toolpad/pull/721
