### ISSUE TITLE
In custom component interface, move 'Update' button to the bottom right.

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#613]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

<img width="1089" alt="Screenshot 2022-06-27 at 11 49 42 AM" src="https://user-images.githubusercontent.com/92228082/175925241-39d439d5-5e66-4b84-a48b-777ca6068f7f.png">

In the current placement, it gets easily missed.

**Comment by prakhargupta1** [comment]
Closed via #671

**Comment by Janpot** [comment]
That PR was closed without merging. Merging the [new PR](https://github.com/mui/mui-toolpad/pull/673) will automatically close this ticket
