### ISSUE TITLE
Allow column renaming in datagrid

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#649]
1. Column renaming doesn't work for a custom defined datagrid column

In this app: https://master--toolpad.mui.com/_toolpad/app/cl56qkrj70035aqtojzlqkzr0/editor/pages/cl56qkrjj0002aqto0wxe0kji

columns like parsed_diff2, gzip_diff2 are custom created in the rows JS editor but renaming these columns from Column properties is not possible. We will have to make aliases to support this.

<img width="1187" alt="Screenshot 2022-07-12 at 5 40 59 PM" src="https://user-images.githubusercontent.com/92228082/178532486-603522b6-bd55-4134-82ab-9a03813a9c21.png">
With reference to the above image:

**Comment by Janpot** [comment]
Added in https://github.com/mui/mui-toolpad/pull/1449
