### ISSUE TITLE
[docs] Redirection issue

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#660]
### The problem

All requests to resources under `_next` when navigating to [https://mui.com/toolpad/](https://mui.com/toolpad/) fail, because of – I imagine – [this](https://github.com/mui/material-ui/blob/62a777e6ea4dd13c5e9f369b6c843a389b160dda/docs/public/_redirects#L401) conflicting rewrite rule:
<img width="668" alt="Screenshot 2022-07-15 at 1 31 11 PM" src="https://user-images.githubusercontent.com/19550456/179179918-de21a631-d6f0-466c-9b77-ac3e2f832221.png">

### Ideas on solutions

1. Setting a custom build directory instead of `.next` might be a possible way to fix this => doesn't work it has no impact on the URLs.
2. Configuring the `_next` prefix => not possible https://github.com/vercel/next.js/issues/31718
3. Using `assetPrefix` => OK-ish, not awesome because it would break the standalone previews
4. Using `basePath` => doesn't work because it breaks the links. Links we can't change because not coming from this repository.

**Comment by Janpot** [comment]
This rule is surprising to me:

```
/_next/* https://material-ui-x.netlify.app/_next/:splat 200
```

How come it doesn't conflict with the core docs? The core docs need assets from `/_next/*` as well, but don't they all get routed to the X docs assets according to that rule?

**Comment by oliviertassinari** [comment]
> How come it doesn't conflict with the core docs?

@Janpot Netlify will first resolve the files that are on the filesystem:

> By default, you can’t shadow a URL that actually exists within the site.

https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing

It's only if we where doing this that it would be broken:

```jsx
/_next/* https://material-ui-x.netlify.app/_next/:splat 200! 
```

**Comment by siriwatknp** [comment]
@bharatkashyap Can you put that line in https://github.com/mui/mui-x/blob/master/docs/public/_redirects?

**Comment by oliviertassinari** [comment]
> This rule is surprising to me:

@Janpot Gone in this commit inside MUI Core: https://github.com/mui/material-ui/commit/04fa759c7995b86a0010f3af492a386dc9e657b3.
