### ISSUE TITLE
Applications cards overflow badly

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="499" alt="Screenshot 2022-07-19 at 17 25 07" src="https://user-images.githubusercontent.com/2109932/179788875-811f32b9-bcd0-4a53-978f-c0f260075ec5.png">

### Expected behavior 🤔

Proper overflow behavior. Ellipses maybe? Or should this UI be a table rather than cards?

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by apedroferreira** [comment]
i think ellipses would solve it, but the title text should be small enough so that titles that aren't too long are always fully readable
