### ISSUE TITLE
Input label gets cut off

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#681]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On https://master--toolpad.mui.com/_toolpad/app/cl27ajqfu0403a0oz236ay3pj/editor/pages/cl27arb1i00043g693pzhex2r
![Screenshot 2022-07-22 at 15 20 08](https://user-images.githubusercontent.com/2109932/180447843-29256c6f-782c-498e-afa6-1c722243408b.png)

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by apedroferreira** [comment]
i fixed this in my PR for resizing but should've added it separately, anyway fix is coming :D
