### ISSUE TITLE
REST query options are being reset when changing other options

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#686]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I start configuring REST query:
1. Add URL
2. Change query name

URL is reset to blank value

### Expected behavior 🤔

I would expect that no values are reset when I change other values in dialog

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

Latest master, local instance

**Comment by prakhargupta1** [comment]
@bytasv 
I tried replicating, but it doesn't happen for me.
Can you check it? Also, a video would be helpful.

**Comment by bytasv** [comment]
I can't reproduce this anymore 🤔 maybe it got fixed with some other work. Anyways I think we should always add exact repro steps next time so it's clear whether this is still happening or not (my bad 😅 )

**Comment by Janpot** [comment]
Likely was solved as a side effect of https://github.com/mui/mui-toolpad/pull/764
