### ISSUE TITLE
Opening an application without changing marks it as edited

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#709]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. From the overview page, open an app that is not at the first position.
2. Move back to the overview page
3. The app you just opened has moved to the first position

### Expected behavior 🤔

If the app is not edited, it shouldn't be marked as such

**Comment by apedroferreira** [comment]
this might be because of the row resizing logic, i can look into it

**Comment by apedroferreira** [comment]
ok i've investigated and doesn't seem to be anything in the `RenderPanel` after all... 🤔
