### ISSUE TITLE
Support Checkbox component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#742]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://mui.com/material-ui/react-checkbox/

One of: https://github.com/mui/mui-toolpad/issues/78

**Comment by JerryWu1234** [comment]
let me take a look

**Comment by JerryWu1234** [comment]
> Hi @JerryWu1234, We could start with a single `checkbox` first. Later, when we have a use case for the `Checkbox group`, we can look into it.

thanks I got it

**Comment by prakhargupta1** [comment]
Closed by #2494
