### ISSUE TITLE
Support Switch component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#745]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://mui.com/material-ui/react-switch/

One of: https://github.com/mui/mui-toolpad/issues/78

**Comment by JerryWu1234** [comment]
I'll be work on.

**Comment by Janpot** [comment]
Question: Would it make sense to implement this as a variant on the checkbox component and leverage https://github.com/mui/mui-toolpad/pull/2763 to add a switch component in the library?

**Comment by JerryWu1234** [comment]
`Switch` is very normal componen.
if we do not inform the user beforehand but they want to use the `Switch`, they may have difficulty locating it .

Of course, this is just my poor idea. Waiting for a better idea.

**Comment by Janpot** [comment]
> if we do not inform the user beforehand but they want to use the `Switch`, they may have difficulty locating it.

Exactly, this is where https://github.com/mui/mui-toolpad/pull/2763 comes in. It allows us to add a "Switch" component to the library, very findable. But keep the implementation in the Checkbox component.
