### ISSUE TITLE
Support Tabs component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#747]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://mui.com/material-ui/react-tabs/

One of: https://github.com/mui/mui-toolpad/issues/78

**Comment by bytasv** [comment]
@prakhargupta1 can you confirm if I understand correctly that we want something ala `Tabbed container` that retool offers? 
<img width="81" alt="CleanShot 2023-01-02 at 15 21 26@2x" src="https://user-images.githubusercontent.com/437214/210237030-2395611b-48f5-4157-ada3-7cea7ed57e67.png">

<img width="574" alt="CleanShot 2023-01-02 at 15 21 59@2x" src="https://user-images.githubusercontent.com/437214/210237052-a1e2263c-fde0-4c9e-82d3-71f29e889275.png">

There is also `Tabs` component which allows controlling other components via special configuration
<img width="659" alt="CleanShot 2023-01-02 at 15 23 34@2x" src="https://user-images.githubusercontent.com/437214/210237309-64a807b8-f427-4f61-9a73-2eded251605f.png">

Should we implement one, the other or both?

**Comment by prakhargupta1** [comment]
We should do Tabbed containers.  
Example from appsmith [here](https://docs.appsmith.com/reference/widgets/tabs#:~:text=The%20tabs%20widget%20is%20a,user%20based%20on%20their%20choices.)

**Comment by JerryWu1234** [comment]
@Janpot 

Today I doved into this issue. 
Tabs can only receive only one `children` property.
my suggestion is change children into a type of array.

**Comment by apedroferreira** [comment]
> @Janpot
> 
> Today I doved into this issue. Tabs can only receive only one `children` property. my suggestion is change children into a type of array.

An array of `layoutSlot` props might work? But not sure if there would be any obstacles that could be complicated to deal with.
