### ISSUE TITLE
Support Form component

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#749]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Examples 🌈

- https://ant.design/components/form/
- https://retool.com/components/form, https://retool.com/components/json-schema-form
- https://mantine.dev/form/use-form/
- https://docs.appsmith.com/reference/widgets/form
- https://refine.dev/docs/core/hooks/useForm/

**Comment by bharatkashyap** [comment]
Sharing an idea for the form component here: For me the most useful feature would be if a form could be auto-generated from a pre-existing DataGrid on your page. The data on submission would feed into that DataGrid.

**Comment by prakhargupta1** [comment]
The JSON form as demonstrated [here](https://www.youtube.com/watch?v=Zk6df9mOtQA) makes total sense. 
It can create or update a record in the data source, provide validations, read and display correct data types.
Let's discuss it further.

**Comment by prakhargupta1** [comment]
I think we can have 2 types of forms:

1. A basic form that just takes some basic input and has 2 buttons; Submit and an optional Cancel/Reset. 
    Eg 1: A login form that just asks for username and password.
    Eg 2: A complaint box that asks for a user issue and shows an additional button to upload any file.

2. A JSON form, that generates a form based on a datagrid json schema. Now, it would be interesting to have this form as a slideout component. This is also a problem that I was facing, so when I was wanted to show details of a selected row, I had to make many Typography components that connected with each cell value I wanted to show.
 Example experience can be checked [here, point 1](https://www.superblocks.com/blog/alchemy-scaling-support-through-hypergrowth-with-superblocks)

**Comment by bytasv** [comment]
IMO it shouldn't be too hard to to build form kinda like we build using paper component - drag and drop buttons, inputs, selects and other form elements into form and then using context or w/e else "register" them so that they values can be captured as a form input. I think we shouldn't hardcode form layout at all

**Comment by apedroferreira** [comment]
> IMO it shouldn't be too hard to to build form kinda like we build using paper component - drag and drop buttons, inputs, selects...

This would also be more consistent with how the `List` are `Card` components are probably going to work.
