### ISSUE TITLE
Support non root npm import

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It could be interesting to support imports like:

```jsx
import Typography from "@mui/material/Typography";
```

I was moving this code to Toolpad https://github.com/mui/card-generator/blob/43f889160708b40b0a218deeefeecc0e76d11338/src/Mui-X-release.js#L3 when I have found the problem. We document this pattern everywhere in the docs of http://mui.com/ because it's the only way to get tree shaking in dev mode.

### Reproducton

<img width="1153" alt="Screenshot 2022-08-06 at 19 21 05" src="https://user-images.githubusercontent.com/3165635/183259339-e4091c42-31f5-46df-9f71-4d0c1ddd15d2.png">

https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/codeComponents/cl6i5vml600013b6gw8ir9yfs

### Examples 🌈

It almost works with esm.sh, modulo the React context duplication:

<img width="1148" alt="Screenshot 2022-08-06 at 19 24 07" src="https://user-images.githubusercontent.com/3165635/183259425-4ec73179-4e87-4f04-832f-489aca4104ae.png">

https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/codeComponents/cl6i5yj4700013b6gpptyqnxb

**Comment by prakhargupta1** [comment]
I think this one can be marked closed now? @Janpot

**Comment by Janpot** [comment]
this should work in the next version when we make the new runtime default

**Comment by oliviertassinari** [comment]
I believe we solved this.
