### ISSUE TITLE
Deleting component doesn't work when just added to the page

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#752]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have to unselect/reselect to have the <kbd>Backspace</kbd> key delete the component.

### Expected behavior 🤔

I can press the <kbd>Backspace</kbd> key as soon as I add the component to remove it.

### Steps to reproduce 🕹

https://user-images.githubusercontent.com/3165635/183259732-7c0478ad-2eba-4360-8755-596bee610bca.mov

### Context 🔦

I **systematically** confuse the TextField with the Typography component. Hopefully, #598 would fix this. This is how I found the bug.
I'm only reporting it to collect upvotes, to not fix yet.

**Comment by Janpot** [comment]
I think it makes sense to at least look into what's going on here. And fix now only if it's straightforward

**Comment by apedroferreira** [comment]
hopefully should be a quick one, i can take a look
