### ISSUE TITLE
[Typography] Buggy default value

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#755]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

What's displayed should match with the props

### Expected behavior 🤔

It doesn't match.

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/pages/cl6i6tvxa00003b6gb6jit295
2. See how there is "Text" displayed but nothing under the "value" property.

<img width="550" alt="Screenshot 2022-08-06 at 19 49 02" src="https://user-images.githubusercontent.com/3165635/183260208-5ddce141-d956-4792-bc93-5f764e125292.png">

### Context 🔦

I first tried to click on the "Text"

<img width="404" alt="Screenshot 2022-08-06 at 19 47 47" src="https://user-images.githubusercontent.com/3165635/183260157-f7c19394-6780-41c5-8dfc-e1120fbb5178.png">

area to type my text. When I realized that it would not work, I searched for where "Text" was displayed. And because I couldn't find it, I started to try the different prop to see which one would update the content of the Typography.

**Comment by Janpot** [comment]
I think this is a regression, and probably the same root cause as https://github.com/mui/mui-toolpad/issues/753
