### ISSUE TITLE
Support Markdown component

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The TextField component is quite limited. By default, I would expect to be able to use Toolpad's text component like I use Notion 😁

### Motivation

In https://master--toolpad.mui.com/_toolpad/app/cl4hla83p01949xoizo5uxf2a/editor/pages/cl6i430vg00003b6ghpxth1dz, I had to mix two different components, but they are not part of the same layout flow, they should:

<img width="645" alt="Screenshot 2022-08-06 at 19 53 46" src="https://user-images.githubusercontent.com/3165635/183260348-2f2dad4b-2203-419f-8b26-c18aa5b20243.png">

### Examples 🌈
https://retool.com/blog/text-v2-app-documentation/

**Comment by prakhargupta1** [comment]
When we add it, should we remove typography component? 
Are images, videos and text links different?

**Comment by oliviertassinari** [comment]
> When we add it, should we remove typography component?

I wonder, Notion is made of small blocks and it feels great, so maybe keep both. 

> Should we call it Rich text or MD?

I would be afraid that if we call it Rich text, then people will confuse this with a Rich text editor. Markdown sounds clear.
