### ISSUE TITLE
Add integration test for the application editor

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#758]
Test basic functionality in a playwright test:

- Can we test drag & drop? (In a way that doesn't regress constantly)
- selection and default property values https://github.com/mui/mui-toolpad/issues/755
- deleting elements
- updating property value
- ...

**Comment by oliviertassinari** [comment]
> Can we test drag & drop?

MUI X has a few tests about this https://github.com/mui/mui-x/blob/249969c611a2d89ff895bdb639551b6dae0d5e3d/test/e2e/index.test.ts#L175
