### ISSUE TITLE
Empty drop areas in editor are easy to wrongfully perceive as buttons

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#773]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Empty drop areas in the editor kind of look like buttons, which creates even more confusion when users click it and nothing happens.

<img width="1792" alt="Screen Shot 2022-08-10 at 20 01 24" src="https://user-images.githubusercontent.com/10789765/183997460-6f9cab27-59f0-407a-99fb-bb652f7cb2d0.png">

A good solution would probably be to change the way these drop areas look visually, so users don't think that they're buttons, and can correctly perceive them as drop areas.

Ideas:
- Replace the "+" with something like "Drag components here"

Small benchmark:
- Makeswift leaves its drop area empty.
- Retool has their "main" section with no indicator of being a drop area.
- Appsmith has just an empty canvas.
- Flutterflow shows instructions "drag a layout element..."

![Screenshot 2022-08-02 at 17 46 48](https://user-images.githubusercontent.com/10789765/183996806-63d683b0-7b8d-4d5a-aef4-46a4cfaf71bb.png)
![Screenshot 2022-08-02 at 17 49 24](https://user-images.githubusercontent.com/10789765/183996797-4e02207a-f572-4f69-84c6-c1fcf89a6f1b.png)

### Expected behavior 🤔

Empty drop areas should not confuse users.

**Comment by prakhargupta1** [comment]
Along with adding a message, we should also increase the height of the drop-box.
