### ISSUE TITLE
[RFC] Merge Fetch and Function datasource

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#777]
### What's the problem? 🤔

Currently we have two separate connection types, "Fetch" and "Function"
<img width="564" alt="Screenshot 2022-08-11 at 7 17 57 PM" src="https://user-images.githubusercontent.com/19550456/184122001-c0a23ab8-260d-4d82-99ab-d7a684f7e57c.png"> 
which provide similar utility; being able to connect to an API. 

While creating a query, it isn't immediately obvious what the distinction will be between these two options:
<img width="755" alt="Screenshot 2022-08-11 at 7 20 48 PM" src="https://user-images.githubusercontent.com/19550456/184122419-200263d9-7e3d-48c1-9ecb-f8e2b8372b19.png">

and while editing the query, the configuration options for Fetch <img width="1456" alt="Screenshot 2022-08-11 at 7 19 48 PM" src="https://user-images.githubusercontent.com/19550456/184122235-598649fe-48df-41dd-aec5-ec7e811aaa4c.png"> are a subset of a Function query, but represented visually:
<img width="1468" alt="Screenshot 2022-08-11 at 7 23 35 PM" src="https://user-images.githubusercontent.com/19550456/184122858-720315d0-3ee7-425c-bc40-cbd46df515a8.png">

 

### Proposed solution 🟢

Therefore, it feels like we could merge the two entities and provide the only a single option, perhaps like so:
<img width="1512" alt="Screenshot 2022-08-11 at 7 58 27 PM" src="https://user-images.githubusercontent.com/19550456/184128499-be8a6095-5490-4a0c-ab03-8b26da9597fb.png">

load the Fetch configuration options by default, provide an option to toggle into the Function mode (but disable toggling back if the user has added custom code into the Function editor).

**Comment by bytasv** [comment]
I like the idea. Maybe it would make sense to call aggregated option something like `API Query` and then have 2 tabs inside:
`Basic` and `Advanced` (which would display function UI).
If we did something like that, then I'd expect that if I'm in basic Query mode, when switching to `Advanced` I get the code for exact same Basic query, just with an option to modify difference pieces 🤔

**Comment by Janpot** [comment]
Just to keep in mind, this is a one-way-operation. I can see how one can generate a function datasource from a rest datasource, but not the other way around. Using tabs as a UI may give users the false impression that they can go back

**Comment by bytasv** [comment]
We can always convert basic to advance, right? So if we use tabs, we could simply throw warning: Your function source will be reset (or something similar) and that's it 🤷

**Comment by bharatkashyap** [comment]
> We can always convert basic to advance, right? So if we use tabs, we could simply throw warning: Your function source will be reset (or something similar) and that's it 🤷

Agree with this as well; we can reset to default with a warning in case a user tries to go back

**Comment by prakhargupta1** [comment]
This can be closed now. A related requirement could be to allow converting a UI fetch query to code query.
