### ISSUE TITLE
Throw an exception when creating a custom component with a hyphen

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#790]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

It throws.

### Expected behavior 🤔

It works.

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/_toolpad/app/cl42qt2jx01249xnr14xjce8b/editor/pages/cl42qt2kt00029xnr5rta2nog
2. <img width="479" alt="Screenshot 2022-08-13 at 13 40 37" src="https://user-images.githubusercontent.com/3165635/184492576-c976e507-1368-4788-bc3b-f4f85ab224bd.png">
3. <img width="527" alt="Screenshot 2022-08-13 at 13 40 50" src="https://user-images.githubusercontent.com/3165635/184492575-bc9f6034-d808-46fd-a0be-7a03f45f9c1c.png">

### Context 🔦

It's never clear to me what capitalization and word separation I should use in the different text fields of Toolpad.

**Comment by Janpot** [comment]
We should add validation to this input, and the create button should be disabled as long as the input is invalid

**Comment by oliviertassinari** [comment]
> the create button should be disabled

I would be in favor of never disabling a submit button, but to make it a noop and to show the error when pressed.

**Comment by Janpot** [comment]
> I would be in favor of never disabling a submit button, but to make it a noop and to show the error when pressed.

I think it makes sense to decide on a case-by-case basis. 
- A single input + submit button in a dialog: we should show a validation message as soon as invalid input is typed, and disable the button to communicate that nothing will happen when clicked.
- a large form with multiple inputs that can scroll: I think not disabling the button and showing the error when pressed (as you described) makes sense
