### ISSUE TITLE
Update favicon icon with Toolpad logo

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#812]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

**Comment by prakhargupta1** [comment]
Test

**Comment by prakhargupta1** [comment]
Based on my discussion with @gerdadesign, we will do it as part of the larger UI overhaul.
I'll remove it from the current cycle.

**Comment by oliviertassinari** [comment]
Was this issue about the favicon? ⬇️

<img width="248" alt="Screenshot 2022-08-30 at 11 19 29" src="https://user-images.githubusercontent.com/3165635/187399868-01ee2c23-52be-4800-8b37-389bb20767aa.png">

**Comment by prakhargupta1** [comment]
Yes, we could update the logo in favicon.
The task was about replacing **Home icon MUI Toolpad CE** with 

![Image](https://user-images.githubusercontent.com/92228082/187409874-c9b35e51-7190-4e05-81cc-83ebecdaeb4a.png)

Some questions that came across:

- Is it ok to remove CE?
- The blue color in Toolpad logo is different from the blue color being used inside Toolpad currently.

Then we decided to do it later with the overhaul.

**Comment by prakhargupta1** [comment]
Is there anything that blocks this task? @bharatkashyap 

Here is the link to the bigger task that we'll tackle separately: https://github.com/mui/mui-toolpad/issues/873

**Comment by bharatkashyap** [comment]
In case of https://mui.com/x/, the favicon is the MUI logo (which is the current state for Toolpad as well). Do we need to change it? My personal opinion would be to not change this.

In case we need to, I would need to have the correct `.ico` file to replace the existing one.

**Comment by prakhargupta1** [comment]
Somehow, it is coming blank for me. Also checked Firefox and Incognito.
![Screenshot 2022-09-06 at 11 45 51 AM](https://user-images.githubusercontent.com/92228082/188560463-5322dc08-bcc2-4b64-8aa6-65040cd660c9.png)

**Comment by Janpot** [comment]
Yes, I added a blank placeholder icon a while ago to avoid errors in the integration tests

**Comment by oliviertassinari** [comment]
> In case of https://mui.com/x/, the favicon is the MUI logo (which is the current state for Toolpad as well). Do we need to change it?

@bharatkashyap For the marketing page, as a developer, I think that I would expect to see the MUI company logo, e.g. https://www.hashicorp.com/products/consul. But I'm not sure, maybe the logo of the open source project would make more sense, like https://k6.io/.

For the documentation pages, as a developer, I think that I would expect to see the logo of the related open-source project. e.g. https://www.consul.io/docs.

In the end, it's more of a question for the design department.

**Comment by bharatkashyap** [comment]
> For the application itself, I assume the Toolpad logo? Or should it be the MUI one?

I think the Toolpad logo makes the most sense here

**Comment by gerdadesign** [comment]
Confirming we discussed using the Toolpad logo as the favicon for toolpad itself. Something like: 
<img height="42" alt="Tab (1)" src="https://user-images.githubusercontent.com/106991024/188929854-b06c2891-c9fb-420a-be79-265340f53b92.png">

**Comment by oliviertassinari** [comment]
I'm reopening, #911 doesn't respect the scale of the logo, it looks distorted

<img width="400" alt="Screenshot 2022-09-11 at 19 02 25" src="https://user-images.githubusercontent.com/3165635/189539908-013f0370-99ec-4bd4-8514-5b83320c4b68.png">

**Comment by prakhargupta1** [comment]
<img width="197" alt="Screenshot 2022-09-12 at 11 46 43 AM" src="https://user-images.githubusercontent.com/92228082/189585701-bb21891c-ec25-4b84-b44f-8d7ffa61c6cf.png">

The difference can also be seen here. Toolpad icon (left), Notion space icon (right)

**Comment by gerdadesign** [comment]
Thanks for catching that @oliviertassinari!
@bharatkashyap See if these files work better for you.  _I had to do a zip since github doesn't support ico._

[MUIToolpadFavicon_favicon_io.zip](https://github.com/mui/mui-toolpad/files/9548558/MUIToolpadFavicon_favicon_io.zip) includes:
- PNG @ 512px, 192px, 180px, 48px, 32px, 16px
- ICO @ 48px  
- site.webmanifest

For reference, I created a square frame in figma, added the toolpad logo, and exported the png. Then used https://favicon.io/favicon-converter/ for the conversion + all sizes (that's why that webmanifest file is in there). This is probably overkill, but just in case you need it, here are the [installation instructions](https://favicon.io/favicon-converter/) from the site.

**Comment by oliviertassinari** [comment]
One day, we will be able to use SVG for icons https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/

**Comment by bharatkashyap** [comment]
> a funny story on how we got the favicon in IE 5, asking a junior PM, so smart! 😅

>> A funny thing about the history of the favicon: Internet Explorer was the first browser to support them and [they were snuck in at the 11th hour](https://thehistoryoftheweb.com/how-we-got-the-favicon/) by a developer named Bharat Shyam:

Unexpected surprise to find another Bharat in the creation story of the `.ico` format :D

**Comment by bharatkashyap** [comment]
> Thanks for catching that @oliviertassinari! @bharatkashyap See if these files work better for you. _I had to do a zip since github doesn't support ico._
> 
> [MUIToolpadFavicon_favicon_io.zip](https://github.com/mui/mui-toolpad/files/9548558/MUIToolpadFavicon_favicon_io.zip) includes:
> 
> * PNG @ 512px, 192px, 180px, 48px, 32px, 16px
> * ICO @ 48px
> * site.webmanifest
> 
> For reference, I created a square frame in figma, added the toolpad logo, and exported the png. Then used https://favicon.io/favicon-converter/ for the conversion + all sizes (that's why that webmanifest file is in there). This is probably overkill, but just in case you need it, here are the [installation instructions](https://favicon.io/favicon-converter/) from the site.

Thanks @gerdadesign! This was extremely helpful :D I’ve opened #984 to fix this.
