### ISSUE TITLE
In the right pane, props and component name should be visually separated

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#819]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, the right panel shows everything together. Should we have some visual separation based on the type of items?

Moreover, we can also look into separating UI props from data props.
<img width="301" alt="Screenshot 2022-08-18 at 1 50 04 PM" src="https://user-images.githubusercontent.com/92228082/185347082-9ba6917c-5acb-4e71-8055-3b22e0b59382.png">

**Comment by apedroferreira** [comment]
i'm going to separate some "layout" props in this PR https://github.com/mui/mui-toolpad/pull/804, but it still doesn't look great, I can still at least try to improve the spacing there.

**Comment by apedroferreira** [comment]
> Moreover, we can also look into separating UI props from data props.

We would need something like property categories to do something like this, so we could group them by category. But this would mean every prop would need to have its own category, which I'm not sure would make sense in every case.

So for now I just tried to make the order of the props in each component a bit more logical, but if we want to categorize and split thing I guess we can do it separately.
