### ISSUE TITLE
Dependent selection clears Typography field

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#832]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When selecting an option from the sub-breed drop down and then subsequently select another breed, the image URL changes to "Text" and no image loads:

https://user-images.githubusercontent.com/19550456/185734854-7fcef3c9-480b-4cc6-9f49-1b2cb74df818.mov

### Expected behavior 🤔

The image URL should change to the appropriate URL for the selected breed and the image should be displayed

### Steps to reproduce 🕹

Steps:

1. Navigate to https://master--toolpad.mui.com/app/cl27ajqfu0403a0oz236ay3pj/preview/pages
2. Select a breed, e.g. "Samoyed"
3. Select a different breed, e.g. "Australian"
4. Select a sub-breed, e.g. "Shepherd"
5. Select any other breed again, e.g. "Samoyed"

**Comment by prakhargupta1** [comment]
It is currently affected by https://github.com/mui/mui-toolpad/issues/1086. The sub-breed filter is not responding when there is no sub-breed. I'll check it again later.

**Comment by bharatkashyap** [comment]
I can replicate this again after #1086 has been rectified

**Comment by prakhargupta1** [comment]
I could replicate it too. Let's diagnose it.
