### ISSUE TITLE
Unable to scroll in the function query editor

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-toolpad#833]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When trying to edit a Function query, the code editor doesn't let a user scroll above line 7:

https://user-images.githubusercontent.com/19550456/185739578-7ed6ee56-d559-4588-a9de-b8664bf9cfcf.mov

### Expected behavior 🤔

The scrollbar should let the user scroll to the top

### Steps to reproduce 🕹

Steps:

1. Navigate to https://master--toolpad.mui.com/_toolpad/app/cl1on1bd80041a1pdrrfdt0rq/editor/pages/cl6ysktjz00023b6g8xkizxr8
2. Click on "query10"
3. Try scrolling the code in the editor

**Comment by Janpot** [comment]
This has been solved in https://github.com/mui/mui-toolpad/pull/811 as I copied the layout and it suffered from the same problem.
