### ISSUE TITLE
[website] Toolpad documentation to be updated

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#834]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Based on the finalized [structure](https://www.notion.so/mui-org/Toolpad-documentation-ea6b379e88434c2ebf58b7b948d49208), update [documentation](https://mui.com/toolpad/getting-started/tutorial/).

**Comment by bytasv** [comment]
I'm wondering if this issue can be closed now or should we add something else to the docs? It currently has main functionality covered, the rest that's mentioned in https://www.notion.so/mui-org/Toolpad-documentation-ea6b379e88434c2ebf58b7b948d49208 does not have a clear content to put in place. Maybe we could do a dedicated tasks once we figure out what else we are putting in the docs? Or should we keep this one open?

**Comment by prakhargupta1** [comment]
I think we can close it, as the bigger part of creating the structure is done.
If I am not wrong, after merging the PRs https://mui.com/toolpad/getting-started/setup/ needs to show the changes, I think that's missing for now. 
Also let's link all related PRs to this issue.

We'll create new issues for the dedicated sections of the docs.

**Comment by bytasv** [comment]
Ok, then closing it. All PRs are linked to the issue
