### ISSUE TITLE
Components should have some pre-filled dummy data when dragged on canvas

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#841]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

This would assist in getting started with the components. Component names:
1. Data grid
2. Select
3. Image

Also, for Select and Textfield components Label="Label" should be there by default.

**Comment by bharatkashyap** [comment]
What kind of data do we want to show in each of these components?

**Comment by prakhargupta1** [comment]
For datagrid we can show the JSON that we have here: https://mui.com/x/react-data-grid/#mit-version
In select we can show 6 months (Jan to June)
Image: Any image from MUI assets

**Comment by bharatkashyap** [comment]
I was wondering what objective loading dummy data in the DataGrid serves for a user, and felt if something like this might be better suited instead:

![Image](https://user-images.githubusercontent.com/19550456/202447416-ec47ab80-dd5b-405a-8baa-5fd566cf7071.png)

Since this points the user to the possible next steps in the flow. I

I'm not exactly certain at this point how big and complex this would be, but we can have that discussion if this idea feels worthwhile.

**Comment by prakhargupta1** [comment]
It will lead to following extra handling, some thoughts:

1. If there are many queries which 3 will we show?
2. For the scenarios where there will be no queries, this will only show CREATE NEW QUERY.
3. After dragging a datagrid, with the new query interface we can possibly show prompts that can take the user to 'Create Query'.

We can revisit it in the future, but for now having some dummy data can help user visualize the component output better.

**Comment by bharatkashyap** [comment]
> It will lead to following extra handling, some thoughts:
> 
> 1. If there are many queries which 3 will we show?
> 2. For the scenarios where there will be no queries, this will only show CREATE NEW QUERY.
> 3. After dragging a datagrid, with the new query interface we can possibly show prompts that can take the user to 'Create Query'.
> 
> We can revisit it in the future, but for now having some dummy data can help user visualize the component output better.

Understood. 

For me, a good idea is to create a new template (Internal Admin tool?) which has a few components on the canvas with data present in them. We could possibly make it the default template when creating apps. 

I see two benefits in this case:  
- a first time user can see data in the components by default
-  a returning user will not have to go through the friction of removing dummy data from components each time they are adding one

**Comment by prakhargupta1** [comment]
Agree that we should replace Covid API with our version of user data. Covid api providers in their terms mention overburden as a restriction. We can create something like the movies json.


I'll create an issue for this. Let's do this after releasing the demo.
