### ISSUE TITLE
Allow for immediate deployment when creating a release

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#860]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We should add a switch to the "create release" dialog that says "immediately deploy this release". It should be enabled by default. When it's enabled, the release should be immediately promoted to the current deployed version.

### Motivation 🔦

Most of the times a user intends to immediately deploy a release when the create it. Therefore this flow should be the default.

**Comment by prakhargupta1** [comment]
Shall we mark this as done? @Janpot

**Comment by Janpot** [comment]
👍
