### ISSUE TITLE
Tweak action buttons styling

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#870]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The way we currently style our action buttons both in dialogs and in other places is not really consistent as well as doesn't seem to follow best UX practices

Primary CTA's are kinda blending in with `cancel` button
![image](https://user-images.githubusercontent.com/437214/187411873-73ae4574-8a50-4813-9afe-115fd82c3e70.png)

![image](https://user-images.githubusercontent.com/437214/187412025-4891b643-7d8e-4c52-8153-8c38e2b46558.png)

Entirely different styling

![image](https://user-images.githubusercontent.com/437214/187412308-165584d3-e7b4-44a6-a0c9-e8c102634a4c.png)

Component creation only has update which is yet another style

![image](https://user-images.githubusercontent.com/437214/187412424-be21cc39-6c01-41c6-8dc4-8eb472b3959a.png)

In addition we do not differentiate destructive vs positive actions - both buttons have same style

### Examples 🌈

I would expect that every:

1. `cancel`/`revert` type action would have a "muted" style in our case `variant="text"` (👌  seems that we are following this pretty much everywhere)
2. Primary CTA that "confirms" action would have "standing out" style in our case `variant="contained"`
3. All "negative"/"destructive" confirmation actions (such as delete, remove, etc..) would use `color="error"` to hint users intention
4. All "secondary" actions (i.e. remove when there is also an option to "save") would use `variant="outlined"` not to be mixed with primary CTA and cancel buttons

cc @gerdadesign obviously your feedback would be very valuable here to either confirm or reject my proposal 🙇 

### Motivation 🔦

Main motivation for these changes is to create a consistent userflows where UI would be more "self explanatory"

I think it's also relevant to dialog box improvements mentioned in https://github.com/mui/mui-toolpad/issues/798

**Comment by prakhargupta1** [comment]
Agree, it is better to wait as under the scope of this issue we'll review e2e UX for all dialog boxes.

**Comment by prakhargupta1** [comment]
Closing this as none of these buttons are there in Toolpad anymore.
