### ISSUE TITLE
[RFC] UI Terminology

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#878]
### What's the problem? 🤔

While working on Toolpad documentation (https://github.com/mui/mui-toolpad/pull/859) we kicked off a discussion about what should be the right name to call certain sections of Toolpad app.

![image](https://user-images.githubusercontent.com/437214/187905272-d1bdebba-74f2-4f34-8684-929fd434da5a.png)

### What are the requirements? ❓

- Each UI section of Toolpad has a name that can be used to communicate/refer
  - Left
  - Right
  - Top
  - Middle (canvas/editor)
  - Components drawer
- Should be fairly common how similar sections would be called in similar apps (so it's easier for new users who have tried similar software)

### What are our options? 💡

**Left** and **Right**
- Sidebar
- Pane

**Left**:
- Explorer
- Navigator
- Primary sidebar
- Project hierarchy
- Outliner (blender)

**Right**
- Inspector
- Properties
- Utilities
- Secondary sidebar

---

**Top**
- Toolbar
- Navigation

---

**Middle**
- Editor
- Canvas

---

**Components drawer**
- Components' library
- Components' drawer
- UI Library
- UI Selector
- Components

---
**This is not a finite list, we can keep adding options to consider**

### Proposed solution 🟢

Left - **Explorer**
Right - **Inspector**
Top - **Navigation**
Middle - **Canvas**
Component drawer - **Component library**

### Relevant resources/benchmarks 🔗

![image](https://user-images.githubusercontent.com/437214/187906362-61230a77-e1a8-40b8-a4f5-d04e5115faf5.png)

![image](https://user-images.githubusercontent.com/437214/187906390-47188c27-560d-43c8-8dc3-3ec1c1a183ec.png)

![image](https://user-images.githubusercontent.com/437214/187906411-892edf4a-5262-4b1c-8adf-2d10265c2e6a.png)

**Comment by bytasv** [comment]
My personal preference for each:

**Left** 
1. **Explorer** - because we can "explore" and select instances of our app. I also think that maybe it would be good to have `queries` and `mutations` selectable in the explorer in the future (but that's another topic)
2. **Left sidebar** - my 2nd option - `left` because it's immediately clear which side and `sidebar` well because it's side and `sidebar` is also pretty common term to know that it takes entire height of something 🤔 

**Right**
1. **Inspector** - because we can "inspect" and change properties of selected components
2. **Properties** - different variation instead of inspector 😅 
3. **Right sidebar** - if we choose to call left as **Left sidebar**

**Top**
1. **Navigation** - we kinda navigate between releases/editor/preview
2. **Toolbar** - would be my primary choice but we don't really expose much "tooling" there so doesn't seem exactly correct to use this

**Middle**
**Editor** - seems it's also consistently used in many other IDEs

**Components drawer**
1. **Components' library** - IMO this is implementation agnostic name
2. **UI Library** - same as 1st and also either of two sounds good to me

**Comment by Janpot** [comment]
Middle: I'd call it "canvas". I'd reserve "Editor" for the combination of "left"+"center"+"right"

Top: I'd go with "Navigation bar" because it's about navigating toolpad as a whole. I'd reserve "toolbar" for future use. e.g. inside of the aforementioned "Editor"

**Comment by apedroferreira** [comment]
I like "app canvas" too for the middle section.
I would also change `Component's library` to just `Component library`, without the `'s`, seems better that way
About the top, "navbar" or "navigation" sound good.
Not too sure about the left section, "app explorer" doesn't sound bad.

**Comment by prakhargupta1** [comment]
Left: Left sidebar
Right: Right sidebar
Top: Header bar
Middle: Canvas
Component library

**Comment by Janpot** [comment]
> Left: Left sidebar
> Right: Right sidebar

Would we ever consider a right-to-left mode?

**Comment by bytasv** [comment]
> Would we ever consider a right-to-left mode for the UI?

I have no idea, but wondering have you ever seen software with such mode? (curious, because I haven't, just heard about webpages for content that do that)

**Comment by samuelsycamore** [comment]
+1 for "Component library" / "Component drawer" as the grammatically correct phrasing! :)

**Comment by Janpot** [comment]
It just seems suboptimal to me to describe the segments by "where" they are instead of "what" they are. Describing them by "what" they are could also serve as a forcing function for us to think about what function they have within the hierarchy of the application, and help us decide where to add certain future features.

**Comment by bytasv** [comment]
@Janpot what's your vote for left/right then?

**Comment by Janpot** [comment]
"Explorer"/"Inspector" makes sense. But I have no clear preference, as long as it's describing the "what" and not the "where".

**Comment by prakhargupta1** [comment]
The reason I said left and right sidebar was that we may put something on the left that may not qualify to be put under Explorer, or something on the right that may not qualify for Inspector. Though these two terms seem appropriate.

**Comment by Janpot** [comment]
> we may put something on the left that may not qualify to be put under Explorer

Yes, that's a good concern. We could also think differently about it. As in "if we can't come up with a good descriptive name for what's under this panel, perhaps that means the way we are structuring our application is not logical". It could go both ways.
Explorer/Inspector are quite broad terms though, but as far as I'm concerned, we can also just change them if we start radically changing what's inside of them.

**Comment by bytasv** [comment]
IMO if we start seeing more items that could be put on the left side, maybe it would be worth to explore UI as in VS code where you have "activity bar" - that way we could group certain functionality under different names, but explorer would still live as is 🤔 
Anyways, lets proceed with explorer and inspector and as Jan mentioned change it if we see it become problematic

**Comment by bytasv** [comment]
@mui/toolpad based on our conversation I've put a following proposal up:

Left - **Explorer**
Right - **Inspector**
Top - **Navigation**
Middle - **Canvas**
Component drawer - **Component library**

Lemme know if you have any concerns, if not I will close this issue and proceed with updating terminology in the docs
