### ISSUE TITLE
function: support calling other datasources

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#887]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It should be possible to fetch the data of another datasource from the function  datasource. This would allow composing different datasources together freely.
Some ideas for a possible API:

```tsx
export default async function ({ fetchDatasource }) {
  const {data} = await fetchDatasource('myPostgresDatasource', { params: { foo: 1 } }) 
}
```

```tsx
import { fetchDatasource } from '@mui/toolpad-core'

export default async function ({}) {
  const {data} = await fetchDatasource('myPostgresDatasource', { params: { foo: 1 } }) 
}

```

```tsx
import myPostgresDatasource from 'toolpad:myPostgresDatasource'

export default async function ({}) {
  const {data} = await myPostgresDatasource.fetch({ params: { foo: 1 } }) 
}

```

### Motivation 🔦

Bring the power of any datasource to the function datasource. e.g. db admin can write their postgres queries in a SQL editor, a toolpad developer can transform or compose those together in a function datasource.

**Comment by apedroferreira** [comment]
I like the first option better, as maybe we could add other useful things in the arguments in the future

**Comment by prakhargupta1** [comment]
Closing it as it is already being done in custom functions.
