### ISSUE TITLE
Unable to drop components on a new page of app.

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#895]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

It is happening both in Chrome and Firefox. I am able to add components to an old page. 

https://user-images.githubusercontent.com/92228082/188435522-f8b74465-6f16-4f2a-a5d3-4533bbd0d435.mov

**Comment by Janpot** [comment]
Next time this happens, could you please take note of which error is appearing in the devtools console?

**Comment by prakhargupta1** [comment]
It works in incognito mode but doesn't work in my regular session. No error is shown in Console.
