### ISSUE TITLE
Provide 2 basic prebuilt apps as examples

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#902]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The apps will help self-host users to examine steps required to build an app.
 
1. COVID app
2. Dog app

**Comment by apedroferreira** [comment]
i'll take this if it's up for grabs

**Comment by prakhargupta1** [comment]
I'll share DOM code of the apps with you.

**Comment by apedroferreira** [comment]
So which direction do we want to go with this?
1. Show the apps in the beginning for every new user, and they can delete them if they wish
2. Allow choosing some app templates in this panel:

<img width="1792" alt="Screen Shot 2022-09-07 at 15 13 12" src="https://user-images.githubusercontent.com/10789765/188900721-ea8a41bb-ad33-49d2-bcc9-126acfa7b201.png">

I guess we opted for option 2 but just confirming. Both have their pros and cons but option 2 may be a useful feature in itself, as it allows us to provide some "starters" for users.

**Comment by Janpot** [comment]
We will do 2.

**Comment by prakhargupta1** [comment]
App 1: https://toolpad-pr-940.onrender.com/_toolpad/app/cl7t6cpxb0106axq11s54imas/editor/pages/xo1a1q7
App 2: https://master--toolpad.mui.com/_toolpad/app/cl27ajqfu0403a0oz236ay3pj/editor/pages/cl27arb1i00043g693pzhex2r

**Comment by apedroferreira** [comment]
> App 1: https://toolpad-pr-940.onrender.com/_toolpad/app/cl7t6cpxb0106axq11s54imas/editor/pages/xo1a1q7 App 2: https://master--toolpad.mui.com/_toolpad/app/cl27ajqfu0403a0oz236ay3pj/editor/pages/cl27arb1i00043g693pzhex2r

thanks Prakhar! the first link stopped working for some reason (the covid stats app), it says `Not found`

**Comment by prakhargupta1** [comment]
Updated the link, it should work now.

**Comment by apedroferreira** [comment]
> https://master--toolpad.mui.com/_toolpad/app/cl7tbkukv0265awtoxfauiywo/editor/pages/l11ao9l

it worked, thanks!

**Comment by WangLarry** [comment]
need password to open this app

**Comment by prakhargupta1** [comment]
Hi Wang,
Currently it is in development and being used internally. For now, you can self-host to try it out.
