### ISSUE TITLE
DataGrid error overlay overlaps canvas overlay

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#917]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

See screenshot:

<img width="906" alt="Screenshot 2022-09-07 at 17 51 06" src="https://user-images.githubusercontent.com/2109932/188923403-385aaacf-1a29-4c50-8140-480dc393fcc0.png">

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by bytasv** [comment]
@Janpot could you add more details - how could this be reproduced? I've just tried adding datagrid and typography and there is no such overlay 🤔 

![image](https://user-images.githubusercontent.com/437214/201095978-f65610bb-c869-4ece-bd4f-6b75fd0bbc3b.png)

**Comment by Janpot** [comment]
https://master--toolpad.mui.com/_toolpad/app/cl6glc2uh0116aro6ichvqv39/pages/ty33nho
