### ISSUE TITLE
DataGrid elements are crashing with error

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#921]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DataGrids are showing an error state with the error message `_mui_x_data_grid_internals__WEBPACK_IMPORTED_MODULE_0__.useGridColumnGroupingPreProcessors) is not a function.`

<img width="1792" alt="Screen Shot 2022-09-07 at 17 12 42" src="https://user-images.githubusercontent.com/10789765/188928580-8743cc69-b084-4a68-8a48-2de213eddbec.png">

### Expected behavior 🤔

DataGrids render successfully without error

### Steps to reproduce 🕹

Steps:

1. Drag a DataGrid to the app canvas

### Context 🔦

It looks like this might've been caused by the `@mui/x-data-grid-pro` dependency updates in https://github.com/mui/mui-toolpad/pull/909.

**Comment by Janpot** [comment]
This looks like corrupted build after switching branches. Have you tried deleting the `.next` folder and restart the dev server?
