### ISSUE TITLE
Warning when closing dialogs with unsaved changes

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#953]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We should add warning when closing dialog with unsaved changes.

Right now we can accidentally close dialog by clicking outside of it and loose any progress that we did.

### Examples 🌈

1. Create function query
2. Change something in the editor
3. Click outside of dialog
4. Changes are lost without any warning

### Motivation 🔦

I was working with function query when I accidentally closed dialog and lost all the changes. If that was some real work, I'd be really unhappy with that 😅

**Comment by prakhargupta1** [comment]
Closing it as I can't reproduce. Looks like it is already fixed.
If it exists, feel free to reopen this issue.
