### ISSUE TITLE
Investigate docker performance improvements

### ISSUE THREAD

**Issue by bytasv** [mui/mui-toolpad#989]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As per findings and discussion in https://github.com/mui/mui-toolpad/pull/859#discussion_r968872635 we should try to investigate if it's possible to improve docker performance for Macbook CPUs architecture

### Motivation 🔦

Seems that M1/M2 CPUs have to use AMD emulation which causes significant performance degradation

**Comment by oliviertassinari** [comment]
> We could pick this back up at some point: https://github.com/mui/mui-toolpad/pull/618
> 
> I'm wondering if it's the real problem though. I'm on M1 and don't see the same behavior. appsmith and Toolpad hum along on Docker just fine for me.
> 
> Perhaps we can try and build an image on your laptop to verify that it works better?

@Janpot Ok, so maybe it's an issue with how I have Docker configured.

**Comment by Janpot** [comment]
> Ok, so maybe it's an issue with how I have Docker configured.

To verify I'd build an image locally:

```sh
docker build \
  --progress plain \
  -t muicom/toolpad:testing-local \
  -f ./docker/images/toolpad/Dockerfile \
  .
```

It should ensure it's been built for your architecture. Then run it with

```sh
TAG=testing-local docker-compose -f docker/compose/docker-compose.yml up
```

And see if it burns your CPU. If it does we should probably look into your docker setup.

**Comment by oliviertassinari** [comment]
> It should ensure it's been built for your architecture. 

@Janpot Ok, I ahve tried your steps. I don't get the amd64 warning

<img width="309" alt="Screenshot 2022-09-14 at 16 17 41" src="https://user-images.githubusercontent.com/3165635/190179664-7b2f660f-10ca-4125-8190-083e592da4ee.png">

and it's a lot faster. I assume the root problem is that https://hub.docker.com/r/muicom/toolpad/tags would need linux/amd64.
