### ISSUE TITLE
[RFC] Fold mutations into queries

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#990]
### What's the problem? 🤔

Currently the concept of query vs. mutation is about how client-side fetching behaves:

- query: idempotent, there is no problem running them automatically or retry them on error
- mutation: mutates something in the backend, needs to be explicitly run by the user. Can not automatically be retried on error.

In general the difference is only in when it can be triggered. Almost all else about it is identical. I've noticed this leads to a lot of confusion with the less technical team members.

Also, with the current model it's hard to convert between one and the other. You have to decide up front when the query is executed and if you want to change your mind you'll have to start all over.

### Proposed solution 🟢

I propose to fold the `mutation` functionality into the query. We'll add a switch between "run manually" and "run automatically". This will make more clear what the behavioral difference is.
Users will be able to bind to them manually in a very similar way as current mutations. e.g. `await query.fetch()`.
We will also make sure to make the response available as `.data` so the page can bind to it.

### Resources and benchmarks 🔗

Retool:

![Screenshot 2022-09-13 at 14 02 14](https://user-images.githubusercontent.com/2109932/189895872-5cfe2061-8616-42ac-80d9-6b6b5388b94c.png)

Superblocks:
![Screenshot 2022-09-13 at 14 13 43](https://user-images.githubusercontent.com/2109932/189898148-67f283ae-7610-43dc-999b-e016e160a222.png)

Appsmith:
![Screenshot 2022-09-13 at 14 16 56](https://user-images.githubusercontent.com/2109932/189900281-3ea99861-5e10-46aa-a5b3-16821aaeb0ee.png)

**Comment by bharatkashyap** [comment]
Agree with this completely.

**Comment by apedroferreira** [comment]
+1, not seeing any real drawbacks to this at first glance

**Comment by Janpot** [comment]
Copying to do list from https://github.com/mui/mui-toolpad/pull/1122 so I can work on this in multiple PRs

To Do list:
- [ ] Migrate existing mutations to queries (blocked on https://github.com/mui/mui-toolpad/pull/776)
- [ ] Remove current "migrations" feature in favor of queries
- [ ] https://github.com/mui/mui-toolpad/issues/1121
- [ ] Automatically switch to mutation mode when user selects non-idempotent HTTP method in the fetch datasource
