### ISSUE TITLE
App crashes if trying to make column from elements in same row

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#992]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://user-images.githubusercontent.com/10789765/189973588-c6d653d5-65b6-468b-a540-691b38e72c40.mov

### Expected behavior 🤔

The app should not crash, and a column should be properly formed.

**Comment by prakhargupta1** [comment]
Duplicate to #1001
