### ISSUE TITLE
Allow nesting inside of the Paper component

### ISSUE THREAD

**Issue by gerdadesign** [mui/mui-toolpad#993]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, after placing the Paper component onto the canvas, you cannot add more than one other component onto the paper. 
<img width="300" alt="Screen Shot 2022-09-13 at 3 13 04 PM" src="https://user-images.githubusercontent.com/106991024/189994298-e6d1e335-b59d-4528-96e3-0ec7b3cea5fa.png">

The paper component should allow infinite nesting inside. 

### Examples 🌈

A mockup of many nested components within paper components. 
![Nested Components in Paper](https://user-images.githubusercontent.com/106991024/190038363-b9e23b21-da4d-4fa4-945f-ab83fccad1ef.png)

**Comment by WangLarry** [comment]
RenderOverlay is very complex. It is hard to supply this.
