### ISSUE TITLE
Make data grid editable

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#994]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a user I should be able to update a cell of a row (inline) This means that the entire column has to be editable. Eg: ID should not be editable, but address column can be.

### Examples 🌈

https://docs.retool.com/docs/data-in-tables#editable-table-columns

**Comment by bharatkashyap** [comment]
Closing basis: https://github.com/mui/mui-toolpad/issues/1039#issuecomment-1531005595
