### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#997]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

From https://github.com/mui/mui-toolpad/issues/592.
Add Google Analytics to Toolpad for usage reporting.

### Examples 🌈

For now we can probably just do something like in this example?
https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics

**Comment by prakhargupta1** [comment]
I think this issue can be delayed. At this point, the only GA event we'll be interested would be no. of apps built. But I think there would be more ways to measure it. 
Acc. to me, we should do this after the overhaul. Let me know what do you think?

**Comment by apedroferreira** [comment]
> I think this issue can be delayed. At this point, the only GA event we'll be interested would be no. of apps built. But I think there would be more ways to measure it. Acc. to me, we should do this after the overhaul. Let me know what do you think?

It could maybe still be useful to track the amount of traffic and such, but we can also delay it if you think it's best.

**Comment by prakhargupta1** [comment]
Ok, let's do the basic implementation then, I think following events would be good to track:
1. Clicks on View demo button
2. Count of demo views
3. Number of apps created (may not be related to GA)

**Comment by prakhargupta1** [comment]
@apedroferreira Let's track the demo related GA events through this old issue.

**Comment by apedroferreira** [comment]
> @apedroferreira Let's track the demo related GA events through this old issue.

Sounds good, I guess for now we're adding:
- custom event for when an app is successfully created
