### ISSUE TITLE
Add error reporting

### ISSUE THREAD

**Issue by apedroferreira** [mui/mui-toolpad#998]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

From https://github.com/mui/mui-toolpad/issues/592.
Add automatic error reporting to Toolpad.

### Examples 🌈

I'm most familiar with Sentry but feel free to suggest others.
The basic Next.js integration should probably be enough to start with?

**Comment by Janpot** [comment]
I'm fine with Sentry. I think we can disable it for the self-hosted version for now. I'd keep telemetry for self-hosted Toolpad out of scope for this demo feature.

**Comment by oliviertassinari** [comment]
We have Sentry set up for https://mui.com/store/ https://www.notion.so/mui-org/Sentry-5784d0f006b9464b847953c3b23e5311. We also have the credentials here https://www.notion.so/mui-org/Accounts-945f0ccb9f7749ccb9e84b9eb9b13ec7#db24eea458014567a130b0849229356b.

**Comment by oliviertassinari** [comment]
@apedroferreira Regarding the `website` label, it's described at:

<img width="316" alt="Screenshot 2022-09-16 at 01 28 53" src="https://user-images.githubusercontent.com/3165635/190525953-caee7682-c719-4fc5-9697-57d9f1eae844.png">

So, right now, it's about one page: https://mui.com/toolpad. However, It seems that we will use inside toolpad, the app.

**Comment by apedroferreira** [comment]
> @apedroferreira Regarding the `website` label, it's described as:
> 
> <img alt="Screenshot 2022-09-16 at 01 28 53" width="316" src="https://user-images.githubusercontent.com/3165635/190525953-caee7682-c719-4fc5-9697-57d9f1eae844.png">
> 
> https://www.notion.so/mui-org/GitHub-labels-af1ef18d3f534f1dbc086aac87b819e8
> 
> So, right now, it's about one page: https://mui.com/toolpad/. It seems that we are tracking the addition of Sentry inside toolpad, the product.

Oh, I didn't notice you had removed the label, sorry!
I originally took the label from the original issue at https://github.com/mui/mui-toolpad/issues/592, but yeah I guess it's not the best label, it's probably not the best for other issues I've added it to either...
